// Each BK map lives in models/BK/<dir>/ as extracted by banjo-kazooie/tools/extract_maps.py:
//   opa.model.bin  - opaque level geometry (BKModelBin)          [asset id in "opa"]
//   xlu.model.bin  - translucent level geometry, if any (BKModelBin) [asset id in "xlu", "" if none]
//   setup.bin      - cube / camera / lighting stream
const BK_Maps = [
    { name: "SM_SPIRAL_MOUNTAIN", sceneID: "1", dir: "01_SM_SPIRAL_MOUNTAIN", opa: "14CF", xlu: "14D0" },
    { name: "SM_BANJOS_HOUSE", sceneID: "8C", dir: "8C_SM_BANJOS_HOUSE", opa: "14A2", xlu: "14A4" },
    { name: "MM_MUMBOS_MOUNTAIN", sceneID: "2", dir: "02_MM_MUMBOS_MOUNTAIN", opa: "14AA", xlu: "14AB" },
    { name: "MM_TICKERS_TOWER", sceneID: "C", dir: "0C_MM_TICKERS_TOWER", opa: "14AC", xlu: "14AD" },
    { name: "MM_MUMBOS_SKULL", sceneID: "E", dir: "0E_MM_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "TTC_TREASURE_TROVE_COVE", sceneID: "7", dir: "07_TTC_TREASURE_TROVE_COVE", opa: "146B", xlu: "146C" },
    { name: "TTC_BLUBBERS_SHIP", sceneID: "5", dir: "05_TTC_BLUBBERS_SHIP", opa: "146F", xlu: "1470" },
    { name: "TTC_NIPPERS_SHELL", sceneID: "6", dir: "06_TTC_NIPPERS_SHELL", opa: "146D", xlu: "146E" },
    { name: "TTC_SHARKFOOD_ISLAND", sceneID: "8F", dir: "8F_TTC_SHARKFOOD_ISLAND", opa: "1473", xlu: "" },
    { name: "TTC_SANDCASTLE", sceneID: "A", dir: "0A_TTC_SANDCASTLE", opa: "1471", xlu: "1472" },
    { name: "CC_CLANKERS_CAVERN", sceneID: "B", dir: "0B_CC_CLANKERS_CAVERN", opa: "14ED", xlu: "14EE" },
    { name: "CC_WITCH_SWITCH_ROOM", sceneID: "21", dir: "21_CC_WITCH_SWITCH_ROOM", opa: "14EF", xlu: "" },
    { name: "CC_INSIDE_CLANKER", sceneID: "22", dir: "22_CC_INSIDE_CLANKER", opa: "14F0", xlu: "14F1" },
    { name: "CC_GOLDFEATHER_ROOM", sceneID: "23", dir: "23_CC_GOLDFEATHER_ROOM", opa: "14F2", xlu: "" },
    { name: "BGS_BUBBLEGLOOP_SWAMP", sceneID: "D", dir: "0D_BGS_BUBBLEGLOOP_SWAMP", opa: "14D1", xlu: "14D2" },
    { name: "BGS_MR_VILE", sceneID: "10", dir: "10_BGS_MR_VILE", opa: "14D3", xlu: "" },
    { name: "BGS_TIPTUP", sceneID: "11", dir: "11_BGS_TIPTUP", opa: "14D4", xlu: "14D5" },
    { name: "BGS_MUMBOS_SKULL", sceneID: "47", dir: "47_BGS_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "GV_GOBIS_VALLEY", sceneID: "12", dir: "12_GV_GOBIS_VALLEY", opa: "1474", xlu: "1475" },
    { name: "GV_SNS_CHAMBER", sceneID: "92", dir: "92_GV_SNS_CHAMBER", opa: "147E", xlu: "" },
    { name: "GV_MEMORY_GAME", sceneID: "13", dir: "13_GV_MEMORY_GAME", opa: "1476", xlu: "" },
    { name: "GV_SANDYBUTTS_MAZE", sceneID: "14", dir: "14_GV_SANDYBUTTS_MAZE", opa: "1478", xlu: "1479" },
    { name: "GV_WATER_PYRAMID", sceneID: "15", dir: "15_GV_WATER_PYRAMID", opa: "147A", xlu: "147B" },
    { name: "GV_RUBEES_CHAMBER", sceneID: "16", dir: "16_GV_RUBEES_CHAMBER", opa: "147C", xlu: "" },
    { name: "GV_INSIDE_JINXY", sceneID: "1A", dir: "1A_GV_INSIDE_JINXY", opa: "147D", xlu: "" },
    { name: "FP_FREEZEEZY_PEAK", sceneID: "27", dir: "27_FP_FREEZEEZY_PEAK", opa: "14C8", xlu: "14C9" },
    { name: "FP_BOGGYS_IGLOO", sceneID: "41", dir: "41_FP_BOGGYS_IGLOO", opa: "14CA", xlu: "14CE" },
    { name: "FP_WOZZAS_CAVE", sceneID: "7F", dir: "7F_FP_WOZZAS_CAVE", opa: "14CC", xlu: "14CD" },
    { name: "FP_MUMBOS_SKULL", sceneID: "48", dir: "48_FP_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "FP_CHRISTMAS_TREE", sceneID: "53", dir: "53_FP_CHRISTMAS_TREE", opa: "14CB", xlu: "" },
    { name: "MMM_MAD_MONSTER_MANSION", sceneID: "1B", dir: "1B_MMM_MAD_MONSTER_MANSION", opa: "147F", xlu: "1480" },
    { name: "MMM_CHURCH", sceneID: "1C", dir: "1C_MMM_CHURCH", opa: "1486", xlu: "1487" },
    { name: "MMM_CELLAR", sceneID: "1D", dir: "1D_MMM_CELLAR", opa: "1482", xlu: "149B" },
    { name: "MMM_TUMBLARS_SHED", sceneID: "24", dir: "24_MMM_TUMBLARS_SHED", opa: "1488", xlu: "" },
    { name: "MMM_WELL", sceneID: "25", dir: "25_MMM_WELL", opa: "1495", xlu: "1496" },
    { name: "MMM_NAPPERS_ROOM", sceneID: "26", dir: "26_MMM_NAPPERS_ROOM", opa: "1485", xlu: "149A" },
    { name: "MMM_EGG_ROOM", sceneID: "28", dir: "28_MMM_EGG_ROOM", opa: "1489", xlu: "148A" },
    { name: "MMM_NOTE_ROOM", sceneID: "29", dir: "29_MMM_NOTE_ROOM", opa: "148B", xlu: "148C" },
    { name: "MMM_FEATHER_ROOM", sceneID: "2A", dir: "2A_MMM_FEATHER_ROOM", opa: "148D", xlu: "148E" },
    { name: "MMM_SECRET_CHURCH_ROOM", sceneID: "2B", dir: "2B_MMM_SECRET_CHURCH_ROOM", opa: "1483", xlu: "1484" },
    { name: "MMM_BATHROOM", sceneID: "2C", dir: "2C_MMM_BATHROOM", opa: "148F", xlu: "1490" },
    { name: "MMM_BEDROOM", sceneID: "2D", dir: "2D_MMM_BEDROOM", opa: "1491", xlu: "1492" },
    { name: "MMM_HONEYCOMB_ROOM", sceneID: "2E", dir: "2E_MMM_HONEYCOMB_ROOM", opa: "1493", xlu: "1494" },
    { name: "MMM_WATERDRAIN_BARREL", sceneID: "2F", dir: "2F_MMM_WATERDRAIN_BARREL", opa: "1481", xlu: "1497" },
    { name: "MMM_MUMBOS_SKULL", sceneID: "30", dir: "30_MMM_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "MMM_INSIDE_LOGGO", sceneID: "8D", dir: "8D_MMM_INSIDE_LOGGO", opa: "1498", xlu: "1499" },
    { name: "RBB_RUSTY_BUCKET_BAY", sceneID: "31", dir: "31_RBB_RUSTY_BUCKET_BAY", opa: "14B0", xlu: "14B1" },
    { name: "RBB_ANCHOR_ROOM", sceneID: "8B", dir: "8B_RBB_ANCHOR_ROOM", opa: "14C5", xlu: "14C6" },
    { name: "RBB_ENGINE_ROOM", sceneID: "34", dir: "34_RBB_ENGINE_ROOM", opa: "14B2", xlu: "14B3" },
    { name: "RBB_WAREHOUSE", sceneID: "35", dir: "35_RBB_WAREHOUSE", opa: "14B4", xlu: "14B5" },
    { name: "RBB_BOATHOUSE", sceneID: "36", dir: "36_RBB_BOATHOUSE", opa: "14B6", xlu: "14B7" },
    { name: "RBB_CONTAINER_1", sceneID: "37", dir: "37_RBB_CONTAINER_1", opa: "14B8", xlu: "" },
    { name: "RBB_CONTAINER_2", sceneID: "3E", dir: "3E_RBB_CONTAINER_2", opa: "14B9", xlu: "" },
    { name: "RBB_CONTAINER_3", sceneID: "38", dir: "38_RBB_CONTAINER_3", opa: "14BA", xlu: "" },
    { name: "RBB_CREW_CABIN", sceneID: "39", dir: "39_RBB_CREW_CABIN", opa: "14BD", xlu: "" },
    { name: "RBB_BOSS_BOOM_BOX", sceneID: "3A", dir: "3A_RBB_BOSS_BOOM_BOX", opa: "14BE", xlu: "14BF" },
    { name: "RBB_STORAGE_ROOM", sceneID: "3B", dir: "3B_RBB_STORAGE_ROOM", opa: "14C1", xlu: "14C2" },
    { name: "RBB_KITCHEN", sceneID: "3C", dir: "3C_RBB_KITCHEN", opa: "14C3", xlu: "14C4" },
    { name: "RBB_NAVIGATION_ROOM", sceneID: "3D", dir: "3D_RBB_NAVIGATION_ROOM", opa: "14C0", xlu: "14C7" },
    { name: "RBB_CAPTAINS_CABIN", sceneID: "3F", dir: "3F_RBB_CAPTAINS_CABIN", opa: "14BB", xlu: "14BC" },
    { name: "CCW_HUB", sceneID: "40", dir: "40_CCW_HUB", opa: "14D8", xlu: "14E3" },
    { name: "CCW_SPRING", sceneID: "43", dir: "43_CCW_SPRING", opa: "14D9", xlu: "14E4" },
    { name: "CCW_SUMMER", sceneID: "44", dir: "44_CCW_SUMMER", opa: "14DA", xlu: "14E5" },
    { name: "CCW_AUTUMN", sceneID: "45", dir: "45_CCW_AUTUMN", opa: "14DB", xlu: "14E6" },
    { name: "CCW_WINTER", sceneID: "46", dir: "46_CCW_WINTER", opa: "14DC", xlu: "14E7" },
    { name: "CCW_SPRING_MUMBOS_SKULL", sceneID: "4A", dir: "4A_CCW_SPRING_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_SUMMER_MUMBOS_SKULL", sceneID: "4B", dir: "4B_CCW_SUMMER_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_AUTUMN_MUMBOS_SKULL", sceneID: "4C", dir: "4C_CCW_AUTUMN_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_WINTER_MUMBOS_SKULL", sceneID: "4D", dir: "4D_CCW_WINTER_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_SUMMER_ZUBBA_HIVE", sceneID: "5A", dir: "5A_CCW_SUMMER_ZUBBA_HIVE", opa: "14DD", xlu: "" },
    { name: "CCW_SPRING_ZUBBA_HIVE", sceneID: "5B", dir: "5B_CCW_SPRING_ZUBBA_HIVE", opa: "14DD", xlu: "" },
    { name: "CCW_AUTUMN_ZUBBA_HIVE", sceneID: "5C", dir: "5C_CCW_AUTUMN_ZUBBA_HIVE", opa: "14DD", xlu: "" },
    { name: "CCW_SPRING_NABNUTS_HOUSE", sceneID: "5E", dir: "5E_CCW_SPRING_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_SUMMER_NABNUTS_HOUSE", sceneID: "5F", dir: "5F_CCW_SUMMER_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_AUTUMN_NABNUTS_HOUSE", sceneID: "60", dir: "60_CCW_AUTUMN_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_WINTER_NABNUTS_HOUSE", sceneID: "61", dir: "61_CCW_WINTER_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_WINTER_HONEYCOMB_ROOM", sceneID: "62", dir: "62_CCW_WINTER_HONEYCOMB_ROOM", opa: "14E0", xlu: "" },
    { name: "CCW_AUTUMN_NABNUTS_WATER_SUPPLY", sceneID: "63", dir: "63_CCW_AUTUMN_NABNUTS_WATER_SUPPLY", opa: "14E1", xlu: "14E2" },
    { name: "CCW_WINTER_NABNUTS_WATER_SUPPLY", sceneID: "64", dir: "64_CCW_WINTER_NABNUTS_WATER_SUPPLY", opa: "14E1", xlu: "14E2" },
    { name: "CCW_SPRING_WHIPCRACK_ROOM", sceneID: "65", dir: "65_CCW_SPRING_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "CCW_SUMMER_WHIPCRACK_ROOM", sceneID: "66", dir: "66_CCW_SUMMER_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "CCW_AUTUMN_WHIPCRACK_ROOM", sceneID: "67", dir: "67_CCW_AUTUMN_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "CCW_WINTER_WHIPCRACK_ROOM", sceneID: "68", dir: "68_CCW_WINTER_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "GL_MM_LOBBY", sceneID: "69", dir: "69_GL_MM_LOBBY", opa: "14F3", xlu: "150B" },
    { name: "GL_TTC_AND_CC_PUZZLE", sceneID: "6A", dir: "6A_GL_TTC_AND_CC_PUZZLE", opa: "14F4", xlu: "150C" },
    { name: "GL_180_NOTE_DOOR", sceneID: "6B", dir: "6B_GL_180_NOTE_DOOR", opa: "14F5", xlu: "1510" },
    { name: "GL_RED_CAULDRON_ROOM", sceneID: "6C", dir: "6C_GL_RED_CAULDRON_ROOM", opa: "14F6", xlu: "150D" },
    { name: "GL_TTC_LOBBY", sceneID: "6D", dir: "6D_GL_TTC_LOBBY", opa: "14F7", xlu: "1512" },
    { name: "GL_GV_LOBBY", sceneID: "6E", dir: "6E_GL_GV_LOBBY", opa: "14F8", xlu: "14A8" },
    { name: "GL_FP_LOBBY", sceneID: "6F", dir: "6F_GL_FP_LOBBY", opa: "14F9", xlu: "14FA" },
    { name: "GL_GV_PUZZLE", sceneID: "74", dir: "74_GL_GV_PUZZLE", opa: "14FD", xlu: "" },
    { name: "GL_CC_LOBBY", sceneID: "70", dir: "70_GL_CC_LOBBY", opa: "14FB", xlu: "1507" },
    { name: "GL_MMM_LOBBY", sceneID: "75", dir: "75_GL_MMM_LOBBY", opa: "14FE", xlu: "" },
    { name: "GL_CRYPT", sceneID: "7A", dir: "7A_GL_CRYPT", opa: "14FF", xlu: "" },
    { name: "GL_STATUE_ROOM", sceneID: "71", dir: "71_GL_STATUE_ROOM", opa: "1500", xlu: "150E" },
    { name: "GL_BGS_LOBBY", sceneID: "72", dir: "72_GL_BGS_LOBBY", opa: "1501", xlu: "1511" },
    { name: "GL_640_NOTE_DOOR", sceneID: "76", dir: "76_GL_640_NOTE_DOOR", opa: "1502", xlu: "1508" },
    { name: "GL_RBB_LOBBY", sceneID: "77", dir: "77_GL_RBB_LOBBY", opa: "1503", xlu: "1509" },
    { name: "GL_RBB_AND_MMM_PUZZLE", sceneID: "78", dir: "78_GL_RBB_AND_MMM_PUZZLE", opa: "1504", xlu: "150A" },
    { name: "GL_CCW_LOBBY", sceneID: "79", dir: "79_GL_CCW_LOBBY", opa: "1505", xlu: "" },
    { name: "GL_FF_ENTRANCE", sceneID: "80", dir: "80_GL_FF_ENTRANCE", opa: "1506", xlu: "1514" },
    { name: "GL_FURNACE_FUN", sceneID: "8E", dir: "8E_GL_FURNACE_FUN", opa: "14E8", xlu: "" },
    { name: "GL_DINGPOT", sceneID: "93", dir: "93_GL_DINGPOT", opa: "150F", xlu: "1513" },
    { name: "GL_BATTLEMENTS", sceneID: "90", dir: "90_GL_BATTLEMENTS", opa: "14FC", xlu: "1515" },
    { name: "CS_START_NINTENDO", sceneID: "1E", dir: "1E_CS_START_NINTENDO", opa: "149D", xlu: "14A1" },
    { name: "CS_START_RAREWARE", sceneID: "1F", dir: "1F_CS_START_RAREWARE", opa: "149E", xlu: "14A0" },
    { name: "CS_INTRO_GL_DINGPOT_1", sceneID: "7B", dir: "7B_CS_INTRO_GL_DINGPOT_1", opa: "150F", xlu: "" },
    { name: "CS_INTRO_BANJOS_HOUSE_1", sceneID: "7C", dir: "7C_CS_INTRO_BANJOS_HOUSE_1", opa: "14A2", xlu: "" },
    { name: "CS_SPIRAL_MOUNTAIN_1", sceneID: "7D", dir: "7D_CS_SPIRAL_MOUNTAIN_1", opa: "14CF", xlu: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_2", sceneID: "7E", dir: "7E_CS_SPIRAL_MOUNTAIN_2", opa: "14CF", xlu: "14D0" },
    { name: "CS_INTRO_GL_DINGPOT_2", sceneID: "81", dir: "81_CS_INTRO_GL_DINGPOT_2", opa: "150F", xlu: "" },
    { name: "CS_ENTERING_GL_MACHINE_ROOM", sceneID: "82", dir: "82_CS_ENTERING_GL_MACHINE_ROOM", opa: "150F", xlu: "" },
    { name: "CS_GAME_OVER_MACHINE_ROOM", sceneID: "83", dir: "83_CS_GAME_OVER_MACHINE_ROOM", opa: "150F", xlu: "" },
    { name: "CS_UNUSED_MACHINE_ROOM", sceneID: "84", dir: "84_CS_UNUSED_MACHINE_ROOM", opa: "150F", xlu: "" },
    { name: "CS_SPIRAL_MOUNTAIN_3", sceneID: "85", dir: "85_CS_SPIRAL_MOUNTAIN_3", opa: "14CF", xlu: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_4", sceneID: "86", dir: "86_CS_SPIRAL_MOUNTAIN_4", opa: "14CF", xlu: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_5", sceneID: "87", dir: "87_CS_SPIRAL_MOUNTAIN_5", opa: "14A6", xlu: "" },
    { name: "CS_SPIRAL_MOUNTAIN_6", sceneID: "88", dir: "88_CS_SPIRAL_MOUNTAIN_6", opa: "14CF", xlu: "14D0" },
    { name: "CS_INTRO_SPIRAL_7", sceneID: "94", dir: "94_CS_INTRO_SPIRAL_7", opa: "14CF", xlu: "14D0" },
    { name: "CS_END_SPIRAL_MOUNTAIN_1", sceneID: "98", dir: "98_CS_END_SPIRAL_MOUNTAIN_1", opa: "149F", xlu: "14A3" },
    { name: "CS_END_SPIRAL_MOUNTAIN_2", sceneID: "99", dir: "99_CS_END_SPIRAL_MOUNTAIN_2", opa: "149F", xlu: "14A3" },
    { name: "CS_END_ALL_100", sceneID: "95", dir: "95_CS_END_ALL_100", opa: "14A9", xlu: "14A5" },
    { name: "CS_END_NOT_100", sceneID: "20", dir: "20_CS_END_NOT_100", opa: "14A9", xlu: "14A5" },
    { name: "CS_INTRO_BANJOS_HOUSE_2", sceneID: "89", dir: "89_CS_INTRO_BANJOS_HOUSE_2", opa: "14A2", xlu: "14A4" },
    { name: "CS_INTRO_BANJOS_HOUSE_3", sceneID: "8A", dir: "8A_CS_INTRO_BANJOS_HOUSE_3", opa: "14A2", xlu: "14A4" },
    { name: "CS_END_BEACH_1", sceneID: "96", dir: "96_CS_END_BEACH_1", opa: "14A9", xlu: "14A5" },
    { name: "CS_END_BEACH_2", sceneID: "97", dir: "97_CS_END_BEACH_2", opa: "14A9", xlu: "14A5" },
    { name: "FILE_SELECT", sceneID: "91", dir: "91_FILE_SELECT", opa: "14A2", xlu: "14A4" },
];

const BT_Maps = [
    { name: "SM - Spiral Mountain", pointer: "7998", sceneID: "AF", modelAPointer: "c56c", modelBPointer: "c570" },
    { name: "SM - behind the waterfall", pointer: "7994", sceneID: "AE", modelAPointer: "c580", modelBPointer: "c584" },
    { name: "SM - Banjo's House", pointer: "7ca8", sceneID: "0173", modelAPointer: "c574", modelBPointer: "c578" },
    { name: "SM - Banjo's House (Destroyed)", pointer: "7ca8", sceneID: "0173", modelAPointer: "c5a8", modelBPointer: "" },
    { name: "SM - Digger Tunnel", pointer: "7be0", sceneID: "0141", modelAPointer: "c598", modelBPointer: "" },
    { name: "GL - Entrance", pointer: "7990", sceneID: "AD", modelAPointer: "c57c", modelBPointer: "" },
    { name: "JV - Jinjo Village", pointer: "7be4", sceneID: "0142", modelAPointer: "c88c", modelBPointer: "" },
    { name: "JV - Bottles house", pointer: "7be8", sceneID: "0143", modelAPointer: "c8c8", modelBPointer: "c8d4" },
    { name: "JV - King Jingalings throne room", pointer: "7bec", sceneID: "0144", modelAPointer: "c8cc", modelBPointer: "" },
    { name: "JV - Zombiefied Throne Room", pointer: "7d48", sceneID: "019B", modelAPointer: "c8d0", modelBPointer: "" },
    { name: "JV - Jinjo's house", pointer: "7bf0", sceneID: "0145", modelAPointer: "c8c4", modelBPointer: "" },
    /*{ name: "JV - Green jinjo's house", pointer: "7bf0", sceneID: "0145", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Black jinjo's house", pointer: "7bf4", sceneID: "0146", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Yellow jinjo's house", pointer: "7bf8", sceneID: "0147", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Blue jinjo's house", pointer: "7bfc", sceneID: "0148", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Unused jinjo's house", pointer: "7c00", sceneID: "0149", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Brown jinjo's house", pointer: "7c04", sceneID: "014A", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Orange jinjo's house", pointer: "7c08", sceneID: "014B", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Purple jinjo's house", pointer: "7c0c", sceneID: "014C", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Red jinjo's house", pointer: "7c10", sceneID: "014D", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - White jinjo's house", pointer: "7c14", sceneID: "014E", modelAPointer: "c8c4", modelBPointer: "" },*/
    { name: "Mumbo's Skull", pointer: "7c34", sceneID: "0156", modelAPointer: "c58c", modelBPointer: "c590" },
    { name: "Wumba's Wigwam", pointer: "7c38", sceneID: "0157", modelAPointer: "c588", modelBPointer: "c5a0" },
    { name: "IOH - Wooden Hollow", pointer: "7c18", sceneID: "014F", modelAPointer: "c890", modelBPointer: "" },
    { name: "IOH - Heggy's egg shed", pointer: "7c1c", sceneID: "0150", modelAPointer: "c8a4", modelBPointer: "" },
    { name: "IOH - Jiggywiggy's temple", pointer: "7c20", sceneID: "0151", modelAPointer: "c894", modelBPointer: "" },
    { name: "IOH - Plateau", pointer: "7c24", sceneID: "0152", modelAPointer: "c898", modelBPointer: "" },
    { name: "IOH - Honey B's Hive", pointer: "7c28", sceneID: "0153", modelAPointer: "c8c0", modelBPointer: "" },
    { name: "IOH - Pine Grove", pointer: "7c2c", sceneID: "0154", modelAPointer: "c89c", modelBPointer: "c8a0" },
    { name: "IOH - Cliff Top", pointer: "7c30", sceneID: "0155", modelAPointer: "c8a8", modelBPointer: "" },
    { name: "IOH - Wasteland", pointer: "7c44", sceneID: "015A", modelAPointer: "c8ac", modelBPointer: "" },
    { name: "IOH - Digger Tunnel", pointer: "7c48", sceneID: "015B", modelAPointer: "c8b8", modelBPointer: "" },
    { name: "IOH - Quagmire", pointer: "7c4c", sceneID: "015C", modelAPointer: "c8b0", modelBPointer: "" },
    { name: "MT", pointer: "79bc", sceneID: "B8", modelAPointer: "c5b0", modelBPointer: "c5b4" },
    { name: "MT - Prison Compound", pointer: "79c4", sceneID: "B9", modelAPointer: "c5b8", modelBPointer: "c5bc" },
    { name: "MT - Columns Vault", pointer: "79c8", sceneID: "BA", modelAPointer: "c5c0", modelBPointer: "" },
    { name: "MT - Mayan Kickball Stadium", pointer: "79cc", sceneID: "BB", modelAPointer: "c5c4", modelBPointer: "" },
    { name: "MT - Code Chamber", pointer: "79cc", sceneID: "BC", modelAPointer: "c5c8", modelBPointer: "" },
    { name: "MT - Jade Snake Grove", pointer: "79ec", sceneID: "C4", modelAPointer: "c5cc", modelBPointer: "c5d0" },
    { name: "MT - Treasure Chamber", pointer: "79f0", sceneID: "C5", modelAPointer: "c5d4", modelBPointer: "" },
    { name: "MT - Kickball Arena", pointer: "79f4", sceneID: "C6", modelAPointer: "c5d8", modelBPointer: "" },
    { name: "MT - kickball arena", pointer: "7a00", sceneID: "00C9", modelAPointer: "c5d8", modelBPointer: "" },
    { name: "MT - Targitzan's Slighty Sacred Temple", pointer: "7cb8", sceneID: "0177", modelAPointer: "c5dc", modelBPointer: "" },
    { name: "MT - Inside Targitzan's temple", pointer: "7cbc", sceneID: "0178", modelAPointer: "c5e0", modelBPointer: "" },
    { name: "MT - Targitzan temple lobby", pointer: "7cc0", sceneID: "0179", modelAPointer: "c5e4", modelBPointer: "" },
    { name: "MT - Targitzan's Really Sacred Chamber", pointer: "7cc4", sceneID: "017A", modelAPointer: "c5dc", modelBPointer: "" },
    { name: "GGM", pointer: "79f8", sceneID: "C7", modelAPointer: "c61c", modelBPointer: "c660" },
    { name: "GGM - fuel depot", pointer: "7a04", sceneID: "00CA", modelAPointer: "c5ec", modelBPointer: "c650" },
    { name: "GGM - crushing shed", pointer: "7a08", sceneID: "00CB", modelAPointer: "c5f0", modelBPointer: "c628" },
    { name: "GGM - flooded caves", pointer: "7a0c", sceneID: "00CC", modelAPointer: "c5f4", modelBPointer: "c63c" },
    { name: "GGM - water storage", pointer: "7a10", sceneID: "00CD", modelAPointer: "c5f8", modelBPointer: "c648" },
    { name: "GGM - waterfall cavern", pointer: "7a14", sceneID: "00CE", modelAPointer: "c5fc", modelBPointer: "c620" },
    { name: "GGM - power hut basement", pointer: "7a18", sceneID: "00CF", modelAPointer: "c600", modelBPointer: "c634" },
    { name: "GGM - chuffy's cab", pointer: "7a1c", sceneID: "00D0", modelAPointer: "c604", modelBPointer: "" },
    { name: "GGM - inside chuffy's boiler boss", pointer: "7a20", sceneID: "00D1", modelAPointer: "c608", modelBPointer: "" },
    { name: "GGM - gloomy caverns", pointer: "7a24", sceneID: "00D2", modelAPointer: "c60c", modelBPointer: "c630" },
    { name: "GGM - generator caverns", pointer: "7a28", sceneID: "00D3", modelAPointer: "c610", modelBPointer: "c640" },
    { name: "GGM - power hut", pointer: "7a2c", sceneID: "00D4", modelAPointer: "c614", modelBPointer: "c62c" },
    { name: "GGM - train station", pointer: "7a38", sceneID: "00D7", modelAPointer: "c618", modelBPointer: "" },
    { name: "GGM - prospectors hut", pointer: "7a3c", sceneID: "00D8", modelAPointer: "c638", modelBPointer: "c664" },
    { name: "GGM - toxic gas cave", pointer: "7a44", sceneID: "00DA", modelAPointer: "c644", modelBPointer: "" },
    { name: "GGM - canary cave", pointer: "7a48", sceneID: "00DB", modelAPointer: "c624", modelBPointer: "c64c" },
    { name: "GGM - Inside Chuffy's wagon", pointer: "7b60", sceneID: "0121", modelAPointer: "c654", modelBPointer: "" },
    { name: "GGM - water supply pipe", pointer: "7b74", sceneID: "0126", modelAPointer: "c700", modelBPointer: "" },
    { name: "GGM - Ordnance Shooting Entrance", pointer: "7c68", sceneID: "0163", modelAPointer: "c65c", modelBPointer: "" },
    { name: "GGM - ordnance storage", pointer: "7a4c", sceneID: "00DC", modelAPointer: "c658", modelBPointer: "" },
    /*{ name: "GGM - Ordnance Shooting Game", pointer: "7c6c", sceneID: "0164", modelAPointer: "", modelBPointer: "" },
    { name: "GGM - Ordnance Shooting Game Multi", pointer: "7c70", sceneID: "0165", modelAPointer: "", modelBPointer: "" },*/
    { name: "WW - Witchyworld", pointer: "7a34", sceneID: "00D6", modelAPointer: "c668", modelBPointer: "c698" },
    { name: "WW - dodgem dome lobby", pointer: "7a50", sceneID: "00DD", modelAPointer: "c68c", modelBPointer: "" },
    /*{ name: "WW - dodgem challenge 1 vs 1", pointer: "7a54", sceneID: "00DE", modelAPointer: "c690", modelBPointer: "" },
    { name: "WW - dodgem challenge 2 vs 1", pointer: "7a58", sceneID: "00DF", modelAPointer: "c690", modelBPointer: "" },
    { name: "WW - dodgem challenge 3 vs 1", pointer: "7a5c", sceneID: "00E0", modelAPointer: "c690", modelBPointer: "" },*/
    { name: "WW - crazy castle stockade", pointer: "7a60", sceneID: "00E1", modelAPointer: "c66c", modelBPointer: "" },
    { name: "WW - crazy castle lobby", pointer: "7a64", sceneID: "00E2", modelAPointer: "c674", modelBPointer: "" },
    { name: "WW - crazy castle pump room", pointer: "7a68", sceneID: "00E3", modelAPointer: "c670", modelBPointer: "" },
    { name: "WW - balloon burst game", pointer: "7a6c", sceneID: "00E4", modelAPointer: "c6a0", modelBPointer: "" },
    { name: "WW - hoop hurry game", pointer: "7a70", sceneID: "00E5", modelAPointer: "c6a0", modelBPointer: "" },
    { name: "WW - star spinner", pointer: "7a74", sceneID: "00E6", modelAPointer: "c688", modelBPointer: "c69c" },
    { name: "WW - the inferno", pointer: "7a78", sceneID: "00E7", modelAPointer: "c678", modelBPointer: "" },
    { name: "WW - Haunted Caverns", pointer: "7a88", sceneID: "00EB", modelAPointer: "c680", modelBPointer: "" },
    { name: "WW - Cave of Horrors", pointer: "7a84", sceneID: "00EA", modelAPointer: "c67c", modelBPointer: "" },
    { name: "WW - Train Station", pointer: "7a8c", sceneID: "00EC", modelAPointer: "c684", modelBPointer: "c6b0" },
    { name: "WW - Mr. Patch", pointer: "7ac0", sceneID: "00F9", modelAPointer: "c694", modelBPointer: "" },
    /*{ name: "WW - Saucer of Peril", pointer: "7b6c", sceneID: "0124", modelAPointer: "", modelBPointer: "" },
    { name: "WW - crazy castle stockade (sop)", pointer: "7bc8", sceneID: "013B", modelAPointer: "c66c", modelBPointer: "" },
    { name: "WW - star spinner (sop)", pointer: "7bcc", sceneID: "013C", modelAPointer: "", modelBPointer: "" },*/
    { name: "JRL - Town", pointer: "7d78", sceneID: "01A7", modelAPointer: "6e24", modelBPointer: "" }, //c6f8
    { name: "JRL - Town buildings", pointer: "", sceneID: "01A7", modelAPointer: "6e58", modelBPointer: "" },
    { name: "JRL - UFO area", pointer: "", sceneID: "", modelAPointer: "6e28", modelBPointer: "" },
    { name: "JRL - Smugglers Cavern", pointer: "7d74", sceneID: "01A6", modelAPointer: "6e2c", modelBPointer: "6e5c" },
    { name: "JRL - Atlantis", pointer: "7d7c", sceneID: "01A8", modelAPointer: "6e30", modelBPointer: "" },
    { name: "JRL - Sunken Ship area", pointer: "", sceneID: "", modelAPointer: "6e48", modelBPointer: "" },
    { name: "JRL - Wumba area", pointer: "", sceneID: "", modelAPointer: "6e54", modelBPointer: "6e64" },
    { name: "JRL - Sea Bottom locker area", pointer: "7d80", sceneID: "01A9", modelAPointer: "6e4c", modelBPointer: "" },
    { name: "JRL - Sea Bottom big fish area", pointer: "", sceneID: "", modelAPointer: "6e50", modelBPointer: "6e68" },
    { name: "JRL - Passage UFO to Smugglers", pointer: "", sceneID: "", modelAPointer: "6e34", modelBPointer: "" },
    { name: "JRL - Passage UFO to Atlantis", pointer: "", sceneID: "", modelAPointer: "6e38", modelBPointer: "" },
    { name: "JRL - Passage Atlantis to ship", pointer: "", sceneID: "", modelAPointer: "6e3c", modelBPointer: "" },
    { name: "JRL - Passage ship to locker", pointer: "", sceneID: "", modelAPointer: "6e40", modelBPointer: "" },
    { name: "JRL - Passage locker to big fish", pointer: "", sceneID: "", modelAPointer: "6e44", modelBPointer: "" },
    { name: "JRL - Jollys", pointer: "7a90", sceneID: "00ED", modelAPointer: "c6e4", modelBPointer: "c714" },
    //{ name: "JRL - Wumba's Wigwam", pointer: "7b5c", sceneID: "0120", modelAPointer: "c588", modelBPointer: "c5a0" },
    { name: "JRL - Pawno", pointer: "7a94", sceneID: "00EE", modelAPointer: "c6ec", modelBPointer: "c6f0" },
    { name: "JRL - Inside UFO", pointer: "7aa0", sceneID: "00F1", modelAPointer: "c6b8", modelBPointer: "c718" },
    { name: "JRL - Ancient Swimming Baths", pointer: "7aac", sceneID: "00F4", modelAPointer: "c6bc", modelBPointer: "c6c0" },
    { name: "JRL - Water", pointer: "", sceneID: "", modelAPointer: "c6f8", modelBPointer: "" },
    //{ name: "JRL - Objects (Beta JRL)", pointer: "7ab0", sceneID: "00F5", modelAPointer: "", modelBPointer: "" },
    { name: "JRL - Electric Eels Lair", pointer: "7ab4", sceneID: "00F6", modelAPointer: "c6c4", modelBPointer: "c6c8" },
    { name: "JRL - Seaweed Santchum", pointer: "7ab8", sceneID: "00F7", modelAPointer: "c6cc", modelBPointer: "c6d0" },
    { name: "JRL - Inside the big fish", pointer: "7abc", sceneID: "00F8", modelAPointer: "c6d4", modelBPointer: "c6d8" },
    { name: "JRL - Temple of the Fishes", pointer: "7ac4", sceneID: "00FA", modelAPointer: "c6dc", modelBPointer: "c6fc" },
    { name: "JRL - Lord Woo Fak Fak", pointer: "7acc", sceneID: "00FC", modelAPointer: "c6e8", modelBPointer: "" },
    { name: "JRL - Blubber's Wave Race Hire", pointer: "7ad8", sceneID: "00FF", modelAPointer: "c6f4", modelBPointer: "" },
    { name: "JRL - sea bottom cavern", pointer: "7ce0", sceneID: "0181", modelAPointer: "c708", modelBPointer: "" },
    /*{ name: "JRL - submarine multi", pointer: "7ce4", sceneID: "0182", modelAPointer: "", modelBPointer: "" },*/
    { name: "TDL", pointer: "7b24", sceneID: "0112", modelAPointer: "c720", modelBPointer: "c750" },
    { name: "TDL - terry's nest", pointer: "7b28", sceneID: "0113", modelAPointer: "c734", modelBPointer: "c75c" },
    { name: "TDL - train station", pointer: "7b2c", sceneID: "0114", modelAPointer: "c740", modelBPointer: "" },
    { name: "TDL - oogle boogles cave", pointer: "7b30", sceneID: "0115", modelAPointer: "c744", modelBPointer: "" },
    { name: "TDL - inside the mountain", pointer: "7b34", sceneID: "0116", modelAPointer: "c72c", modelBPointer: "c730" },
    { name: "TDL - river passage", pointer: "7b38", sceneID: "0117", modelAPointer: "c738", modelBPointer: "c73c" },
    { name: "TDL - styracosaurus family cave", pointer: "7b3c", sceneID: "0118", modelAPointer: "c728", modelBPointer: "" },
    { name: "TDL - unga bunga's cave", pointer: "7b40", sceneID: "0119", modelAPointer: "c748", modelBPointer: "" },
    { name: "TDL - stomping plains", pointer: "7b44", sceneID: "011A", modelAPointer: "c74c", modelBPointer: "" },
    { name: "TDL - bonfire caverns", pointer: "7b48", sceneID: "011B", modelAPointer: "c724", modelBPointer: "" },
    { name: "TDL - Wumba's Wigwam Big (missing)", pointer: "7b64", sceneID: "0122", modelAPointer: "", modelBPointer: "" },
    { name: "TDL - Inside chompa's belly", pointer: "7b68", sceneID: "0123", modelAPointer: "c608", modelBPointer: "" },
    { name: "GI - outside", pointer: "7adc", sceneID: "0100", modelAPointer: "c760", modelBPointer: "c7a8" },
    { name: "GI - floor 1", pointer: "7ae0", sceneID: "0101", modelAPointer: "c764", modelBPointer: "c7a4" },
    { name: "GI - Train Station", pointer: "7ae4", sceneID: "0102", modelAPointer: "c77c", modelBPointer: "c7b8" },
    { name: "GI - workers quarters", pointer: "7ae8", sceneID: "0103", modelAPointer: "c790", modelBPointer: "c7dc" },
    { name: "GI - trash compactor", pointer: "7aec", sceneID: "0104", modelAPointer: "c780", modelBPointer: "" },
    { name: "GI - toxic waste disposal", pointer: "7b20", sceneID: "0111", modelAPointer: "c78c", modelBPointer: "c7a0" },
    { name: "GI - elevator shaft", pointer: "7af0", sceneID: "0105", modelAPointer: "c774", modelBPointer: "" },
    { name: "GI - floor 2", pointer: "7af4", sceneID: "0106", modelAPointer: "c768", modelBPointer: "c7c4" },
    { name: "GI - floor 2 (electromagnet chamber)", pointer: "7af8", sceneID: "0107", modelAPointer: "c788", modelBPointer: "" },
    { name: "GI - floor 3", pointer: "7afc", sceneID: "0108", modelAPointer: "c76C", modelBPointer: "c7c8" },
    { name: "GI - floor 3 (boiler plant)", pointer: "7b00", sceneID: "0109", modelAPointer: "c784", modelBPointer: "c7d8" },
    { name: "GI - floor 3 (packing room)", pointer: "7b04", sceneID: "010A", modelAPointer: "c7b0", modelBPointer: "" },
    { name: "GI - floor 4", pointer: "7b08", sceneID: "010B", modelAPointer: "c770", modelBPointer: "c7cc" },
    { name: "GI - floor 4 (cable room)", pointer: "7b0c", sceneID: "010C", modelAPointer: "c798", modelBPointer: "" },
    { name: "GI - floor 4 (quality control)", pointer: "7b10", sceneID: "010D", modelAPointer: "c79c", modelBPointer: "c7ac" },
    { name: "GI - floor 4 (Clinker's Cavern Lobby)", pointer: "7cf8", sceneID: "0187", modelAPointer: "c7c0", modelBPointer: "c7e0" },
    { name: "GI - floor 4 (Clinker's Cavern)", pointer: "7c64", sceneID: "0162", modelAPointer: "c7bc", modelBPointer: "" },
    { name: "GI - floor 5", pointer: "7b14", sceneID: "010E", modelAPointer: "c794", modelBPointer: "" },
    { name: "GI - basement", pointer: "7b18", sceneID: "010F", modelAPointer: "c778", modelBPointer: "c7d4" },
    { name: "GI - basement (repair depot)", pointer: "7b1c", sceneID: "0110", modelAPointer: "c7b4", modelBPointer: "" },
    { name: "GI - water supply pipe", pointer: "7b70", sceneID: "0125", modelAPointer: "c704", modelBPointer: "" },
    { name: "HFP - lava side", pointer: "7b78", sceneID: "0127", modelAPointer: "c7ec", modelBPointer: "c7f0" },
    { name: "HFP - icy side", pointer: "7b7c", sceneID: "0128", modelAPointer: "c7f4", modelBPointer: "c7f8" },
    { name: "HFP - lava train station", pointer: "7b80", sceneID: "0129", modelAPointer: "c808", modelBPointer: "" },
    { name: "HFP - ice train station", pointer: "7b84", sceneID: "012A", modelAPointer: "c800", modelBPointer: "c804" },
    { name: "HFP - chilli billi", pointer: "7b88", sceneID: "012B", modelAPointer: "c81c", modelBPointer: "c82c" },
    { name: "HFP - chilly willy", pointer: "7b8c", sceneID: "012C", modelAPointer: "c820", modelBPointer: "c830" },
    { name: "HFP - colosseum kickball stadium lobby", pointer: "7b90", sceneID: "012D", modelAPointer: "c814", modelBPointer: "" },
    /*{ name: "HFP - colosseum kickball stadium - Quarterfinal", pointer: "7b94", sceneID: "012E", modelAPointer: "", modelBPointer: "" },
    { name: "HFP - colosseum kickball stadium - Semifinal", pointer: "7b98", sceneID: "012F", modelAPointer: "", modelBPointer: "" },
    { name: "HFP - colosseum kickball stadium - Final", pointer: "7b9c", sceneID: "0130", modelAPointer: "", modelBPointer: "" },*/
    { name: "HFP - boggy's igloo", pointer: "7ba0", sceneID: "0131", modelAPointer: "c7fc", modelBPointer: "c828" },
    { name: "HFP - icicle grotto", pointer: "7ba4", sceneID: "0132", modelAPointer: "c80c", modelBPointer: "" },
    { name: "HFP - inside the volcano", pointer: "7ba8", sceneID: "0133", modelAPointer: "c818", modelBPointer: "" },
    { name: "CCL", pointer: "7c60", sceneID: "0161", modelAPointer: "c834", modelBPointer: "c854" },
    { name: "CCL - Cloud Cuckoo Land", pointer: "7bb4", sceneID: "0136", modelAPointer: "c834", modelBPointer: "c854" },
    { name: "CCL - inside the trashcan", pointer: "7bb8", sceneID: "0137", modelAPointer: "c84c", modelBPointer: "c850" },
    { name: "CCL - inside the cheesewedge", pointer: "7bbc", sceneID: "0138", modelAPointer: "c848", modelBPointer: "c860" },
    { name: "CCL - central cavern", pointer: "7bc4", sceneID: "013A", modelAPointer: "c838", modelBPointer: "c858" },
    { name: "CCL - inside the pot o gold", pointer: "7bd0", sceneID: "013D", modelAPointer: "c83c", modelBPointer: "c840" },
    { name: "CK - Cauldron Keep", pointer: "7c50", sceneID: "015D", modelAPointer: "c86c", modelBPointer: "c870" },
    { name: "CK - Gatehouse", pointer: "7c54", sceneID: "015E", modelAPointer: "c878", modelBPointer: "72e4" },
    { name: "CK - Quiz", pointer: "7c58", sceneID: "015F", modelAPointer: "c87c", modelBPointer: "" },
    { name: "CK - Gun Chamber", pointer: "7c5c", sceneID: "0160", modelAPointer: "c874", modelBPointer: "" },
    //{ name: "CK - Gun Room Still", pointer: "7c84", sceneID: "016A", modelAPointer: "", modelBPointer: "" },
    { name: "CK - Final Boss", pointer: "", sceneID: "", modelAPointer: "c884", modelBPointer: "" },
    { name: "CK - Final Boss Inside", pointer: "", sceneID: "", modelAPointer: "c880", modelBPointer: "" },
    /*{ name: "CK", pointer: "7d44", sceneID: "019A", modelAPointer: "", modelBPointer: "" },
    { name: "MT - Multi", pointer: "7c74", sceneID: "0166", modelAPointer: "", modelBPointer: "" },
    { name: "MT - still", pointer: "7c78", sceneID: "0167", modelAPointer: "", modelBPointer: "" },
    { name: "HFP - Icy side still", pointer: "7c7c", sceneID: "0168", modelAPointer: "", modelBPointer: "" },
    { name: "Bottles house still", pointer: "7c80", sceneID: "0169", modelAPointer: "", modelBPointer: "" },
    { name: "GGM", pointer: "7c98", sceneID: "016F", modelAPointer: "", modelBPointer: "" },
    { name: "GGM", pointer: "7c9c", sceneID: "0170", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Balloons", pointer: "7cc8", sceneID: "017B", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Hoops", pointer: "7ccc", sceneID: "017C", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Packing Game", pointer: "7cd0", sceneID: "017D", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Kickball Arena", pointer: "7cd8", sceneID: "017F", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Kickball Arena 2", pointer: "7cdc", sceneID: "0180", modelAPointer: "", modelBPointer: "" },
    { name: "TDL - chompa's belly multi", pointer: "7ce8", sceneID: "0183", modelAPointer: "", modelBPointer: "" },
    { name: "Beta green pipe", pointer: "7cec", sceneID: "0184", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Trash Can", pointer: "7cf0", sceneID: "0185", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Dodgems", pointer: "7cf4", sceneID: "0186", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Bee Hive", pointer: "7cfc", sceneID: "0188", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Quiz Game", pointer: "7d00", sceneID: "0189", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Game select screen", pointer: "7c3c", sceneID: "0158", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Opening cut scene", pointer: "7c40", sceneID: "0159", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Intro", pointer: "7d08", sceneID: "018B", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Sisters explain BOB", pointer: "7d0c", sceneID: "018C", modelAPointer: "", modelBPointer: "" },
    { name: "CS - About to Blast Jingaling", pointer: "7d18", sceneID: "018F", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Getting Zapped", pointer: "7d1c", sceneID: "0190", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Zombiefied Throne Room", pointer: "7cd4", sceneID: "017E", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Gained energy from Jingaling", pointer: "7d10", sceneID: "018D", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Party Ended", pointer: "7d20", sceneID: "0191", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Bottles gets home", pointer: "7d24", sceneID: "0192", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Bottles is brought back to life!", pointer: "7d28", sceneID: "0193", modelAPointer: "", modelBPointer: "" },
    { name: "CS - B and K About to use BOB", pointer: "7d2c", sceneID: "0194", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Lets fix Bottles Next", pointer: "7d30", sceneID: "0195", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Playing with Gruntys Head", pointer: "7d34", sceneID: "0196", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Giving Jingaliong back life", pointer: "7d38", sceneID: "0197", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Jingalings Temple gets back life", pointer: "7d3c", sceneID: "0198", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Jingaling Celebrates that hes back", pointer: "7d40", sceneID: "0199", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Credits", pointer: "7d4c", sceneID: "019C", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Character Parade", pointer: "7d50", sceneID: "019D", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Two Years have Passed", pointer: "7960", sceneID: "A1", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Drill Starts", pointer: "7964", sceneID: "A2", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Drill goes through Boulders", pointer: "7968", sceneID: "A3", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Use Magic to Lift Boulder", pointer: "796c", sceneID: "A4", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Revenge is Mine!", pointer: "7970", sceneID: "A5", modelAPointer: "10510", modelBPointer: "" },
    { name: "CS - Witches Leave Spiral Mountain", pointer: "7974", sceneID: "A6", modelAPointer: "", modelBPointer: "" },
    { name: "CS - House Destoryed", pointer: "7978", sceneID: "A7", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Playing Poker", pointer: "797c", sceneID: "A8", modelAPointer: "", modelBPointer: "10518" },
    { name: "CS - Earthquake!", pointer: "7980", sceneID: "A9", modelAPointer: "", modelBPointer: "" },
    { name: "CS - It Stopped", pointer: "7984", sceneID: "AA", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Get out of the House!", pointer: "7988", sceneID: "AB", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Come on!", pointer: "798c", sceneID: "AC", modelAPointer: "", modelBPointer: "" },*/
];

const OOT_Maps = [
    { name: "Spot 00 - Hyrule Field", file: "spot00_scene" },
    { name: "Spot 01 - Kakariko Village", file: "spot01_scene" },
    { name: "Spot 02 - Graveyard", file: "spot02_scene" },
    { name: "Spot 03 - Zora's River", file: "spot03_scene" },
    { name: "Spot 04 - Kokiri Forest", file: "spot04_scene" },
    { name: "Spot 05 - Sacred Forest Meadow", file: "spot05_scene" },
    { name: "Spot 06 - Lake Hylia", file: "spot06_scene" },
    { name: "Spot 07 - Zora's Domain", file: "spot07_scene" },
    { name: "Spot 08 - Zora's Fountain", file: "spot08_scene" },
    { name: "Spot 09 - Gerudo Valley", file: "spot09_scene" },
    { name: "Spot 10 - Lost Woods", file: "spot10_scene" },
    { name: "Spot 11 - Desert Colossus", file: "spot11_scene" },
    { name: "Spot 12 - Gerudo's Fortress", file: "spot12_scene" },
    { name: "Spot 13 - Haunted Wasteland", file: "spot13_scene" },
    { name: "Spot 15 - Hyrule Castle", file: "spot15_scene" },
    { name: "Spot 16 - Death Mountain Trail", file: "spot16_scene" },
    { name: "Spot 17 - Death Mountain Crater", file: "spot17_scene" },
    { name: "Spot 18 - Goron City", file: "spot18_scene" },
    { name: "Spot 20 - Lon Lon Ranch", file: "spot20_scene" },
    { name: "Back Alley (Day)", file: "market_alley_scene" },
    { name: "Back Alley (Night)", file: "market_alley_n_scene" },
    { name: "Back Alley House (Dog Lady)", file: "impa_scene" },
    { name: "Back Alley House (Man in Green)", file: "kakariko3_scene" },
    { name: "Barinade's Lair", file: "bdan_boss_scene" },
    { name: "Bazaar", file: "shop1_scene" },
    { name: "Bombchu Bowling Alley", file: "bowling_scene" },
    { name: "Bombchu Shop", file: "night_shop_scene" },
    { name: "Bongo Bongo's Lair", file: "HAKAdan_bs_scene" },
    { name: "Bottom of the Well", file: "HAKAdanCH_scene" },
    { name: "Carpenter Boss's House", file: "kakariko_scene" },
    { name: "Carpenters' Tent", file: "tent_scene" },
    { name: "Castle Courtyard", file: "nakaniwa_scene" },
    { name: "Castle Hedge Maze (Day)", file: "hairal_niwa_scene" },
    { name: "Castle Hedge Maze (Night)", file: "hairal_niwa_n_scene" },
    { name: "Chamber of the Sages", file: "kenjyanoma_scene" },
    { name: "Cutscene Map", file: "hiral_demo_scene" },
    { name: "Dampe's Grave & Windmill", file: "hakasitarelay_scene" },
    { name: "Dodongo's Cavern", file: "ddan_scene" },
    { name: "Fairy's Fountain (Healing Fairies)", file: "yousei_izumi_tate_scene" },
    { name: "Fire Temple", file: "HIDAN_scene" },
    { name: "Fishing Pond", file: "turibori_scene" },
    { name: "Forest Temple", file: "Bmori1_scene" },
    { name: "Ganon's Castle Exterior", file: "ganon_tou_scene" },
    { name: "Ganon's Tower", file: "ganon_scene" },
    { name: "Ganon's Tower (Collapsing)", file: "ganon_sonogo_scene" },
    { name: "Ganon's Tower Exterior (Collapsing)", file: "ganon_final_scene" },
    { name: "Ganon Battle Arena", file: "ganon_demo_scene" },
    { name: "Ganondorf's Lair", file: "ganon_boss_scene" },
    { name: "Gerudo Training Ground", file: "men_scene" },
    { name: "Gohma's Lair", file: "ydan_boss_scene" },
    { name: "Goron Shop", file: "golon_scene" },
    { name: "Granny's Potion Shop", file: "mahouya_scene" },
    { name: "Grave (Fairy's Fountain)", file: "hakaana2_scene" },
    { name: "Grave (Redead)", file: "hakaana_scene" },
    { name: "Gravekeeper's Hut", file: "hut_scene" },
    { name: "Great Fairy's Fountain (Spells)", file: "yousei_izumi_yoko_scene" },
    { name: "Great Fairy's Fountain (Upgrades)", file: "daiyousei_izumi_scene" },
    { name: "Grottos", file: "kakusiana_scene" },
    { name: "Guard House", file: "miharigoya_scene" },
    { name: "Happy Mask Shop", file: "face_shop_scene" },
    { name: "House of Skulltula", file: "kinsuta_scene" },
    { name: "House of Twins", file: "kokiri_home3_scene" },
    { name: "Ice Cavern", file: "ice_doukutu_scene" },
    { name: "Impa's House", file: "labo_scene" },
    { name: "Inside Ganon's Castle", file: "ganontika_scene" },
    { name: "Inside Ganon's Castle (Collapsing)", file: "ganontikasonogo_scene" },
    { name: "Inside Jabu-Jabu's Belly", file: "bdan_scene" },
    { name: "Inside the Deku Tree", file: "ydan_scene" },
    { name: "Kakariko Potion Shop", file: "drag_scene" },
    { name: "King Dodongo's Lair", file: "ddan_boss_scene" },
    { name: "Know-It-All Brothers' House", file: "kokiri_home_scene" },
    { name: "Kokiri Shop", file: "kokiri_shop_scene" },
    { name: "Lakeside Laboratory", file: "hylia_labo_scene" },
    { name: "Link's House", file: "link_home_scene" },
    { name: "Lon Lon Ranch House & Tower", file: "souko_scene" },
    { name: "Market (Child - Day)", file: "market_day_scene" },
    { name: "Market (Child - Night)", file: "market_night_scene" },
    { name: "Market (Ruins)", file: "market_ruins_scene" },
    { name: "Market Entrance (Child - Day)", file: "entra_scene" },
    { name: "Market Entrance (Child - Night)", file: "entra_n_scene" },
    { name: "Market Entrance (Ruins)", file: "enrui_scene" },
    { name: "Market Potion Shop", file: "alley_shop_scene" },
    { name: "Mido's House", file: "kokiri_home4_scene" },
    { name: "Morpha's Lair", file: "MIZUsin_bs_scene" },
    { name: "Phantom Ganon's Lair", file: "moribossroom_scene" },
    { name: "Royal Family's Tomb", file: "hakaana_ouke_scene" },
    { name: "Saria's House", file: "kokiri_home5_scene" },
    { name: "Shadow Temple", file: "HAKAdan_scene" },
    { name: "Shooting Gallery", file: "syatekijyou_scene" },
    { name: "Spirit Temple", file: "jyasinzou_scene" },
    { name: "Stable", file: "malon_stable_scene" },
    { name: "Temple of Time", file: "tokinoma_scene" },
    { name: "Temple of Time Exterior (Day)", file: "shrine_scene" },
    { name: "Temple of Time Exterior (Night)", file: "shrine_n_scene" },
    { name: "Temple of Time Exterior (Ruins)", file: "shrine_r_scene" },
    { name: "Thieves' Hideout", file: "gerudoway_scene" },
    { name: "Treasure Chest Shop", file: "takaraya_scene" },
    { name: "Twinrova's Lair", file: "jyasinboss_scene" },
    { name: "Volvagia's Lair", file: "FIRE_bs_scene" },
    { name: "Water Temple", file: "MIZUsin_scene" },
    { name: "Zora Shop", file: "zoora_scene" }
];

const MM_Maps = [
    { name: "Ancient Castle of Ikana", file: "Z2_CASTLE" },
    { name: "Astral Observatory", file: "Z2_TENMON_DAI" },
    { name: "Before the Portal to Termina", file: "Z2_OPENINGDAN" },
    { name: "Beneath the Graveyard", file: "Z2_HAKASHITA" },
    { name: "Beneath the Well", file: "Z2_REDEAD" },
    { name: "Bomb Shop", file: "Z2_BOMYA" },
    { name: "Clock Tower Interior", file: "Z2_INSIDETOWER" },
    { name: "Clock Tower Rooftop", file: "Z2_OKUJOU" },
    { name: "Cucco Shack", file: "Z2_F01C" },
    { name: "Curiosity Shop", file: "Z2_AYASHIISHOP" },
    { name: "Cutscene Map", file: "SPOT00" },
    { name: "Dampe's House", file: "Z2_DANPEI2TEST" },
    { name: "Deku King's Chamber", file: "Z2_DEKU_KING" },
    { name: "Deku Palace", file: "Z2_22DEKUCITY" },
    { name: "Deku Scrub Playground", file: "Z2_DEKUTES" },
    { name: "Deku Shrine", file: "Z2_DANPEI" },
    { name: "Doggy Racetrack", file: "Z2_F01_B" },
    { name: "East Clock Town", file: "Z2_TOWN" },
    { name: "Fairy's Fountain", file: "Z2_YOUSEI_IZUMI" },
    { name: "Fisherman's Hut", file: "Z2_FISHERMAN" },
    { name: "Ghost Hut", file: "Z2_TOUGITES" },
    { name: "Giants' Chamber", file: "Z2_KYOJINNOMA" },
    { name: "Goht's Lair", file: "Z2_HAKUGIN_BS" },
    { name: "Gorman Track", file: "Z2_KOEPONARACE" },
    { name: "Goron Graveyard", file: "Z2_GORON_HAKA" },
    { name: "Goron Racetrack", file: "Z2_GORONRACE" },
    { name: "Goron Shop", file: "Z2_GORONSHOP" },
    { name: "Goron Shrine", file: "Z2_16GORON_HOUSE" },
    { name: "Goron Village (Spring)", file: "Z2_11GORONNOSATO2" },
    { name: "Goron Village (Winter)", file: "Z2_11GORONNOSATO" },
    { name: "Great Bay (Cutscene)", file: "Z2_KONPEKI_ENT" },
    { name: "Great Bay Coast", file: "Z2_30GYOSON" },
    { name: "Great Bay Temple", file: "Z2_SEA" },
    { name: "Grottos", file: "KAKUSIANA" },
    { name: "Gyorg's Lair", file: "Z2_SEA_BS" },
    { name: "Honey & Darling's Shop", file: "Z2_BOWLING" },
    { name: "Igos du Ikana's Lair", file: "Z2_IKNINSIDE" },
    { name: "Ikana Canyon", file: "Z2_IKANA" },
    { name: "Ikana Graveyard", file: "Z2_BOTI" },
    { name: "Laundry Pool", file: "Z2_ALLEY" },
    { name: "Lost Woods", file: "Z2_LOST_WOODS" },
    { name: "Lottery Shop", file: "Z2_TAKARAKUJI" },
    { name: "Magic Hags' Potion Shop", file: "Z2_WITCH_SHOP" },
    { name: "Majora's Lair", file: "Z2_LAST_BS" },
    { name: "Marine Research Lab", file: "Z2_LABO" },
    { name: "Mayor's Residence", file: "Z2_SONCHONOIE" },
    { name: "Milk Bar", file: "Z2_MILK_BAR" },
    { name: "Milk Road", file: "Z2_ROMANYMAE" },
    { name: "Mountain Smithy", file: "Z2_KAJIYA" },
    { name: "Mountain Village (Spring)", file: "Z2_10YUKIYAMANOMURA2" },
    { name: "Mountain Village (Winter)", file: "Z2_10YUKIYAMANOMURA" },
    { name: "Music Box House", file: "Z2_MUSICHOUSE" },
    { name: "North Clock Town", file: "Z2_BACKTOWN" },
    { name: "Oceanside Spider House", file: "Z2_KINDAN2" },
    { name: "Odolwa's Lair", file: "Z2_MITURIN_BS" },
    { name: "Path to Goron Village (Spring)", file: "Z2_17SETUGEN2" },
    { name: "Path to Goron Village (Winter)", file: "Z2_17SETUGEN" },
    { name: "Path to Mountain Village", file: "Z2_13HUBUKINOMITI" },
    { name: "Path to Snowhead", file: "Z2_14YUKIDAMANOMITI" },
    { name: "Pinnacle Rock", file: "Z2_SINKAI" },
    { name: "Pirates' Fortress", file: "Z2_KAIZOKU" },
    { name: "Pirates' Fortress Exterior", file: "Z2_TORIDE" },
    { name: "Pirates' Fortress Interior", file: "Z2_PIRATE" },
    { name: "Post Office", file: "Z2_POSTHOUSE" },
    { name: "Ranch House & Barn", file: "Z2_OMOYA" },
    { name: "Road to Ikana", file: "Z2_IKANAMAE" },
    { name: "Road to Southern Swamp", file: "Z2_24KEMONOMITI" },
    { name: "Romani Ranch", file: "Z2_F01" },
    { name: "Sakon's Hideout", file: "Z2_SECOM" },
    { name: "Secret Shrine", file: "Z2_RANDOM" },
    { name: "Snowhead", file: "Z2_12HAKUGINMAE" },
    { name: "Snowhead Temple", file: "Z2_HAKUGIN" },
    { name: "South Clock Town", file: "Z2_CLOCKTOWER" },
    { name: "Southern Swamp (Clear)", file: "Z2_20SICHITAI2" },
    { name: "Southern Swamp (Poisoned)", file: "Z2_20SICHITAI" },
    { name: "Stock Pot Inn", file: "Z2_YADOYA" },
    { name: "Stone Tower", file: "Z2_F40" },
    { name: "Stone Tower (Inverted)", file: "Z2_F41" },
    { name: "Stone Tower Temple", file: "Z2_INISIE_N" },
    { name: "Stone Tower Temple (Inverted)", file: "Z2_INISIE_R" },
    { name: "Swamp Shooting Gallery", file: "Z2_SYATEKI_MORI" },
    { name: "Swamp Spider House", file: "Z2_KINSTA1" },
    { name: "Swordsman's School", file: "Z2_DOUJOU" },
    { name: "Termina Field", file: "Z2_00KEIKOKU" },
    { name: "The Moon", file: "Z2_SOUGEN" },
    { name: "The Moon - Deku Trial", file: "Z2_LAST_DEKU" },
    { name: "The Moon - Goron Trial", file: "Z2_LAST_GORON" },
    { name: "The Moon - Link Trial", file: "Z2_LAST_LINK" },
    { name: "The Moon - Zora Trial", file: "Z2_LAST_ZORA" },
    { name: "Tourist Information", file: "Z2_MAP_SHOP" },
    { name: "Town Shooting Gallery", file: "Z2_SYATEKI_MIZU" },
    { name: "Trading Post", file: "Z2_8ITEMSHOP" },
    { name: "Treasure Chest Shop", file: "Z2_TAKARAYA" },
    { name: "Twinmold's Lair", file: "Z2_INISIE_BS" },
    { name: "Waterfall Rapids", file: "Z2_35TAKI" },
    { name: "West Clock Town", file: "Z2_ICHIBA" },
    { name: "Woodfall", file: "Z2_21MITURINMAE" },
    { name: "Woodfall Temple", file: "Z2_MITURIN" },
    { name: "Woods of Mystery", file: "Z2_26SARUNOMORI" },
    { name: "Zora Cape", file: "Z2_31MISAKI" },
    { name: "Zora Hall", file: "Z2_33ZORACITY" },
    { name: "Zora Hall Rooms", file: "Z2_BANDROOM" }
];

const OOT3D_Maps = [
    { name: "Spot 00 - Hyrule Field", file: "spot00_info.zsi" },
    { name: "Spot 01 - Kakariko Village", file: "spot01_info.zsi" },
    { name: "Spot 02 - Graveyard", file: "spot02_info.zsi" },
    { name: "Spot 03 - Zora's River", file: "spot03_info.zsi" },
    { name: "Spot 04 - Kokiri Forest", file: "spot04_info.zsi" },
    { name: "Spot 05 - Sacred Forest Meadow", file: "spot05_info.zsi" },
    { name: "Spot 06 - Lake Hylia", file: "spot06_info.zsi" },
    { name: "Spot 07 - Zora's Domain", file: "spot07_info.zsi" },
    { name: "Spot 08 - Zora's Fountain", file: "spot08_info.zsi" },
    { name: "Spot 09 - Gerudo Valley", file: "spot09_info.zsi" },
    { name: "Spot 10 - Lost Woods", file: "spot10_info.zsi" },
    { name: "Spot 11 - Desert Colossus", file: "spot11_info.zsi" },
    { name: "Spot 12 - Gerudo's Fortress", file: "spot12_info.zsi" },
    { name: "Spot 13 - Haunted Wasteland", file: "spot13_info.zsi" },
    { name: "Spot 15 - Hyrule Castle", file: "spot15_info.zsi" },
    { name: "Spot 16 - Death Mountain Trail", file: "spot16_info.zsi" },
    { name: "Spot 17 - Death Mountain Crater", file: "spot17_info.zsi" },
    { name: "Spot 18 - Goron City", file: "spot18_info.zsi" },
    { name: "Spot 20 - Lon Lon Ranch", file: "spot20_info.zsi" },
    { name: "Spot 99 - Hyrule Field (Title)", file: "spot99_info.zsi" },
    { name: "Back Alley (Day)", file: "market_alley_info.zsi" },
    { name: "Back Alley (Night)", file: "market_alley_n_info.zsi" },
    { name: "Back Alley House (Dog Lady)", file: "kakariko_impa_info.zsi" },
    { name: "Back Alley House (Man in Green)", file: "kakariko_home3_info.zsi" },
    { name: "Barinade's Lair", file: "bdan_boss_info.zsi" },
    { name: "Bazaar", file: "shop_info.zsi" },
    { name: "Bombchu Bowling Alley", file: "bowling_info.zsi" },
    { name: "Bombchu Shop", file: "shop_night_info.zsi" },
    { name: "Bongo Bongo's Lair", file: "hakadan_boss_info.zsi" },
    { name: "Bottom of the Well", file: "hakadan_ch_info.zsi" },
    { name: "Carpenter Boss's House", file: "kakariko_info.zsi" },
    { name: "Carpenters' Tent", file: "tent_info.zsi" },
    { name: "Castle Courtyard", file: "nakaniwa_info.zsi" },
    { name: "Castle Hedge Maze (Day)", file: "hairal_niwa_info.zsi" },
    { name: "Castle Hedge Maze (Night)", file: "hairal_niwa_n_info.zsi" },
    { name: "Chamber of the Sages", file: "kenjyanoma_info.zsi" },
    { name: "Cutscene Map", file: "hiral_demo_info.zsi" },
    { name: "Dampe's Grave & Windmill", file: "hakasitarelay_info.zsi" },
    { name: "Dodongo's Cavern", file: "ddan_info.zsi" },
    { name: "Fairy's Fountain (Healing Fairies)", file: "yousei_izumi_tate_info.zsi" },
    { name: "Fire Temple", file: "hidan_info.zsi" },
    { name: "Fishing Pond", file: "turibori_info.zsi" },
    { name: "Forest Temple", file: "bmori1_info.zsi" },
    { name: "Ganon's Castle Exterior", file: "ganon_tou_info.zsi" },
    { name: "Ganon's Tower", file: "ganon_info.zsi" },
    { name: "Ganon's Tower (Collapsing)", file: "ganon_sonogo_info.zsi" },
    { name: "Ganon's Tower Exterior (Collapsing)", file: "ganon_final_info.zsi" },
    { name: "Ganon Battle Arena", file: "ganon_demo_info.zsi" },
    { name: "Ganondorf's Lair", file: "ganon_boss_info.zsi" },
    { name: "Gerudo Training Ground", file: "men_info.zsi" },
    { name: "Gohma's Lair", file: "ydan_boss_info.zsi" },
    { name: "Goron Shop", file: "shop_golon_info.zsi" },
    { name: "Granny's Potion Shop", file: "mahouya_info.zsi" },
    { name: "Grave (Fairy's Fountain)", file: "hakaana2_info.zsi" },
    { name: "Grave (Redead)", file: "hakaana_info.zsi" },
    { name: "Gravekeeper's Hut", file: "hut_info.zsi" },
    { name: "Great Fairy's Fountain (Spells)", file: "yousei_izumi_yoko_info.zsi" },
    { name: "Great Fairy's Fountain (Upgrades)", file: "daiyousei_izumi_info.zsi" },
    { name: "Grottos", file: "kakusiana_info.zsi" },
    { name: "Guard House", file: "miharigoya_info.zsi" },
    { name: "Happy Mask Shop", file: "shop_face_info.zsi" },
    { name: "House of Skulltula", file: "kinsuta_info.zsi" },
    { name: "Ice Cavern", file: "ice_doukutu_info.zsi" },
    { name: "Impa's House", file: "labo_info.zsi" },
    { name: "Inside Ganon's Castle", file: "ganontika_info.zsi" },
    { name: "Inside Ganon's Castle (Collapsing)", file: "ganontikasonogo_info.zsi" },
    { name: "Inside Jabu-Jabu's Belly", file: "bdan_info.zsi" },
    { name: "Inside the Deku Tree", file: "ydan_info.zsi" },
    { name: "Kakariko Potion Shop", file: "shop_drag_info.zsi" },
    { name: "King Dodongo's Lair", file: "ddan_boss_info.zsi" },
    { name: "Know-It-All Brothers' House", file: "k_home_info.zsi" },
    { name: "Kokiri Shop", file: "kokiri_info.zsi" },
    { name: "Lakeside Laboratory", file: "hylia_labo_info.zsi" },
    { name: "Link's House", file: "link_info.zsi" },
    { name: "Lon Lon Ranch House & Tower", file: "souko_info.zsi" },
    { name: "Market (Child - Day)", file: "market_day_info.zsi" },
    { name: "Market (Child - Night)", file: "market_night_info.zsi" },
    { name: "Market (Ruins)", file: "market_ruins_info.zsi" },
    { name: "Market Entrance (Child - Day)", file: "entra_day_info.zsi" },
    { name: "Market Entrance (Child - Night)", file: "entra_night_info.zsi" },
    { name: "Market Entrance (Ruins)", file: "entra_ruins_info.zsi" },
    { name: "Market Potion Shop", file: "shop_alley_info.zsi" },
    { name: "Mido's House", file: "k_home4_info.zsi" },
    { name: "Morpha's Lair", file: "mizusin_boss_info.zsi" },
    { name: "Phantom Ganon's Lair", file: "moriboss_info.zsi" },
    { name: "Royal Family's Tomb", file: "hakaana_ouke_info.zsi" },
    { name: "Saria's House", file: "k_home5_info.zsi" },
    { name: "Shadow Temple", file: "hakadan_info.zsi" },
    { name: "Shooting Gallery", file: "syatekijyou_info.zsi" },
    { name: "Spirit Temple", file: "jyasinzou_info.zsi" },
    { name: "Stable", file: "stable_info.zsi" },
    { name: "Temple of Time", file: "tokinoma_info.zsi" },
    { name: "Temple of Time Exterior (Day)", file: "shrine_info.zsi" },
    { name: "Temple of Time Exterior (Night)", file: "shrine_n_info.zsi" },
    { name: "Temple of Time Exterior (Ruins)", file: "shrine_r_info.zsi" },
    { name: "Thieves' Hideout", file: "gerudoway_info.zsi" },
    { name: "Treasure Chest Shop", file: "takaraya_info.zsi" },
    { name: "Twinrova's Lair", file: "jyasinzou_boss_info.zsi" },
    { name: "Twins' House", file: "k_home3_info.zsi" },
    { name: "Volvagia's Lair", file: "fire_bs_info.zsi" },
    { name: "Water Temple", file: "mizusin_info.zsi" },
    { name: "Zora Shop", file: "zoora_info.zsi" }
    //{ name: "Bottom of the Well (MQ)", file: "hakadan_ch_dd_info.zsi" },
    //{ name: "Dodongo's Cavern (MQ)", file: "ddan_dd_info.zsi" },
    //{ name: "Fire Temple (MQ)", file: "hidan_dd_info.zsi" },
    //{ name: "Forest Temple (MQ)", file: "bmori1_dd_info.zsi" },
    //{ name: "Gerudo Training Ground (MQ)", file: "men_dd_info.zsi" },
    //{ name: "Ice Cavern (MQ)", file: "ice_doukutu_dd_info.zsi" },
    //{ name: "Inside Ganon's Castle (MQ)", file: "ganontika_dd_info.zsi" },
    //{ name: "Inside Jabu-Jabu's Belly (MQ)", file: "bdan_dd_info.zsi" },
    //{ name: "Inside the Deku Tree (MQ)", file: "ydan_dd_info.zsi" },
    //{ name: "Shadow Temple (MQ)", file: "hakadan_dd_info.zsi" },
    //{ name: "Spirit Temple (MQ)", file: "jyasinzou_dd_info.zsi" },
    //{ name: "Water Temple (MQ)", file: "mizusin_dd_info.zsi" }
];

const MM3D_Maps = [
    { name: "Ancient Castle of Ikana", file: "z2_castle_info.zsi" },
    { name: "Astral Observatory", file: "z2_tenmon_dai_info.zsi" },
    { name: "Before the Portal to Termina", file: "z2_openingdan_info.zsi" },
    { name: "Beneath the Graves", file: "z2_hakashita_info.zsi" },
    { name: "Beneath the Well", file: "z2_redead_info.zsi" },
    { name: "Bomb Shop", file: "z2_bomya_info.zsi" },
    { name: "Clock Tower Interior", file: "z2_insidetower_info.zsi" },
    { name: "Clock Tower Rooftop", file: "z2_okujou_info.zsi" },
    { name: "Cucco Shack", file: "z2_f01c_info.zsi" },
    { name: "Curiosity Shop & Kafei's Hideout", file: "z2_ayashiishop_info.zsi" },
    { name: "Cutscene Map", file: "spot00_info.zsi" },
    { name: "Dampe's House", file: "z2_danpei2test_info.zsi" },
    { name: "Deku King's Chamber", file: "z2_deku_king_info.zsi" },
    { name: "Deku Palace", file: "z2_22dekucity_info.zsi" },
    { name: "Deku Scrub Playground", file: "z2_dekutes_info.zsi" },
    { name: "Deku Shrine", file: "z2_danpei_info.zsi" },
    { name: "Doggy Racetrack", file: "z2_f01_b_info.zsi" },
    { name: "East Clock Town", file: "z2_town_info.zsi" },
    { name: "Fairy's Fountain", file: "z2_yousei_izumi_info.zsi" },
    { name: "Fisherman's Hut", file: "z2_fisherman_info.zsi" },
    { name: "Ghost Hut", file: "z2_tougites_info.zsi" },
    { name: "Giants' Chamber", file: "z2_kyojinnoma_info.zsi" },
    { name: "Goht's Lair", file: "z2_hakugin_bs_info.zsi" },
    { name: "Gorman Track", file: "z2_koeponarace_info.zsi" },
    { name: "Goron Graveyard", file: "z2_goron_haka_info.zsi" },
    { name: "Goron Racetrack", file: "z2_goronrace_info.zsi" },
    { name: "Goron Shop", file: "z2_goronshop_info.zsi" },
    { name: "Goron Shrine", file: "z2_16goron_house_info.zsi" },
    { name: "Goron Village (Spring)", file: "z2_11goronnosato2_info.zsi" },
    { name: "Goron Village (Winter)", file: "z2_11goronnosato_info.zsi" },
    { name: "Great Bay Temple", file: "z2_sea_info.zsi" },
    { name: "Great Bay Coast", file: "z2_30gyoson_info.zsi" },
    { name: "Great Bay Coast (Cutscene)", file: "z2_konpeki_ent_info.zsi" },
    { name: "Grottos", file: "kakusiana_info.zsi" },
    { name: "Gyorg's Lair", file: "z2_sea_bs_info.zsi" },
    { name: "Honey & Darling's Shop", file: "z2_bowling_info.zsi" },
    { name: "Igos du Ikana's Lair", file: "z2_ikninside_info.zsi" },
    { name: "Ikana Canyon", file: "z2_ikana_info.zsi" },
    { name: "Ikana Graveyard", file: "z2_boti_info.zsi" },
    { name: "Laundry Pool", file: "z2_alley_info.zsi" },
    { name: "Lost Woods", file: "z2_lost_woods_info.zsi" },
    { name: "Lottery Shop", file: "z2_takarakuji_info.zsi" },
    { name: "Magic Hags' Potion Shop", file: "z2_witch_shop_info.zsi" },
    { name: "Majora's Lair", file: "z2_last_bs_info.zsi" },
    { name: "Marine Research Lab", file: "z2_labo_info.zsi" },
    { name: "Mayor's Residence", file: "z2_sonchonoie_info.zsi" },
    { name: "Milk Bar", file: "z2_milk_bar_info.zsi" },
    { name: "Milk Road", file: "z2_romanymae_info.zsi" },
    { name: "Mountain Smithy", file: "z2_kajiya_info.zsi" },
    { name: "Mountain Village (Spring)", file: "z2_10yukiyamanomura2_info.zsi" },
    { name: "Mountain Village (Winter)", file: "z2_10yukiyamanomura_info.zsi" },
    { name: "Music Box House", file: "z2_musichouse_info.zsi" },
    { name: "North Clock Town", file: "z2_backtown_info.zsi" },
    { name: "Ocean Fishing Hole", file: "z2_turibori2_info.zsi" },
    { name: "Oceanside Spider House", file: "z2_kindan2_info.zsi" },
    { name: "Odolwa's Lair", file: "z2_miturin_bs_info.zsi" },
    { name: "Path to Goron Village (Spring)", file: "z2_17setugen2_info.zsi" },
    { name: "Path to Goron Village (Winter)", file: "z2_17setugen_info.zsi" },
    { name: "Path to Mountain Village", file: "z2_13hubukinomiti_info.zsi" },
    { name: "Path to Snowhead", file: "z2_14yukidamanomiti_info.zsi" },
    { name: "Pinnacle Rock", file: "z2_sinkai_info.zsi" },
    { name: "Pirates' Fortress", file: "z2_kaizoku_info.zsi" },
    { name: "Pirates' Fortress Exterior", file: "z2_toride_info.zsi" },
    { name: "Pirates' Fortress Interior", file: "z2_pirate_info.zsi" },
    { name: "Post Office", file: "z2_posthouse_info.zsi" },
    { name: "Ranch House & Barn", file: "z2_omoya_info.zsi" },
    { name: "Road to Ikana", file: "z2_ikanamae_info.zsi" },
    { name: "Road to Southern Swamp", file: "z2_24kemonomiti_info.zsi" },
    { name: "Romani Ranch", file: "z2_f01_info.zsi" },
    { name: "Sakon's Hideout", file: "z2_secom_info.zsi" },
    { name: "Secret Shrine", file: "z2_random_info.zsi" },
    { name: "Snowhead", file: "z2_12hakuginmae_info.zsi" },
    { name: "Snowhead Temple", file: "z2_hakugin_info.zsi" },
    { name: "South Clock Town", file: "z2_clocktower_info.zsi" },
    { name: "Southern Swamp (Clear)", file: "z2_20sichitai2_info.zsi" },
    { name: "Southern Swamp (Poisoned)", file: "z2_20sichitai_info.zsi" },
    { name: "Stock Pot Inn", file: "z2_yadoya_info.zsi" },
    { name: "Stone Tower", file: "z2_f40_info.zsi" },
    { name: "Stone Tower (Inverted)", file: "z2_f41_info.zsi" },
    { name: "Stone Tower Temple", file: "z2_inisie_n_info.zsi" },
    { name: "Stone Tower Temple (Inverted)", file: "z2_inisie_r_info.zsi" },
    { name: "Swamp Fishing Hole", file: "z2_turibori_info.zsi" },
    { name: "Swamp Shooting Gallery", file: "z2_syateki_mori_info.zsi" },
    { name: "Swamp Spider House", file: "z2_kinsta1_info.zsi" },
    { name: "Swordsman's School", file: "z2_doujou_info.zsi" },
    { name: "Termina Field", file: "z2_00keikoku_info.zsi" },
    { name: "Termina Field (Credits Cutscene)", file: "z2_01keikoku_info.zsi" },
    { name: "Termina Field (Credits Cutscene 2)", file: "z2_02keikoku_info.zsi" },
    { name: "Test Map 01", file: "test01_info.zsi" },
    { name: "Test Map 02", file: "test02_info.zsi" },
    { name: "The Moon", file: "z2_sougen_info.zsi" },
    { name: "The Moon - Deku Trial", file: "z2_last_deku_info.zsi" },
    { name: "The Moon - Goron Trial", file: "z2_last_goron_info.zsi" },
    { name: "The Moon - Link Trial", file: "z2_last_link_info.zsi" },
    { name: "The Moon - Zora Trial", file: "z2_last_zora_info.zsi" },
    { name: "Tourist Information", file: "z2_map_shop_info.zsi" },
    { name: "Town Shooting Gallery", file: "z2_syateki_mizu_info.zsi" },
    { name: "Trading Post", file: "z2_8itemshop_info.zsi" },
    { name: "Treasure Chest Shop", file: "z2_takaraya_info.zsi" },
    { name: "Twinmold's Lair", file: "z2_inisie_bs_info.zsi" },
    { name: "Waterfall Rapids", file: "z2_35taki_info.zsi" },
    { name: "West Clock Town", file: "z2_ichiba_info.zsi" },
    { name: "Woodfall", file: "z2_21miturinmae_info.zsi" },
    { name: "Woodfall Temple", file: "z2_miturin_info.zsi" },
    { name: "Woods of Mystery", file: "z2_26sarunomori_info.zsi" },
    { name: "Zora Cape", file: "z2_31misaki_info.zsi" },
    { name: "Zora Hall", file: "z2_33zoracity_info.zsi" },
    { name: "Zora Hall Rooms", file: "z2_bandroom_info.zsi" },
    { name: "Zora Shop", file: "z2_zolashop_info.zsi" },
    { name: "32kamejimamae", file: "z2_32kamejimamae_info.zsi" },
    { name: "meganeana", file: "z2_meganeana_info.zsi" }
];

const flat_ground_clip_y_table = new Set([
    515, 519, 523, 527, 531, 535, 539, 543, 547, 551, 555, 559, 563, 567, 571, 575, 579, 583,
    587, 591, 595, 599, 603, 607, 611, 615, 619, 623, 627, 631, 635, 639, 643, 647, 651, 655,
    659, 663, 667, 671, 675, 679, 683, 687, 691, 695, 699, 703, 707, 711, 715, 719, 723, 727,
    731, 735, 739, 743, 747, 751, 755, 759, 763, 767, 771, 775, 779, 783, 787, 791, 795, 799,
    803, 807, 811, 815, 819, 823, 827, 831, 835, 839, 843, 847, 851, 855, 859, 863, 867, 871,
    875, 879, 883, 887, 891, 895, 899, 903, 907, 911, 915, 919, 923, 927, 931, 935, 939, 943,
    947, 951, 955, 959, 963, 967, 971, 975, 979, 983, 987, 991, 995, 999, 1003, 1007, 1011,
    1015, 1019, 1023, 1030, 1038, 1046, 1054, 1062, 1070, 1078, 1086, 1094, 1102, 1110, 1118,
    1126, 1134, 1142, 1150, 1158, 1166, 1174, 1182, 1190, 1198, 1206, 1214, 1222, 1230, 1238,
    1246, 1254, 1262, 1270, 1278, 1286, 1294, 1302, 1310, 1318, 1326, 1334, 1342, 1350, 1358,
    1366, 1374, 1382, 1390, 1398, 1406, 1414, 1422, 1430, 1438, 1446, 1454, 1462, 1470, 1478,
    1486, 1494, 1502, 1510, 1518, 1526, 1534, 1542, 1550, 1558, 1566, 1574, 1582, 1590, 1598,
    1606, 1614, 1622, 1630, 1638, 1646, 1654, 1662, 1670, 1678, 1686, 1694, 1702, 1710, 1718,
    1726, 1734, 1742, 1750, 1758, 1766, 1774, 1782, 1790, 1798, 1806, 1814, 1822, 1830, 1838,
    1846, 1854, 1862, 1870, 1878, 1886, 1894, 1902, 1910, 1918, 1926, 1934, 1942, 1950, 1958,
    1966, 1974, 1982, 1990, 1998, 2006, 2014, 2022, 2030, 2038, 2046, 2060, 2076, 2092, 2108,
    2124, 2140, 2156, 2172, 2188, 2204, 2220, 2236, 2252, 2268, 2284, 2300, 2316, 2332, 2348,
    2364, 2380, 2396, 2412, 2428, 2444, 2460, 2476, 2492, 2508, 2524, 2540, 2556, 2572, 2588,
    2604, 2620, 2636, 2652, 2668, 2684, 2700, 2716, 2732, 2748, 2764, 2780, 2796, 2812, 2828,
    2844, 2860, 2876, 2892, 2908, 2924, 2940, 2956, 2972, 2988, 3004, 3020, 3036, 3052, 3068,
    3084, 3100, 3116, 3132, 3148, 3164, 3180, 3196, 3212, 3228, 3244, 3260, 3276, 3292, 3308,
    3324, 3340, 3356, 3372, 3388, 3404, 3420, 3436, 3452, 3468, 3484, 3500, 3516, 3532, 3548,
    3564, 3580, 3596, 3612, 3628, 3644, 3660, 3676, 3692, 3708, 3724, 3740, 3756, 3772, 3788,
    3804, 3820, 3836, 3852, 3868, 3884, 3900, 3916, 3932, 3948, 3964, 3980, 3996, 4012, 4028,
    4044, 4060, 4076, 4092, 4120, 4152, 4184, 4216, 4248, 4280, 4312, 4344, 4376, 4408, 4440,
    4472, 4504, 4536, 4568, 4600, 4632, 4664, 4696, 4728, 4760, 4792, 4824, 4856, 4888, 4920,
    4952, 4984
]);
