// Each BK map lives in models/BK/<dir>/ as extracted by banjo-kazooie/tools/extract_maps.py:
//   opa.model.bin  - opaque level geometry (BKModelBin)          [asset id in "opa"]
//   xlu.model.bin  - translucent level geometry, if any (BKModelBin) [asset id in "xlu", "" if none]
//   setup.bin      - cube / camera / lighting stream
const BK_Maps = [
    { name: "SM_SPIRAL_MOUNTAIN", sceneID: "1", dir: "01_SM_SPIRAL_MOUNTAIN", opa: "14CF", xlu: "14D0" },
    { name: "SM_BANJOS_HOUSE", sceneID: "8C", dir: "8C_SM_BANJOS_HOUSE", opa: "14A2", xlu: "14A4" },
    { name: "MM_MUMBOS_MOUNTAIN", sceneID: "2", dir: "02_MM_MUMBOS_MOUNTAIN", opa: "14AA", xlu: "14AB" },
    { name: "MM_TICKERS_TOWER", sceneID: "C", dir: "0C_MM_TICKERS_TOWER", opa: "14AC", xlu: "14AD" },
    { name: "MM_MUMBOS_SKULL", sceneID: "E", dir: "0E_MM_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "TTC_TREASURE_TROVE_COVE", sceneID: "7", dir: "07_TTC_TREASURE_TROVE_COVE", opa: "146B", xlu: "146C" },
    { name: "TTC_BLUBBERS_SHIP", sceneID: "5", dir: "05_TTC_BLUBBERS_SHIP", opa: "146F", xlu: "1470" },
    { name: "TTC_NIPPERS_SHELL", sceneID: "6", dir: "06_TTC_NIPPERS_SHELL", opa: "146D", xlu: "146E" },
    { name: "TTC_SHARKFOOD_ISLAND", sceneID: "8F", dir: "8F_TTC_SHARKFOOD_ISLAND", opa: "1473", xlu: "" },
    { name: "TTC_SANDCASTLE", sceneID: "A", dir: "0A_TTC_SANDCASTLE", opa: "1471", xlu: "1472" },
    { name: "CC_CLANKERS_CAVERN", sceneID: "B", dir: "0B_CC_CLANKERS_CAVERN", opa: "14ED", xlu: "14EE" },
    { name: "CC_WITCH_SWITCH_ROOM", sceneID: "21", dir: "21_CC_WITCH_SWITCH_ROOM", opa: "14EF", xlu: "" },
    { name: "CC_INSIDE_CLANKER", sceneID: "22", dir: "22_CC_INSIDE_CLANKER", opa: "14F0", xlu: "14F1" },
    { name: "CC_GOLDFEATHER_ROOM", sceneID: "23", dir: "23_CC_GOLDFEATHER_ROOM", opa: "14F2", xlu: "" },
    { name: "BGS_BUBBLEGLOOP_SWAMP", sceneID: "D", dir: "0D_BGS_BUBBLEGLOOP_SWAMP", opa: "14D1", xlu: "14D2" },
    { name: "BGS_MR_VILE", sceneID: "10", dir: "10_BGS_MR_VILE", opa: "14D3", xlu: "" },
    { name: "BGS_TIPTUP", sceneID: "11", dir: "11_BGS_TIPTUP", opa: "14D4", xlu: "14D5" },
    { name: "BGS_MUMBOS_SKULL", sceneID: "47", dir: "47_BGS_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "GV_GOBIS_VALLEY", sceneID: "12", dir: "12_GV_GOBIS_VALLEY", opa: "1474", xlu: "1475" },
    { name: "GV_SNS_CHAMBER", sceneID: "92", dir: "92_GV_SNS_CHAMBER", opa: "147E", xlu: "" },
    { name: "GV_MEMORY_GAME", sceneID: "13", dir: "13_GV_MEMORY_GAME", opa: "1476", xlu: "" },
    { name: "GV_SANDYBUTTS_MAZE", sceneID: "14", dir: "14_GV_SANDYBUTTS_MAZE", opa: "1478", xlu: "1479" },
    { name: "GV_WATER_PYRAMID", sceneID: "15", dir: "15_GV_WATER_PYRAMID", opa: "147A", xlu: "147B" },
    { name: "GV_RUBEES_CHAMBER", sceneID: "16", dir: "16_GV_RUBEES_CHAMBER", opa: "147C", xlu: "" },
    { name: "GV_INSIDE_JINXY", sceneID: "1A", dir: "1A_GV_INSIDE_JINXY", opa: "147D", xlu: "" },
    { name: "FP_FREEZEEZY_PEAK", sceneID: "27", dir: "27_FP_FREEZEEZY_PEAK", opa: "14C8", xlu: "14C9" },
    { name: "FP_BOGGYS_IGLOO", sceneID: "41", dir: "41_FP_BOGGYS_IGLOO", opa: "14CA", xlu: "14CE" },
    { name: "FP_WOZZAS_CAVE", sceneID: "7F", dir: "7F_FP_WOZZAS_CAVE", opa: "14CC", xlu: "14CD" },
    { name: "FP_MUMBOS_SKULL", sceneID: "48", dir: "48_FP_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "FP_CHRISTMAS_TREE", sceneID: "53", dir: "53_FP_CHRISTMAS_TREE", opa: "14CB", xlu: "" },
    { name: "MMM_MAD_MONSTER_MANSION", sceneID: "1B", dir: "1B_MMM_MAD_MONSTER_MANSION", opa: "147F", xlu: "1480" },
    { name: "MMM_CHURCH", sceneID: "1C", dir: "1C_MMM_CHURCH", opa: "1486", xlu: "1487" },
    { name: "MMM_CELLAR", sceneID: "1D", dir: "1D_MMM_CELLAR", opa: "1482", xlu: "149B" },
    { name: "MMM_TUMBLARS_SHED", sceneID: "24", dir: "24_MMM_TUMBLARS_SHED", opa: "1488", xlu: "" },
    { name: "MMM_WELL", sceneID: "25", dir: "25_MMM_WELL", opa: "1495", xlu: "1496" },
    { name: "MMM_NAPPERS_ROOM", sceneID: "26", dir: "26_MMM_NAPPERS_ROOM", opa: "1485", xlu: "149A" },
    { name: "MMM_EGG_ROOM", sceneID: "28", dir: "28_MMM_EGG_ROOM", opa: "1489", xlu: "148A" },
    { name: "MMM_NOTE_ROOM", sceneID: "29", dir: "29_MMM_NOTE_ROOM", opa: "148B", xlu: "148C" },
    { name: "MMM_FEATHER_ROOM", sceneID: "2A", dir: "2A_MMM_FEATHER_ROOM", opa: "148D", xlu: "148E" },
    { name: "MMM_SECRET_CHURCH_ROOM", sceneID: "2B", dir: "2B_MMM_SECRET_CHURCH_ROOM", opa: "1483", xlu: "1484" },
    { name: "MMM_BATHROOM", sceneID: "2C", dir: "2C_MMM_BATHROOM", opa: "148F", xlu: "1490" },
    { name: "MMM_BEDROOM", sceneID: "2D", dir: "2D_MMM_BEDROOM", opa: "1491", xlu: "1492" },
    { name: "MMM_HONEYCOMB_ROOM", sceneID: "2E", dir: "2E_MMM_HONEYCOMB_ROOM", opa: "1493", xlu: "1494" },
    { name: "MMM_WATERDRAIN_BARREL", sceneID: "2F", dir: "2F_MMM_WATERDRAIN_BARREL", opa: "1481", xlu: "1497" },
    { name: "MMM_MUMBOS_SKULL", sceneID: "30", dir: "30_MMM_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "MMM_INSIDE_LOGGO", sceneID: "8D", dir: "8D_MMM_INSIDE_LOGGO", opa: "1498", xlu: "1499" },
    { name: "RBB_RUSTY_BUCKET_BAY", sceneID: "31", dir: "31_RBB_RUSTY_BUCKET_BAY", opa: "14B0", xlu: "14B1" },
    { name: "RBB_ANCHOR_ROOM", sceneID: "8B", dir: "8B_RBB_ANCHOR_ROOM", opa: "14C5", xlu: "14C6" },
    { name: "RBB_ENGINE_ROOM", sceneID: "34", dir: "34_RBB_ENGINE_ROOM", opa: "14B2", xlu: "14B3" },
    { name: "RBB_WAREHOUSE", sceneID: "35", dir: "35_RBB_WAREHOUSE", opa: "14B4", xlu: "14B5" },
    { name: "RBB_BOATHOUSE", sceneID: "36", dir: "36_RBB_BOATHOUSE", opa: "14B6", xlu: "14B7" },
    { name: "RBB_CONTAINER_1", sceneID: "37", dir: "37_RBB_CONTAINER_1", opa: "14B8", xlu: "" },
    { name: "RBB_CONTAINER_2", sceneID: "3E", dir: "3E_RBB_CONTAINER_2", opa: "14B9", xlu: "" },
    { name: "RBB_CONTAINER_3", sceneID: "38", dir: "38_RBB_CONTAINER_3", opa: "14BA", xlu: "" },
    { name: "RBB_CREW_CABIN", sceneID: "39", dir: "39_RBB_CREW_CABIN", opa: "14BD", xlu: "" },
    { name: "RBB_BOSS_BOOM_BOX", sceneID: "3A", dir: "3A_RBB_BOSS_BOOM_BOX", opa: "14BE", xlu: "14BF" },
    { name: "RBB_STORAGE_ROOM", sceneID: "3B", dir: "3B_RBB_STORAGE_ROOM", opa: "14C1", xlu: "14C2" },
    { name: "RBB_KITCHEN", sceneID: "3C", dir: "3C_RBB_KITCHEN", opa: "14C3", xlu: "14C4" },
    { name: "RBB_NAVIGATION_ROOM", sceneID: "3D", dir: "3D_RBB_NAVIGATION_ROOM", opa: "14C0", xlu: "14C7" },
    { name: "RBB_CAPTAINS_CABIN", sceneID: "3F", dir: "3F_RBB_CAPTAINS_CABIN", opa: "14BB", xlu: "14BC" },
    { name: "CCW_HUB", sceneID: "40", dir: "40_CCW_HUB", opa: "14D8", xlu: "14E3" },
    { name: "CCW_SPRING", sceneID: "43", dir: "43_CCW_SPRING", opa: "14D9", xlu: "14E4" },
    { name: "CCW_SUMMER", sceneID: "44", dir: "44_CCW_SUMMER", opa: "14DA", xlu: "14E5" },
    { name: "CCW_AUTUMN", sceneID: "45", dir: "45_CCW_AUTUMN", opa: "14DB", xlu: "14E6" },
    { name: "CCW_WINTER", sceneID: "46", dir: "46_CCW_WINTER", opa: "14DC", xlu: "14E7" },
    { name: "CCW_SPRING_MUMBOS_SKULL", sceneID: "4A", dir: "4A_CCW_SPRING_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_SUMMER_MUMBOS_SKULL", sceneID: "4B", dir: "4B_CCW_SUMMER_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_AUTUMN_MUMBOS_SKULL", sceneID: "4C", dir: "4C_CCW_AUTUMN_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_WINTER_MUMBOS_SKULL", sceneID: "4D", dir: "4D_CCW_WINTER_MUMBOS_SKULL", opa: "14AE", xlu: "" },
    { name: "CCW_SUMMER_ZUBBA_HIVE", sceneID: "5A", dir: "5A_CCW_SUMMER_ZUBBA_HIVE", opa: "14DD", xlu: "" },
    { name: "CCW_SPRING_ZUBBA_HIVE", sceneID: "5B", dir: "5B_CCW_SPRING_ZUBBA_HIVE", opa: "14DD", xlu: "" },
    { name: "CCW_AUTUMN_ZUBBA_HIVE", sceneID: "5C", dir: "5C_CCW_AUTUMN_ZUBBA_HIVE", opa: "14DD", xlu: "" },
    { name: "CCW_SPRING_NABNUTS_HOUSE", sceneID: "5E", dir: "5E_CCW_SPRING_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_SUMMER_NABNUTS_HOUSE", sceneID: "5F", dir: "5F_CCW_SUMMER_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_AUTUMN_NABNUTS_HOUSE", sceneID: "60", dir: "60_CCW_AUTUMN_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_WINTER_NABNUTS_HOUSE", sceneID: "61", dir: "61_CCW_WINTER_NABNUTS_HOUSE", opa: "14DE", xlu: "" },
    { name: "CCW_WINTER_HONEYCOMB_ROOM", sceneID: "62", dir: "62_CCW_WINTER_HONEYCOMB_ROOM", opa: "14E0", xlu: "" },
    { name: "CCW_AUTUMN_NABNUTS_WATER_SUPPLY", sceneID: "63", dir: "63_CCW_AUTUMN_NABNUTS_WATER_SUPPLY", opa: "14E1", xlu: "14E2" },
    { name: "CCW_WINTER_NABNUTS_WATER_SUPPLY", sceneID: "64", dir: "64_CCW_WINTER_NABNUTS_WATER_SUPPLY", opa: "14E1", xlu: "14E2" },
    { name: "CCW_SPRING_WHIPCRACK_ROOM", sceneID: "65", dir: "65_CCW_SPRING_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "CCW_SUMMER_WHIPCRACK_ROOM", sceneID: "66", dir: "66_CCW_SUMMER_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "CCW_AUTUMN_WHIPCRACK_ROOM", sceneID: "67", dir: "67_CCW_AUTUMN_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "CCW_WINTER_WHIPCRACK_ROOM", sceneID: "68", dir: "68_CCW_WINTER_WHIPCRACK_ROOM", opa: "14DF", xlu: "" },
    { name: "GL_MM_LOBBY", sceneID: "69", dir: "69_GL_MM_LOBBY", opa: "14F3", xlu: "150B" },
    { name: "GL_TTC_AND_CC_PUZZLE", sceneID: "6A", dir: "6A_GL_TTC_AND_CC_PUZZLE", opa: "14F4", xlu: "150C" },
    { name: "GL_180_NOTE_DOOR", sceneID: "6B", dir: "6B_GL_180_NOTE_DOOR", opa: "14F5", xlu: "1510" },
    { name: "GL_RED_CAULDRON_ROOM", sceneID: "6C", dir: "6C_GL_RED_CAULDRON_ROOM", opa: "14F6", xlu: "150D" },
    { name: "GL_TTC_LOBBY", sceneID: "6D", dir: "6D_GL_TTC_LOBBY", opa: "14F7", xlu: "1512" },
    { name: "GL_GV_LOBBY", sceneID: "6E", dir: "6E_GL_GV_LOBBY", opa: "14F8", xlu: "14A8" },
    { name: "GL_FP_LOBBY", sceneID: "6F", dir: "6F_GL_FP_LOBBY", opa: "14F9", xlu: "14FA" },
    { name: "GL_GV_PUZZLE", sceneID: "74", dir: "74_GL_GV_PUZZLE", opa: "14FD", xlu: "" },
    { name: "GL_CC_LOBBY", sceneID: "70", dir: "70_GL_CC_LOBBY", opa: "14FB", xlu: "1507" },
    { name: "GL_MMM_LOBBY", sceneID: "75", dir: "75_GL_MMM_LOBBY", opa: "14FE", xlu: "" },
    { name: "GL_CRYPT", sceneID: "7A", dir: "7A_GL_CRYPT", opa: "14FF", xlu: "" },
    { name: "GL_STATUE_ROOM", sceneID: "71", dir: "71_GL_STATUE_ROOM", opa: "1500", xlu: "150E" },
    { name: "GL_BGS_LOBBY", sceneID: "72", dir: "72_GL_BGS_LOBBY", opa: "1501", xlu: "1511" },
    { name: "GL_640_NOTE_DOOR", sceneID: "76", dir: "76_GL_640_NOTE_DOOR", opa: "1502", xlu: "1508" },
    { name: "GL_RBB_LOBBY", sceneID: "77", dir: "77_GL_RBB_LOBBY", opa: "1503", xlu: "1509" },
    { name: "GL_RBB_AND_MMM_PUZZLE", sceneID: "78", dir: "78_GL_RBB_AND_MMM_PUZZLE", opa: "1504", xlu: "150A" },
    { name: "GL_CCW_LOBBY", sceneID: "79", dir: "79_GL_CCW_LOBBY", opa: "1505", xlu: "" },
    { name: "GL_FF_ENTRANCE", sceneID: "80", dir: "80_GL_FF_ENTRANCE", opa: "1506", xlu: "1514" },
    { name: "GL_FURNACE_FUN", sceneID: "8E", dir: "8E_GL_FURNACE_FUN", opa: "14E8", xlu: "" },
    { name: "GL_DINGPOT", sceneID: "93", dir: "93_GL_DINGPOT", opa: "150F", xlu: "1513" },
    { name: "GL_BATTLEMENTS", sceneID: "90", dir: "90_GL_BATTLEMENTS", opa: "14FC", xlu: "1515" },
    { name: "CS_START_NINTENDO", sceneID: "1E", dir: "1E_CS_START_NINTENDO", opa: "149D", xlu: "14A1" },
    { name: "CS_START_RAREWARE", sceneID: "1F", dir: "1F_CS_START_RAREWARE", opa: "149E", xlu: "14A0" },
    { name: "CS_INTRO_GL_DINGPOT_1", sceneID: "7B", dir: "7B_CS_INTRO_GL_DINGPOT_1", opa: "150F", xlu: "" },
    { name: "CS_INTRO_BANJOS_HOUSE_1", sceneID: "7C", dir: "7C_CS_INTRO_BANJOS_HOUSE_1", opa: "14A2", xlu: "" },
    { name: "CS_SPIRAL_MOUNTAIN_1", sceneID: "7D", dir: "7D_CS_SPIRAL_MOUNTAIN_1", opa: "14CF", xlu: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_2", sceneID: "7E", dir: "7E_CS_SPIRAL_MOUNTAIN_2", opa: "14CF", xlu: "14D0" },
    { name: "CS_INTRO_GL_DINGPOT_2", sceneID: "81", dir: "81_CS_INTRO_GL_DINGPOT_2", opa: "150F", xlu: "" },
    { name: "CS_ENTERING_GL_MACHINE_ROOM", sceneID: "82", dir: "82_CS_ENTERING_GL_MACHINE_ROOM", opa: "150F", xlu: "" },
    { name: "CS_GAME_OVER_MACHINE_ROOM", sceneID: "83", dir: "83_CS_GAME_OVER_MACHINE_ROOM", opa: "150F", xlu: "" },
    { name: "CS_UNUSED_MACHINE_ROOM", sceneID: "84", dir: "84_CS_UNUSED_MACHINE_ROOM", opa: "150F", xlu: "" },
    { name: "CS_SPIRAL_MOUNTAIN_3", sceneID: "85", dir: "85_CS_SPIRAL_MOUNTAIN_3", opa: "14CF", xlu: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_4", sceneID: "86", dir: "86_CS_SPIRAL_MOUNTAIN_4", opa: "14CF", xlu: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_5", sceneID: "87", dir: "87_CS_SPIRAL_MOUNTAIN_5", opa: "14A6", xlu: "" },
    { name: "CS_SPIRAL_MOUNTAIN_6", sceneID: "88", dir: "88_CS_SPIRAL_MOUNTAIN_6", opa: "14CF", xlu: "14D0" },
    { name: "CS_INTRO_SPIRAL_7", sceneID: "94", dir: "94_CS_INTRO_SPIRAL_7", opa: "14CF", xlu: "14D0" },
    { name: "CS_END_SPIRAL_MOUNTAIN_1", sceneID: "98", dir: "98_CS_END_SPIRAL_MOUNTAIN_1", opa: "149F", xlu: "14A3" },
    { name: "CS_END_SPIRAL_MOUNTAIN_2", sceneID: "99", dir: "99_CS_END_SPIRAL_MOUNTAIN_2", opa: "149F", xlu: "14A3" },
    { name: "CS_END_ALL_100", sceneID: "95", dir: "95_CS_END_ALL_100", opa: "14A9", xlu: "14A5" },
    { name: "CS_END_NOT_100", sceneID: "20", dir: "20_CS_END_NOT_100", opa: "14A9", xlu: "14A5" },
    { name: "CS_INTRO_BANJOS_HOUSE_2", sceneID: "89", dir: "89_CS_INTRO_BANJOS_HOUSE_2", opa: "14A2", xlu: "14A4" },
    { name: "CS_INTRO_BANJOS_HOUSE_3", sceneID: "8A", dir: "8A_CS_INTRO_BANJOS_HOUSE_3", opa: "14A2", xlu: "14A4" },
    { name: "CS_END_BEACH_1", sceneID: "96", dir: "96_CS_END_BEACH_1", opa: "14A9", xlu: "14A5" },
    { name: "CS_END_BEACH_2", sceneID: "97", dir: "97_CS_END_BEACH_2", opa: "14A9", xlu: "14A5" },
    { name: "FILE_SELECT", sceneID: "91", dir: "91_FILE_SELECT", opa: "14A2", xlu: "14A4" },
];

// Each BT map lives in models/BT/<dir>/ as extracted by banjo-tooie/tools/extract_maps.py:
//   opa.model.bin  - model A, opaque level geometry (BKModelBin)      [asset id in "opa", "" if none]
//   xlu.model.bin  - model B, translucent level geometry, if any     [asset id in "xlu", "" if none]
//   setup.bin      - decrypted + decompressed map setup file
//   sect<N>.{opa,xlu}.model.bin - Jolly Roger's Lagoon terrain sectors, drawn translated by
//                                 their offset ["sectors": [[opa, xlu, [x, y, z]], ...]]
const BT_Maps = [
    { name: "SM_SPIRAL_MOUNTAIN", sceneID: "AF", dir: "0AF_SM_SPIRAL_MOUNTAIN", opa: "1CF9", xlu: "1CFA" },
    { name: "SM_BEHIND_THE_WATERFALL", sceneID: "AE", dir: "0AE_SM_BEHIND_THE_WATERFALL", opa: "1CFE", xlu: "1CFF" },
    { name: "SM_DIGGER_TUNNEL", sceneID: "141", dir: "141_SM_DIGGER_TUNNEL", opa: "1D04", xlu: "" },
    { name: "SM_BANJOS_HOUSE", sceneID: "173", dir: "173_SM_BANJOS_HOUSE", opa: "1D08", xlu: "" },
    { name: "GL_ENTRANCE", sceneID: "AD", dir: "0AD_GL_ENTRANCE", opa: "1CFD", xlu: "" },
    { name: "JV_JINJO_VILLAGE", sceneID: "142", dir: "142_JV_JINJO_VILLAGE", opa: "1DC1", xlu: "" },
    { name: "JV_BOTTLES_HOUSE", sceneID: "143", dir: "143_JV_BOTTLES_HOUSE", opa: "1DD0", xlu: "1DD3" },
    { name: "JV_JINGALING_THRONE_ROOM", sceneID: "144", dir: "144_JV_JINGALING_THRONE_ROOM", opa: "1DD1", xlu: "" },
    { name: "JV_GREEN_JINJO_HOUSE", sceneID: "145", dir: "145_JV_GREEN_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_BLACK_JINJO_HOUSE", sceneID: "146", dir: "146_JV_BLACK_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_YELLOW_JINJO_HOUSE", sceneID: "147", dir: "147_JV_YELLOW_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_BLUE_JINJO_HOUSE", sceneID: "148", dir: "148_JV_BLUE_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_UNUSED_JINJO_HOUSE", sceneID: "149", dir: "149_JV_UNUSED_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_BROWN_JINJO_HOUSE", sceneID: "14A", dir: "14A_JV_BROWN_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_ORANGE_JINJO_HOUSE", sceneID: "14B", dir: "14B_JV_ORANGE_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_PURPLE_JINJO_HOUSE", sceneID: "14C", dir: "14C_JV_PURPLE_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_RED_JINJO_HOUSE", sceneID: "14D", dir: "14D_JV_RED_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_WHITE_JINJO_HOUSE", sceneID: "14E", dir: "14E_JV_WHITE_JINJO_HOUSE", opa: "1DCF", xlu: "" },
    { name: "JV_ZOMBIE_THRONE", sceneID: "19B", dir: "19B_JV_ZOMBIE_THRONE", opa: "1DD2", xlu: "" },
    { name: "IOH_WOODED_HOLLOW", sceneID: "14F", dir: "14F_IOH_WOODED_HOLLOW", opa: "1DC2", xlu: "" },
    { name: "IOH_HEGGYS_EGG_", sceneID: "150", dir: "150_IOH_HEGGYS_EGG_", opa: "1DC7", xlu: "" },
    { name: "IOH_JIGGYWIGGY_TEMPLE", sceneID: "151", dir: "151_IOH_JIGGYWIGGY_TEMPLE", opa: "1DC3", xlu: "" },
    { name: "IOH_PLATEAU", sceneID: "152", dir: "152_IOH_PLATEAU", opa: "1DC4", xlu: "" },
    { name: "IOH_HONEY_B_HIVE", sceneID: "153", dir: "153_IOH_HONEY_B_HIVE", opa: "1DCE", xlu: "" },
    { name: "IOH_PINE_GROVE", sceneID: "154", dir: "154_IOH_PINE_GROVE", opa: "1DC5", xlu: "1DC6" },
    { name: "IOH_CLIFF_TOP", sceneID: "155", dir: "155_IOH_CLIFF_TOP", opa: "1DC8", xlu: "" },
    { name: "IOH_MUMBO", sceneID: "156", dir: "156_IOH_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "IOH_WUMBA", sceneID: "157", dir: "157_IOH_WUMBA", opa: "1D00", xlu: "1D05" },
    { name: "IOH_WASTELAND", sceneID: "15A", dir: "15A_IOH_WASTELAND", opa: "1DC9", xlu: "" },
    { name: "IOH_ANOTHER_DIGGER_TUNNEL", sceneID: "15B", dir: "15B_IOH_ANOTHER_DIGGER_TUNNEL", opa: "1DCC", xlu: "1DCD" },
    { name: "IOH_QUAGMIRE", sceneID: "15C", dir: "15C_IOH_QUAGMIRE", opa: "1DCA", xlu: "" },
    { name: "MT_MAYAHEM_TEMPLE", sceneID: "B8", dir: "0B8_MT_MAYAHEM_TEMPLE", opa: "1D0A", xlu: "1D0B" },
    { name: "MT_WUMBAS", sceneID: "B6", dir: "0B6_MT_WUMBAS", opa: "1D00", xlu: "1D05" },
    { name: "MT_MUMBO", sceneID: "B7", dir: "0B7_MT_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "MT_PRISON_COMPOUND", sceneID: "B9", dir: "0B9_MT_PRISON_COMPOUND", opa: "1D0C", xlu: "1D0D" },
    { name: "MT_COLUMNS_VAULT", sceneID: "BA", dir: "0BA_MT_COLUMNS_VAULT", opa: "1D0E", xlu: "" },
    { name: "MT_KICKBALL_STADIUM", sceneID: "BB", dir: "0BB_MT_KICKBALL_STADIUM", opa: "1D0F", xlu: "" },
    { name: "MT_CODE_CHAMBER", sceneID: "BC", dir: "0BC_MT_CODE_CHAMBER", opa: "1D10", xlu: "" },
    { name: "MT_JADE_SNAKE_GROVE", sceneID: "C4", dir: "0C4_MT_JADE_SNAKE_GROVE", opa: "1D11", xlu: "1D12" },
    { name: "MT_TREASURE_CHAMBER", sceneID: "C5", dir: "0C5_MT_TREASURE_CHAMBER", opa: "1D13", xlu: "" },
    { name: "MT_KICKBALL_1", sceneID: "C6", dir: "0C6_MT_KICKBALL_1", opa: "1D14", xlu: "" },
    { name: "MT_KICKBALL_2", sceneID: "C8", dir: "0C8_MT_KICKBALL_2", opa: "1D14", xlu: "" },
    { name: "MT_KICKBALL_3", sceneID: "C9", dir: "0C9_MT_KICKBALL_3", opa: "1D14", xlu: "" },
    { name: "MT_STILL", sceneID: "167", dir: "167_MT_STILL", opa: "1D0A", xlu: "1D0B" },
    { name: "MT_SLIGHTLY_SACRED_CHAMBER", sceneID: "177", dir: "177_MT_SLIGHTLY_SACRED_CHAMBER", opa: "1D15", xlu: "" },
    { name: "MT_INSIDE_TARGITZAN_TEMPLE", sceneID: "178", dir: "178_MT_INSIDE_TARGITZAN_TEMPLE", opa: "1D16", xlu: "" },
    { name: "MT_TARGITZAN_TEMPLE_LOBBY", sceneID: "179", dir: "179_MT_TARGITZAN_TEMPLE_LOBBY", opa: "1D17", xlu: "" },
    { name: "MT_TARGITZAN_BOSS", sceneID: "17A", dir: "17A_MT_TARGITZAN_BOSS", opa: "1D15", xlu: "" },
    { name: "GGM_GLITTER_GULCH_MINE", sceneID: "C7", dir: "0C7_GGM_GLITTER_GULCH_MINE", opa: "1D25", xlu: "1D36" },
    { name: "GGM_FUEL_DEPOT", sceneID: "CA", dir: "0CA_GGM_FUEL_DEPOT", opa: "1D19", xlu: "1D32" },
    { name: "GGM_CRUSHING_SHED", sceneID: "CB", dir: "0CB_GGM_CRUSHING_SHED", opa: "1D1A", xlu: "1D28" },
    { name: "GGM_FLOODED_CAVES", sceneID: "CC", dir: "0CC_GGM_FLOODED_CAVES", opa: "1D1B", xlu: "1D2D" },
    { name: "GGM_WATER_STORAGE", sceneID: "CD", dir: "0CD_GGM_WATER_STORAGE", opa: "1D1C", xlu: "1D30" },
    { name: "GGM_WATERFALL_CAVERN", sceneID: "CE", dir: "0CE_GGM_WATERFALL_CAVERN", opa: "1D1D", xlu: "1D26" },
    { name: "GGM_POWER_HUT_BASEMENT", sceneID: "CF", dir: "0CF_GGM_POWER_HUT_BASEMENT", opa: "1D1E", xlu: "1D2B" },
    { name: "GGM_INSIDE_CHUFFY_BOILER", sceneID: "D1", dir: "0D1_GGM_INSIDE_CHUFFY_BOILER", opa: "1D20", xlu: "" },
    { name: "GGM_GLOOMY_CAVERNS", sceneID: "D2", dir: "0D2_GGM_GLOOMY_CAVERNS", opa: "1D21", xlu: "1D2A" },
    { name: "GGM_GENERATOR_CAVERNS", sceneID: "D3", dir: "0D3_GGM_GENERATOR_CAVERNS", opa: "1D22", xlu: "1D2E" },
    { name: "GGM_POWER_HUT", sceneID: "D4", dir: "0D4_GGM_POWER_HUT", opa: "1D23", xlu: "1D29" },
    { name: "GGM_TRAIN_STATION", sceneID: "D7", dir: "0D7_GGM_TRAIN_STATION", opa: "1D24", xlu: "" },
    { name: "GGM_PROSPECTORS_HUT", sceneID: "D8", dir: "0D8_GGM_PROSPECTORS_HUT", opa: "1D2C", xlu: "1D37" },
    { name: "GGM_MUMBO", sceneID: "D9", dir: "0D9_GGM_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "GGM_TOXIC_GAS_CAVE", sceneID: "DA", dir: "0DA_GGM_TOXIC_GAS_CAVE", opa: "1D2F", xlu: "" },
    { name: "GGM_CANARY_CAVE", sceneID: "DB", dir: "0DB_GGM_CANARY_CAVE", opa: "1D27", xlu: "1D31" },
    { name: "GGM_ORDNANCE_STORAGE", sceneID: "DC", dir: "0DC_GGM_ORDNANCE_STORAGE", opa: "1D34", xlu: "" },
    { name: "GGM_WUMBA", sceneID: "E9", dir: "0E9_GGM_WUMBA", opa: "1D00", xlu: "1D05" },
    { name: "GGM_WATER_SUPPLY_PIPE", sceneID: "126", dir: "126_GGM_WATER_SUPPLY_PIPE", opa: "1D5E", xlu: "" },
    { name: "GGM_ORDNANCE_STORAGE_ENTRANCE", sceneID: "163", dir: "163_GGM_ORDNANCE_STORAGE_ENTRANCE", opa: "1D35", xlu: "" },
    { name: "GGM_RACE_1", sceneID: "16F", dir: "16F_GGM_RACE_1", opa: "1D25", xlu: "1D36" },
    { name: "GGM_RACE_2", sceneID: "170", dir: "170_GGM_RACE_2", opa: "1D25", xlu: "1D36" },
    { name: "WW_WITCHYWORLD", sceneID: "D6", dir: "0D6_WW_WITCHYWORLD", opa: "1D38", xlu: "1D44" },
    { name: "WW_WUMBA", sceneID: "D5", dir: "0D5_WW_WUMBA", opa: "1D00", xlu: "1D05" },
    { name: "WW_DODGEM_LOBBY", sceneID: "DD", dir: "0DD_WW_DODGEM_LOBBY", opa: "1D41", xlu: "" },
    { name: "WW_DODGEM_1V1", sceneID: "DE", dir: "0DE_WW_DODGEM_1V1", opa: "1D42", xlu: "" },
    { name: "WW_DODGEM_1V2", sceneID: "DF", dir: "0DF_WW_DODGEM_1V2", opa: "1D42", xlu: "" },
    { name: "WW_DODGEM_1V3", sceneID: "E0", dir: "0E0_WW_DODGEM_1V3", opa: "1D42", xlu: "" },
    { name: "WW_CRAZY_CASTLE_STOCKADE", sceneID: "E1", dir: "0E1_WW_CRAZY_CASTLE_STOCKADE", opa: "1D39", xlu: "" },
    { name: "WW_CRAZY_CASTLE_LOBBY", sceneID: "E2", dir: "0E2_WW_CRAZY_CASTLE_LOBBY", opa: "1D3B", xlu: "" },
    { name: "WW_CASTLE_PUMP_ROOM", sceneID: "E3", dir: "0E3_WW_CASTLE_PUMP_ROOM", opa: "1D3A", xlu: "" },
    { name: "WW_BALLOON_BURST", sceneID: "E4", dir: "0E4_WW_BALLOON_BURST", opa: "1D46", xlu: "" },
    { name: "WW_HOOP_HURRY", sceneID: "E5", dir: "0E5_WW_HOOP_HURRY", opa: "1D46", xlu: "" },
    { name: "WW_STAR_SPINNER", sceneID: "E6", dir: "0E6_WW_STAR_SPINNER", opa: "1D40", xlu: "1D45" },
    { name: "WW_INFERNO", sceneID: "E7", dir: "0E7_WW_INFERNO", opa: "1D3C", xlu: "" },
    { name: "WW_CAVE_OF_HORRORS", sceneID: "EA", dir: "0EA_WW_CAVE_OF_HORRORS", opa: "1D3D", xlu: "" },
    { name: "WW_HAUNTED_CAVERN", sceneID: "EB", dir: "0EB_WW_HAUNTED_CAVERN", opa: "1D3E", xlu: "" },
    { name: "WW_TRAIN_STATION", sceneID: "EC", dir: "0EC_WW_TRAIN_STATION", opa: "1D3F", xlu: "1D4A" },
    { name: "WW_INSIDE_BIG_TOP", sceneID: "F9", dir: "0F9_WW_INSIDE_BIG_TOP", opa: "1D43", xlu: "" },
    { name: "WW_SAUCER_OF_PERIL", sceneID: "124", dir: "124_WW_SAUCER_OF_PERIL", opa: "1D38", xlu: "1D44" },
    { name: "WW_CRAZY_CASTLE_SOP", sceneID: "13B", dir: "13B_WW_CRAZY_CASTLE_SOP", opa: "1D39", xlu: "" },
    { name: "WW_STAR_SPINNER_SOP", sceneID: "13C", dir: "13C_WW_STAR_SPINNER_SOP", opa: "1D40", xlu: "1D45" },
    { name: "WW_MUMBO", sceneID: "176", dir: "176_WW_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "JRL_JOLLY_ROGERS_LAGOON", sceneID: "1A7", dir: "1A7_JRL_JOLLY_ROGERS_LAGOON", opa: "", xlu: "1D5C", sectors: [["727", "", [-9000, 9000, -8000]], ["734", "", [-9000, 9000, -9200]], ["728", "", [-9000, 2000, -3200]], ["72B", "", [-5500, 1200, -7100]], ["72C", "", [-5400, -1200, 1200]]] },
    { name: "JRL_ATLANTIS", sceneID: "1A8", dir: "1A8_JRL_ATLANTIS", opa: "", xlu: "1D5C", sectors: [["72A", "", [-4400, -3500, 8200]], ["730", "", [3500, -5600, 2600]], ["72D", "", [3500, -6000, 10200]], ["733", "737", [-16900, -800, 9400]]] },
    { name: "JRL_SEA_BOTTOM", sceneID: "1A9", dir: "1A9_JRL_SEA_BOTTOM", opa: "", xlu: "1D5C", sectors: [["72E", "", [8000, -6700, 300]], ["72F", "", [14300, -6300, -4600]], ["731", "", [8500, -8000, -8200]], ["732", "738", [12200, -3800, 5500]]] },
    { name: "JRL_JOLLYS", sceneID: "ED", dir: "0ED_JRL_JOLLYS", opa: "1D57", xlu: "1D63" },
    { name: "JRL_PAWNO", sceneID: "EE", dir: "0EE_JRL_PAWNO", opa: "1D59", xlu: "1D5A" },
    { name: "JRL_MUMBO", sceneID: "EF", dir: "0EF_JRL_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "JRL_UFO", sceneID: "F1", dir: "0F1_JRL_UFO", opa: "1D4C", xlu: "1D64" },
    { name: "JRL_ANCIENT_SWIMMING_BATHS", sceneID: "F4", dir: "0F4_JRL_ANCIENT_SWIMMING_BATHS", opa: "1D4D", xlu: "1D4E" },
    { name: "JRL_ELECTRIC_EELS_LAIR", sceneID: "F6", dir: "0F6_JRL_ELECTRIC_EELS_LAIR", opa: "1D4F", xlu: "1D50" },
    { name: "JRL_SEAWEED_SACTUM", sceneID: "F7", dir: "0F7_JRL_SEAWEED_SACTUM", opa: "1D51", xlu: "1D52" },
    { name: "JRL_INSIDE_BIG_FISH", sceneID: "F8", dir: "0F8_JRL_INSIDE_BIG_FISH", opa: "1D53", xlu: "1D54" },
    { name: "JRL_TEMPLE_OF_FISHES", sceneID: "FA", dir: "0FA_JRL_TEMPLE_OF_FISHES", opa: "1D55", xlu: "1D5D" },
    { name: "JRL_LORD_WOO_FAK_FAK", sceneID: "FC", dir: "0FC_JRL_LORD_WOO_FAK_FAK", opa: "1D58", xlu: "" },
    { name: "JRL_BLUBBERS_SHOP", sceneID: "FF", dir: "0FF_JRL_BLUBBERS_SHOP", opa: "1D5B", xlu: "" },
    { name: "JRL_WUMBA", sceneID: "120", dir: "120_JRL_WUMBA", opa: "1D00", xlu: "1D07" },
    { name: "JRL_SEA_BOTTOM_CAVERN", sceneID: "181", dir: "181_JRL_SEA_BOTTOM_CAVERN", opa: "1D60", xlu: "" },
    { name: "JRL_SMUGGLERS_CAVERN", sceneID: "1A6", dir: "1A6_JRL_SMUGGLERS_CAVERN", opa: "729", xlu: "736" },
    { name: "TDL_TERRYDACTYLAND", sceneID: "112", dir: "112_TDL_TERRYDACTYLAND", opa: "1D66", xlu: "1D72" },
    { name: "TDL_TERRYS_NEST", sceneID: "113", dir: "113_TDL_TERRYS_NEST", opa: "1D6B", xlu: "1D75" },
    { name: "TDL_TRAIN_STATION", sceneID: "114", dir: "114_TDL_TRAIN_STATION", opa: "1D6E", xlu: "" },
    { name: "TDL_OOGLE_BOOGLE_CAVE", sceneID: "115", dir: "115_TDL_OOGLE_BOOGLE_CAVE", opa: "1D6F", xlu: "" },
    { name: "TDL_INSIDE_MOUNTAIN", sceneID: "116", dir: "116_TDL_INSIDE_MOUNTAIN", opa: "1D69", xlu: "1D6A" },
    { name: "TDL_RIVER_PASSAGE", sceneID: "117", dir: "117_TDL_RIVER_PASSAGE", opa: "1D6C", xlu: "1D6D" },
    { name: "TDL_STYRACOSAURUS_FAMILY_CAVE", sceneID: "118", dir: "118_TDL_STYRACOSAURUS_FAMILY_CAVE", opa: "1D68", xlu: "" },
    { name: "TDL_UNGA_BUNGAS_CAVE", sceneID: "119", dir: "119_TDL_UNGA_BUNGAS_CAVE", opa: "1D70", xlu: "" },
    { name: "TDL_STOMPING_PLAINS", sceneID: "11A", dir: "11A_TDL_STOMPING_PLAINS", opa: "1D71", xlu: "" },
    { name: "TDL_BONFIRE_CAVERNS", sceneID: "11B", dir: "11B_TDL_BONFIRE_CAVERNS", opa: "1D67", xlu: "" },
    { name: "TDL_SMALL_WUMBA", sceneID: "11E", dir: "11E_TDL_SMALL_WUMBA", opa: "1D00", xlu: "1D05" },
    { name: "TDL_BIG_WUMBA", sceneID: "122", dir: "122_TDL_BIG_WUMBA", opa: "1D03", xlu: "1D06" },
    { name: "TDL_INSIDE_CHOMPA_BELLY", sceneID: "123", dir: "123_TDL_INSIDE_CHOMPA_BELLY", opa: "1D73", xlu: "" },
    { name: "TDL_MUMBO", sceneID: "171", dir: "171_TDL_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "GI_OUTSIDE", sceneID: "100", dir: "100_GI_OUTSIDE", opa: "1D76", xlu: "1D88" },
    { name: "GI_INSIDE", sceneID: "101", dir: "101_GI_INSIDE", opa: "1D77", xlu: "1D87" },
    { name: "GI_TRAIN_STATION", sceneID: "102", dir: "102_GI_TRAIN_STATION", opa: "1D7D", xlu: "1D8C" },
    { name: "GI_WORKERS_QUARTERS", sceneID: "103", dir: "103_GI_WORKERS_QUARTERS", opa: "1D82", xlu: "1D95" },
    { name: "GI_TRASH_COMPACTOR", sceneID: "104", dir: "104_GI_TRASH_COMPACTOR", opa: "1D7E", xlu: "" },
    { name: "GI_ELEVATOR_SHAFT", sceneID: "105", dir: "105_GI_ELEVATOR_SHAFT", opa: "1D7B", xlu: "" },
    { name: "GI_FLOOR_2", sceneID: "106", dir: "106_GI_FLOOR_2", opa: "1D78", xlu: "1D8F" },
    { name: "GI_FLOOR_2_ELECTROMAGNETIC_CHAMBER", sceneID: "107", dir: "107_GI_FLOOR_2_ELECTROMAGNETIC_CHAMBER", opa: "1D80", xlu: "" },
    { name: "GI_FLOOR_3", sceneID: "108", dir: "108_GI_FLOOR_3", opa: "1D79", xlu: "1D90" },
    { name: "GI_FLOOR_3_BOILER_PLANT", sceneID: "109", dir: "109_GI_FLOOR_3_BOILER_PLANT", opa: "1D7F", xlu: "1D94" },
    { name: "GI_FLOOR_3_PACKING_ROOM", sceneID: "10A", dir: "10A_GI_FLOOR_3_PACKING_ROOM", opa: "1D8A", xlu: "" },
    { name: "GI_FLOOR_4", sceneID: "10B", dir: "10B_GI_FLOOR_4", opa: "1D7A", xlu: "1D91" },
    { name: "GI_FLOOR_4_CABLE_ROOM", sceneID: "10C", dir: "10C_GI_FLOOR_4_CABLE_ROOM", opa: "1D84", xlu: "" },
    { name: "GI_FLOOR_4_QUALITY_CONTROL", sceneID: "10D", dir: "10D_GI_FLOOR_4_QUALITY_CONTROL", opa: "1D85", xlu: "1D89" },
    { name: "GI_FLOOR_5", sceneID: "10E", dir: "10E_GI_FLOOR_5", opa: "1D83", xlu: "1D92" },
    { name: "GI_BASEMENT", sceneID: "10F", dir: "10F_GI_BASEMENT", opa: "1D7C", xlu: "1D93" },
    { name: "GI_BASEMENT_REPAIR_DEPOT", sceneID: "110", dir: "110_GI_BASEMENT_REPAIR_DEPOT", opa: "1D8B", xlu: "" },
    { name: "GI_BASEMENT_WASTE_DISPOSAL", sceneID: "111", dir: "111_GI_BASEMENT_WASTE_DISPOSAL", opa: "1D81", xlu: "1D86" },
    { name: "GI_WUMBA", sceneID: "11F", dir: "11F_GI_WUMBA", opa: "1D00", xlu: "1D05" },
    { name: "GI_WATER_SUPPLY_PIPE", sceneID: "125", dir: "125_GI_WATER_SUPPLY_PIPE", opa: "1D5F", xlu: "" },
    { name: "GI_FLOOR_4_CLINKERS_CAVERN", sceneID: "162", dir: "162_GI_FLOOR_4_CLINKERS_CAVERN", opa: "1D8D", xlu: "" },
    { name: "GI_MUMBO", sceneID: "172", dir: "172_GI_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "GI_FLOOR_4_SEWER_ENTRANCE", sceneID: "187", dir: "187_GI_FLOOR_4_SEWER_ENTRANCE", opa: "1D8E", xlu: "1D96" },
    { name: "HP_LAVA_SIDE", sceneID: "127", dir: "127_HP_LAVA_SIDE", opa: "1D99", xlu: "1D9A" },
    { name: "HP_ICY_SIDE", sceneID: "128", dir: "128_HP_ICY_SIDE", opa: "1D9B", xlu: "1D9C" },
    { name: "HP_FIRE_TRAIN_STATION", sceneID: "129", dir: "129_HP_FIRE_TRAIN_STATION", opa: "1DA0", xlu: "" },
    { name: "HP_ICE_TRAIN_STATION", sceneID: "12A", dir: "12A_HP_ICE_TRAIN_STATION", opa: "1D9E", xlu: "1D9F" },
    { name: "HP_CHILLI_BILLI", sceneID: "12B", dir: "12B_HP_CHILLI_BILLI", opa: "1DA5", xlu: "1DA9" },
    { name: "HP_CHILLY_WILLY", sceneID: "12C", dir: "12C_HP_CHILLY_WILLY", opa: "1DA6", xlu: "1DAA" },
    { name: "HP_KICKBALL_LOBBY", sceneID: "12D", dir: "12D_HP_KICKBALL_LOBBY", opa: "1DA3", xlu: "" },
    { name: "HP_KICKBALL_1", sceneID: "12E", dir: "12E_HP_KICKBALL_1", opa: "1DA7", xlu: "" },
    { name: "HP_KICKBALL_2", sceneID: "12F", dir: "12F_HP_KICKBALL_2", opa: "1DA7", xlu: "" },
    { name: "HP_KICKBALL_3", sceneID: "130", dir: "130_HP_KICKBALL_3", opa: "1DA7", xlu: "" },
    { name: "HP_BOGGYS_IGLOO", sceneID: "131", dir: "131_HP_BOGGYS_IGLOO", opa: "1D9D", xlu: "1DA8" },
    { name: "HP_ICICLE_GROTTO", sceneID: "132", dir: "132_HP_ICICLE_GROTTO", opa: "1DA1", xlu: "1DA2" },
    { name: "HP_INSIDE_VOLCANO", sceneID: "133", dir: "133_HP_INSIDE_VOLCANO", opa: "1DA4", xlu: "" },
    { name: "HP_MUMBO", sceneID: "134", dir: "134_HP_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "HP_WUMBA", sceneID: "135", dir: "135_HP_WUMBA", opa: "1D00", xlu: "1D05" },
    { name: "CCL_CLOUD_CUCKOOLAND", sceneID: "136", dir: "136_CCL_CLOUD_CUCKOOLAND", opa: "1DAB", xlu: "1DB3" },
    { name: "CCL_TRASHCAN", sceneID: "137", dir: "137_CCL_TRASHCAN", opa: "1DB1", xlu: "1DB2" },
    { name: "CCL_CHEESEWEDGE", sceneID: "138", dir: "138_CCL_CHEESEWEDGE", opa: "1DB0", xlu: "1DB6" },
    { name: "CCL_ZUBBA_NEST", sceneID: "139", dir: "139_CCL_ZUBBA_NEST", opa: "1DB5", xlu: "1DB7" },
    { name: "CCL_CENTRAL_CAVERN", sceneID: "13A", dir: "13A_CCL_CENTRAL_CAVERN", opa: "1DAC", xlu: "1DB4" },
    { name: "CCL_POT_O_GOLD", sceneID: "13D", dir: "13D_CCL_POT_O_GOLD", opa: "1DAD", xlu: "1DAE" },
    { name: "CCL_MUMBO", sceneID: "13E", dir: "13E_CCL_MUMBO", opa: "1D01", xlu: "1D02" },
    { name: "CCL_MINGY_JONGO", sceneID: "13F", dir: "13F_CCL_MINGY_JONGO", opa: "1D01", xlu: "1D02" },
    { name: "CCL_WUMBA", sceneID: "140", dir: "140_CCL_WUMBA", opa: "1D00", xlu: "1D05" },
    { name: "CCL_RACE", sceneID: "161", dir: "161_CCL_RACE", opa: "1DAB", xlu: "1DB3" },
    { name: "CK_CAULDRON_KEEP", sceneID: "15D", dir: "15D_CK_CAULDRON_KEEP", opa: "1DB9", xlu: "1DBA" },
    { name: "CK_GATEHOUSE", sceneID: "15E", dir: "15E_CK_GATEHOUSE", opa: "1DBC", xlu: "" },
    { name: "CK_QUIZ", sceneID: "15F", dir: "15F_CK_QUIZ", opa: "1DBD", xlu: "" },
    { name: "CK_GUN_CHAMBER", sceneID: "160", dir: "160_CK_GUN_CHAMBER", opa: "1DBB", xlu: "" },
    { name: "CK_GUN_CHAMBER_STILL", sceneID: "16A", dir: "16A_CK_GUN_CHAMBER_STILL", opa: "1DBB", xlu: "" },
    { name: "CK_INSIDE_DIGGER", sceneID: "18A", dir: "18A_CK_INSIDE_DIGGER", opa: "1DBE", xlu: "" },
    { name: "CK_CAULDRON_KEEP_HAG_1", sceneID: "19A", dir: "19A_CK_CAULDRON_KEEP_HAG_1", opa: "1DBF", xlu: "1DBA" },
    { name: "MP_ORDNANCE_STORAGE", sceneID: "164", dir: "164_MP_ORDNANCE_STORAGE", opa: "1D8D", xlu: "" },
    { name: "MP_ORDNANCE_SHOOTING", sceneID: "165", dir: "165_MP_ORDNANCE_SHOOTING", opa: "1D34", xlu: "" },
    { name: "MP_TARGITZAN_TEMPLE", sceneID: "166", dir: "166_MP_TARGITZAN_TEMPLE", opa: "1D16", xlu: "" },
    { name: "MP_BALLOONS", sceneID: "17B", dir: "17B_MP_BALLOONS", opa: "1D4B", xlu: "" },
    { name: "MP_HOOPS", sceneID: "17C", dir: "17C_MP_HOOPS", opa: "1D4B", xlu: "" },
    { name: "MP_PACKING_GAME", sceneID: "17D", dir: "17D_MP_PACKING_GAME", opa: "1D8A", xlu: "" },
    { name: "MP_KICKBALL_1", sceneID: "17F", dir: "17F_MP_KICKBALL_1", opa: "1D14", xlu: "" },
    { name: "MP_KICKBALL_2", sceneID: "180", dir: "180_MP_KICKBALL_2", opa: "1DA7", xlu: "" },
    { name: "MP_SUBMARINE", sceneID: "182", dir: "182_MP_SUBMARINE", opa: "1D60", xlu: "" },
    { name: "MP_CHOMPAS_BELLY", sceneID: "183", dir: "183_MP_CHOMPAS_BELLY", opa: "1D73", xlu: "" },
    { name: "MP_TRASHCAN", sceneID: "185", dir: "185_MP_TRASHCAN", opa: "1DB1", xlu: "" },
    { name: "MP_DODGEMS", sceneID: "186", dir: "186_MP_DODGEMS", opa: "1D42", xlu: "" },
    { name: "MP_BEE_HIVE", sceneID: "188", dir: "188_MP_BEE_HIVE", opa: "1DB5", xlu: "1DB7" },
    { name: "MP_QUIZ", sceneID: "189", dir: "189_MP_QUIZ", opa: "1DBD", xlu: "" },
    { name: "GAME_SELECT", sceneID: "158", dir: "158_GAME_SELECT", opa: "80B", xlu: "" },
    { name: "CS_INTRO", sceneID: "A1", dir: "0A1_CS_INTRO", opa: "1CF9", xlu: "" },
    { name: "CS_DRILL_START", sceneID: "A2", dir: "0A2_CS_DRILL_START", opa: "1CF9", xlu: "" },
    { name: "CS_DRILL_BOULDER", sceneID: "A3", dir: "0A3_CS_DRILL_BOULDER", opa: "1CF9", xlu: "" },
    { name: "CS_MAGIC_LIFT_BOULDER", sceneID: "A4", dir: "0A4_CS_MAGIC_LIFT_BOULDER", opa: "1CF9", xlu: "1CFA" },
    { name: "CS_REVENGE", sceneID: "A5", dir: "0A5_CS_REVENGE", opa: "1CF9", xlu: "1CFA" },
    { name: "CS_WITCHES_LEAVE", sceneID: "A6", dir: "0A6_CS_WITCHES_LEAVE", opa: "1CF9", xlu: "1CFA" },
    { name: "CS_HOUSE_DESTROYED", sceneID: "A7", dir: "0A7_CS_HOUSE_DESTROYED", opa: "1CF9", xlu: "1CFA" },
    { name: "CS_POKER", sceneID: "A8", dir: "0A8_CS_POKER", opa: "1CFB", xlu: "1CFC" },
    { name: "CS_EARTHQUAKE", sceneID: "A9", dir: "0A9_CS_EARTHQUAKE", opa: "1CFB", xlu: "1CFC" },
    { name: "CS_IT_STOPPED", sceneID: "AA", dir: "0AA_CS_IT_STOPPED", opa: "1CFB", xlu: "1CFC" },
    { name: "CS_EVACUATE_HOUSE", sceneID: "AB", dir: "0AB_CS_EVACUATE_HOUSE", opa: "1CFB", xlu: "1CFC" },
    { name: "CS_COME_ON", sceneID: "AC", dir: "0AC_CS_COME_ON", opa: "1CFB", xlu: "1CFC" },
    { name: "CS_DUPLICATE_INTRO", sceneID: "159", dir: "159_CS_DUPLICATE_INTRO", opa: "", xlu: "" },
    { name: "CS_ZOMBIE_JINGALING", sceneID: "17E", dir: "17E_CS_ZOMBIE_JINGALING", opa: "1DD2", xlu: "" },
    { name: "CS_STARTUP_INTRO", sceneID: "18B", dir: "18B_CS_STARTUP_INTRO", opa: "1CF9", xlu: "1CFA" },
    { name: "CS_PARTY_ENDED", sceneID: "191", dir: "191_CS_PARTY_ENDED", opa: "1DD0", xlu: "1DD3" },
    { name: "CS_BOTTLES_GETS_HOME", sceneID: "192", dir: "192_CS_BOTTLES_GETS_HOME", opa: "1DD0", xlu: "1DD3" },
    { name: "CS_BOTTLES_REVIVED", sceneID: "193", dir: "193_CS_BOTTLES_REVIVED", opa: "1CF9", xlu: "1CFA" },
    { name: "CS_ABOUT_TO_BOB", sceneID: "194", dir: "194_CS_ABOUT_TO_BOB", opa: "1DBB", xlu: "" },
    { name: "CS_LETS_FIX_BOTTLES", sceneID: "195", dir: "195_CS_LETS_FIX_BOTTLES", opa: "1DBB", xlu: "" },
    { name: "CS_GRUNTY_HEAD_PLAYING", sceneID: "196", dir: "196_CS_GRUNTY_HEAD_PLAYING", opa: "1DB9", xlu: "1DBA" },
    { name: "CS_JINGALING_REVIVE", sceneID: "197", dir: "197_CS_JINGALING_REVIVE", opa: "1DB9", xlu: "1DBA" },
    { name: "CS_JINGALING_TEMPLE_FIX", sceneID: "198", dir: "198_CS_JINGALING_TEMPLE_FIX", opa: "1DC1", xlu: "" },
    { name: "CS_JINGALING_CELEBRATE", sceneID: "199", dir: "199_CS_JINGALING_CELEBRATE", opa: "1DD1", xlu: "" },
    { name: "CS_CREDITS", sceneID: "19C", dir: "19C_CS_CREDITS", opa: "1DBD", xlu: "" },
    { name: "CS_CHARACTER_PARADE", sceneID: "19D", dir: "19D_CS_CHARACTER_PARADE", opa: "1DBD", xlu: "" },
    { name: "BOB_EXPLANATION", sceneID: "18C", dir: "18C_BOB_EXPLANATION", opa: "1DBB", xlu: "" },
    { name: "BOB_FIRING_AT_JV", sceneID: "18F", dir: "18F_BOB_FIRING_AT_JV", opa: "1DB9", xlu: "1DBA" },
    { name: "MEANWHILE", sceneID: "18E", dir: "18E_MEANWHILE", opa: "1DB9", xlu: "1DBA" },
    { name: "JINGALING_TEMPLE_DRAIN", sceneID: "190", dir: "190_JINGALING_TEMPLE_DRAIN", opa: "1DC1", xlu: "" },
    { name: "ENERGY_GAINED_BOB", sceneID: "18D", dir: "18D_ENERGY_GAINED_BOB", opa: "1DBB", xlu: "" },
    { name: "CHUFFYS_CAB", sceneID: "D0", dir: "0D0_CHUFFYS_CAB", opa: "1D1F", xlu: "" },
    { name: "INSIDE_CHUFFY_WAGON", sceneID: "121", dir: "121_INSIDE_CHUFFY_WAGON", opa: "1D33", xlu: "" },
    { name: "ICY_SIDE_STILL", sceneID: "168", dir: "168_ICY_SIDE_STILL", opa: "1D9B", xlu: "1D9C" },
    { name: "BOTTLES_HOUSE_STILL", sceneID: "169", dir: "169_BOTTLES_HOUSE_STILL", opa: "1DD0", xlu: "1DD3" },
    { name: "BETA_PIPE", sceneID: "184", dir: "184_BETA_PIPE", opa: "1D61", xlu: "1D62" },
];

const OOT_Maps = [
    { name: "Spot 00 - Hyrule Field", file: "spot00_scene" },
    { name: "Spot 01 - Kakariko Village", file: "spot01_scene" },
    { name: "Spot 02 - Graveyard", file: "spot02_scene" },
    { name: "Spot 03 - Zora's River", file: "spot03_scene" },
    { name: "Spot 04 - Kokiri Forest", file: "spot04_scene" },
    { name: "Spot 05 - Sacred Forest Meadow", file: "spot05_scene" },
    { name: "Spot 06 - Lake Hylia", file: "spot06_scene" },
    { name: "Spot 07 - Zora's Domain", file: "spot07_scene" },
    { name: "Spot 08 - Zora's Fountain", file: "spot08_scene" },
    { name: "Spot 09 - Gerudo Valley", file: "spot09_scene" },
    { name: "Spot 10 - Lost Woods", file: "spot10_scene" },
    { name: "Spot 11 - Desert Colossus", file: "spot11_scene" },
    { name: "Spot 12 - Gerudo's Fortress", file: "spot12_scene" },
    { name: "Spot 13 - Haunted Wasteland", file: "spot13_scene" },
    { name: "Spot 15 - Hyrule Castle", file: "spot15_scene" },
    { name: "Spot 16 - Death Mountain Trail", file: "spot16_scene" },
    { name: "Spot 17 - Death Mountain Crater", file: "spot17_scene" },
    { name: "Spot 18 - Goron City", file: "spot18_scene" },
    { name: "Spot 20 - Lon Lon Ranch", file: "spot20_scene" },
    { name: "Back Alley (Day)", file: "market_alley_scene" },
    { name: "Back Alley (Night)", file: "market_alley_n_scene" },
    { name: "Back Alley House (Dog Lady)", file: "impa_scene" },
    { name: "Back Alley House (Man in Green)", file: "kakariko3_scene" },
    { name: "Barinade's Lair", file: "bdan_boss_scene" },
    { name: "Bazaar", file: "shop1_scene" },
    { name: "Bombchu Bowling Alley", file: "bowling_scene" },
    { name: "Bombchu Shop", file: "night_shop_scene" },
    { name: "Bongo Bongo's Lair", file: "HAKAdan_bs_scene" },
    { name: "Bottom of the Well", file: "HAKAdanCH_scene" },
    { name: "Carpenter Boss's House", file: "kakariko_scene" },
    { name: "Carpenters' Tent", file: "tent_scene" },
    { name: "Castle Courtyard", file: "nakaniwa_scene" },
    { name: "Castle Hedge Maze (Day)", file: "hairal_niwa_scene" },
    { name: "Castle Hedge Maze (Night)", file: "hairal_niwa_n_scene" },
    { name: "Chamber of the Sages", file: "kenjyanoma_scene" },
    { name: "Cutscene Map", file: "hiral_demo_scene" },
    { name: "Dampe's Grave & Windmill", file: "hakasitarelay_scene" },
    { name: "Dodongo's Cavern", file: "ddan_scene" },
    { name: "Fairy's Fountain (Healing Fairies)", file: "yousei_izumi_tate_scene" },
    { name: "Fire Temple", file: "HIDAN_scene" },
    { name: "Fishing Pond", file: "turibori_scene" },
    { name: "Forest Temple", file: "Bmori1_scene" },
    { name: "Ganon's Castle Exterior", file: "ganon_tou_scene" },
    { name: "Ganon's Tower", file: "ganon_scene" },
    { name: "Ganon's Tower (Collapsing)", file: "ganon_sonogo_scene" },
    { name: "Ganon's Tower Exterior (Collapsing)", file: "ganon_final_scene" },
    { name: "Ganon Battle Arena", file: "ganon_demo_scene" },
    { name: "Ganondorf's Lair", file: "ganon_boss_scene" },
    { name: "Gerudo Training Ground", file: "men_scene" },
    { name: "Gohma's Lair", file: "ydan_boss_scene" },
    { name: "Goron Shop", file: "golon_scene" },
    { name: "Granny's Potion Shop", file: "mahouya_scene" },
    { name: "Grave (Fairy's Fountain)", file: "hakaana2_scene" },
    { name: "Grave (Redead)", file: "hakaana_scene" },
    { name: "Gravekeeper's Hut", file: "hut_scene" },
    { name: "Great Fairy's Fountain (Spells)", file: "yousei_izumi_yoko_scene" },
    { name: "Great Fairy's Fountain (Upgrades)", file: "daiyousei_izumi_scene" },
    { name: "Grottos", file: "kakusiana_scene" },
    { name: "Guard House", file: "miharigoya_scene" },
    { name: "Happy Mask Shop", file: "face_shop_scene" },
    { name: "House of Skulltula", file: "kinsuta_scene" },
    { name: "House of Twins", file: "kokiri_home3_scene" },
    { name: "Ice Cavern", file: "ice_doukutu_scene" },
    { name: "Impa's House", file: "labo_scene" },
    { name: "Inside Ganon's Castle", file: "ganontika_scene" },
    { name: "Inside Ganon's Castle (Collapsing)", file: "ganontikasonogo_scene" },
    { name: "Inside Jabu-Jabu's Belly", file: "bdan_scene" },
    { name: "Inside the Deku Tree", file: "ydan_scene" },
    { name: "Kakariko Potion Shop", file: "drag_scene" },
    { name: "King Dodongo's Lair", file: "ddan_boss_scene" },
    { name: "Know-It-All Brothers' House", file: "kokiri_home_scene" },
    { name: "Kokiri Shop", file: "kokiri_shop_scene" },
    { name: "Lakeside Laboratory", file: "hylia_labo_scene" },
    { name: "Link's House", file: "link_home_scene" },
    { name: "Lon Lon Ranch House & Tower", file: "souko_scene" },
    { name: "Market (Child - Day)", file: "market_day_scene" },
    { name: "Market (Child - Night)", file: "market_night_scene" },
    { name: "Market (Ruins)", file: "market_ruins_scene" },
    { name: "Market Entrance (Child - Day)", file: "entra_scene" },
    { name: "Market Entrance (Child - Night)", file: "entra_n_scene" },
    { name: "Market Entrance (Ruins)", file: "enrui_scene" },
    { name: "Market Potion Shop", file: "alley_shop_scene" },
    { name: "Mido's House", file: "kokiri_home4_scene" },
    { name: "Morpha's Lair", file: "MIZUsin_bs_scene" },
    { name: "Phantom Ganon's Lair", file: "moribossroom_scene" },
    { name: "Royal Family's Tomb", file: "hakaana_ouke_scene" },
    { name: "Saria's House", file: "kokiri_home5_scene" },
    { name: "Shadow Temple", file: "HAKAdan_scene" },
    { name: "Shooting Gallery", file: "syatekijyou_scene" },
    { name: "Spirit Temple", file: "jyasinzou_scene" },
    { name: "Stable", file: "malon_stable_scene" },
    { name: "Temple of Time", file: "tokinoma_scene" },
    { name: "Temple of Time Exterior (Day)", file: "shrine_scene" },
    { name: "Temple of Time Exterior (Night)", file: "shrine_n_scene" },
    { name: "Temple of Time Exterior (Ruins)", file: "shrine_r_scene" },
    { name: "Thieves' Hideout", file: "gerudoway_scene" },
    { name: "Treasure Chest Shop", file: "takaraya_scene" },
    { name: "Twinrova's Lair", file: "jyasinboss_scene" },
    { name: "Volvagia's Lair", file: "FIRE_bs_scene" },
    { name: "Water Temple", file: "MIZUsin_scene" },
    { name: "Zora Shop", file: "zoora_scene" }
];

const MM_Maps = [
    { name: "Ancient Castle of Ikana", file: "Z2_CASTLE" },
    { name: "Astral Observatory", file: "Z2_TENMON_DAI" },
    { name: "Before the Portal to Termina", file: "Z2_OPENINGDAN" },
    { name: "Beneath the Graveyard", file: "Z2_HAKASHITA" },
    { name: "Beneath the Well", file: "Z2_REDEAD" },
    { name: "Bomb Shop", file: "Z2_BOMYA" },
    { name: "Clock Tower Interior", file: "Z2_INSIDETOWER" },
    { name: "Clock Tower Rooftop", file: "Z2_OKUJOU" },
    { name: "Cucco Shack", file: "Z2_F01C" },
    { name: "Curiosity Shop", file: "Z2_AYASHIISHOP" },
    { name: "Cutscene Map", file: "SPOT00" },
    { name: "Dampe's House", file: "Z2_DANPEI2TEST" },
    { name: "Deku King's Chamber", file: "Z2_DEKU_KING" },
    { name: "Deku Palace", file: "Z2_22DEKUCITY" },
    { name: "Deku Scrub Playground", file: "Z2_DEKUTES" },
    { name: "Deku Shrine", file: "Z2_DANPEI" },
    { name: "Doggy Racetrack", file: "Z2_F01_B" },
    { name: "East Clock Town", file: "Z2_TOWN" },
    { name: "Fairy's Fountain", file: "Z2_YOUSEI_IZUMI" },
    { name: "Fisherman's Hut", file: "Z2_FISHERMAN" },
    { name: "Ghost Hut", file: "Z2_TOUGITES" },
    { name: "Giants' Chamber", file: "Z2_KYOJINNOMA" },
    { name: "Goht's Lair", file: "Z2_HAKUGIN_BS" },
    { name: "Gorman Track", file: "Z2_KOEPONARACE" },
    { name: "Goron Graveyard", file: "Z2_GORON_HAKA" },
    { name: "Goron Racetrack", file: "Z2_GORONRACE" },
    { name: "Goron Shop", file: "Z2_GORONSHOP" },
    { name: "Goron Shrine", file: "Z2_16GORON_HOUSE" },
    { name: "Goron Village (Spring)", file: "Z2_11GORONNOSATO2" },
    { name: "Goron Village (Winter)", file: "Z2_11GORONNOSATO" },
    { name: "Great Bay (Cutscene)", file: "Z2_KONPEKI_ENT" },
    { name: "Great Bay Coast", file: "Z2_30GYOSON" },
    { name: "Great Bay Temple", file: "Z2_SEA" },
    { name: "Grottos", file: "KAKUSIANA" },
    { name: "Gyorg's Lair", file: "Z2_SEA_BS" },
    { name: "Honey & Darling's Shop", file: "Z2_BOWLING" },
    { name: "Igos du Ikana's Lair", file: "Z2_IKNINSIDE" },
    { name: "Ikana Canyon", file: "Z2_IKANA" },
    { name: "Ikana Graveyard", file: "Z2_BOTI" },
    { name: "Laundry Pool", file: "Z2_ALLEY" },
    { name: "Lost Woods", file: "Z2_LOST_WOODS" },
    { name: "Lottery Shop", file: "Z2_TAKARAKUJI" },
    { name: "Magic Hags' Potion Shop", file: "Z2_WITCH_SHOP" },
    { name: "Majora's Lair", file: "Z2_LAST_BS" },
    { name: "Marine Research Lab", file: "Z2_LABO" },
    { name: "Mayor's Residence", file: "Z2_SONCHONOIE" },
    { name: "Milk Bar", file: "Z2_MILK_BAR" },
    { name: "Milk Road", file: "Z2_ROMANYMAE" },
    { name: "Mountain Smithy", file: "Z2_KAJIYA" },
    { name: "Mountain Village (Spring)", file: "Z2_10YUKIYAMANOMURA2" },
    { name: "Mountain Village (Winter)", file: "Z2_10YUKIYAMANOMURA" },
    { name: "Music Box House", file: "Z2_MUSICHOUSE" },
    { name: "North Clock Town", file: "Z2_BACKTOWN" },
    { name: "Oceanside Spider House", file: "Z2_KINDAN2" },
    { name: "Odolwa's Lair", file: "Z2_MITURIN_BS" },
    { name: "Path to Goron Village (Spring)", file: "Z2_17SETUGEN2" },
    { name: "Path to Goron Village (Winter)", file: "Z2_17SETUGEN" },
    { name: "Path to Mountain Village", file: "Z2_13HUBUKINOMITI" },
    { name: "Path to Snowhead", file: "Z2_14YUKIDAMANOMITI" },
    { name: "Pinnacle Rock", file: "Z2_SINKAI" },
    { name: "Pirates' Fortress", file: "Z2_KAIZOKU" },
    { name: "Pirates' Fortress Exterior", file: "Z2_TORIDE" },
    { name: "Pirates' Fortress Interior", file: "Z2_PIRATE" },
    { name: "Post Office", file: "Z2_POSTHOUSE" },
    { name: "Ranch House & Barn", file: "Z2_OMOYA" },
    { name: "Road to Ikana", file: "Z2_IKANAMAE" },
    { name: "Road to Southern Swamp", file: "Z2_24KEMONOMITI" },
    { name: "Romani Ranch", file: "Z2_F01" },
    { name: "Sakon's Hideout", file: "Z2_SECOM" },
    { name: "Secret Shrine", file: "Z2_RANDOM" },
    { name: "Snowhead", file: "Z2_12HAKUGINMAE" },
    { name: "Snowhead Temple", file: "Z2_HAKUGIN" },
    { name: "South Clock Town", file: "Z2_CLOCKTOWER" },
    { name: "Southern Swamp (Clear)", file: "Z2_20SICHITAI2" },
    { name: "Southern Swamp (Poisoned)", file: "Z2_20SICHITAI" },
    { name: "Stock Pot Inn", file: "Z2_YADOYA" },
    { name: "Stone Tower", file: "Z2_F40" },
    { name: "Stone Tower (Inverted)", file: "Z2_F41" },
    { name: "Stone Tower Temple", file: "Z2_INISIE_N" },
    { name: "Stone Tower Temple (Inverted)", file: "Z2_INISIE_R" },
    { name: "Swamp Shooting Gallery", file: "Z2_SYATEKI_MORI" },
    { name: "Swamp Spider House", file: "Z2_KINSTA1" },
    { name: "Swordsman's School", file: "Z2_DOUJOU" },
    { name: "Termina Field", file: "Z2_00KEIKOKU" },
    { name: "The Moon", file: "Z2_SOUGEN" },
    { name: "The Moon - Deku Trial", file: "Z2_LAST_DEKU" },
    { name: "The Moon - Goron Trial", file: "Z2_LAST_GORON" },
    { name: "The Moon - Link Trial", file: "Z2_LAST_LINK" },
    { name: "The Moon - Zora Trial", file: "Z2_LAST_ZORA" },
    { name: "Tourist Information", file: "Z2_MAP_SHOP" },
    { name: "Town Shooting Gallery", file: "Z2_SYATEKI_MIZU" },
    { name: "Trading Post", file: "Z2_8ITEMSHOP" },
    { name: "Treasure Chest Shop", file: "Z2_TAKARAYA" },
    { name: "Twinmold's Lair", file: "Z2_INISIE_BS" },
    { name: "Waterfall Rapids", file: "Z2_35TAKI" },
    { name: "West Clock Town", file: "Z2_ICHIBA" },
    { name: "Woodfall", file: "Z2_21MITURINMAE" },
    { name: "Woodfall Temple", file: "Z2_MITURIN" },
    { name: "Woods of Mystery", file: "Z2_26SARUNOMORI" },
    { name: "Zora Cape", file: "Z2_31MISAKI" },
    { name: "Zora Hall", file: "Z2_33ZORACITY" },
    { name: "Zora Hall Rooms", file: "Z2_BANDROOM" }
];

const OOT3D_Maps = [
    { name: "Spot 00 - Hyrule Field", file: "spot00_info.zsi" },
    { name: "Spot 01 - Kakariko Village", file: "spot01_info.zsi" },
    { name: "Spot 02 - Graveyard", file: "spot02_info.zsi" },
    { name: "Spot 03 - Zora's River", file: "spot03_info.zsi" },
    { name: "Spot 04 - Kokiri Forest", file: "spot04_info.zsi" },
    { name: "Spot 05 - Sacred Forest Meadow", file: "spot05_info.zsi" },
    { name: "Spot 06 - Lake Hylia", file: "spot06_info.zsi" },
    { name: "Spot 07 - Zora's Domain", file: "spot07_info.zsi" },
    { name: "Spot 08 - Zora's Fountain", file: "spot08_info.zsi" },
    { name: "Spot 09 - Gerudo Valley", file: "spot09_info.zsi" },
    { name: "Spot 10 - Lost Woods", file: "spot10_info.zsi" },
    { name: "Spot 11 - Desert Colossus", file: "spot11_info.zsi" },
    { name: "Spot 12 - Gerudo's Fortress", file: "spot12_info.zsi" },
    { name: "Spot 13 - Haunted Wasteland", file: "spot13_info.zsi" },
    { name: "Spot 15 - Hyrule Castle", file: "spot15_info.zsi" },
    { name: "Spot 16 - Death Mountain Trail", file: "spot16_info.zsi" },
    { name: "Spot 17 - Death Mountain Crater", file: "spot17_info.zsi" },
    { name: "Spot 18 - Goron City", file: "spot18_info.zsi" },
    { name: "Spot 20 - Lon Lon Ranch", file: "spot20_info.zsi" },
    { name: "Spot 99 - Hyrule Field (Title)", file: "spot99_info.zsi" },
    { name: "Back Alley (Day)", file: "market_alley_info.zsi" },
    { name: "Back Alley (Night)", file: "market_alley_n_info.zsi" },
    { name: "Back Alley House (Dog Lady)", file: "kakariko_impa_info.zsi" },
    { name: "Back Alley House (Man in Green)", file: "kakariko_home3_info.zsi" },
    { name: "Barinade's Lair", file: "bdan_boss_info.zsi" },
    { name: "Bazaar", file: "shop_info.zsi" },
    { name: "Bombchu Bowling Alley", file: "bowling_info.zsi" },
    { name: "Bombchu Shop", file: "shop_night_info.zsi" },
    { name: "Bongo Bongo's Lair", file: "hakadan_boss_info.zsi" },
    { name: "Bottom of the Well", file: "hakadan_ch_info.zsi" },
    { name: "Carpenter Boss's House", file: "kakariko_info.zsi" },
    { name: "Carpenters' Tent", file: "tent_info.zsi" },
    { name: "Castle Courtyard", file: "nakaniwa_info.zsi" },
    { name: "Castle Hedge Maze (Day)", file: "hairal_niwa_info.zsi" },
    { name: "Castle Hedge Maze (Night)", file: "hairal_niwa_n_info.zsi" },
    { name: "Chamber of the Sages", file: "kenjyanoma_info.zsi" },
    { name: "Cutscene Map", file: "hiral_demo_info.zsi" },
    { name: "Dampe's Grave & Windmill", file: "hakasitarelay_info.zsi" },
    { name: "Dodongo's Cavern", file: "ddan_info.zsi" },
    { name: "Fairy's Fountain (Healing Fairies)", file: "yousei_izumi_tate_info.zsi" },
    { name: "Fire Temple", file: "hidan_info.zsi" },
    { name: "Fishing Pond", file: "turibori_info.zsi" },
    { name: "Forest Temple", file: "bmori1_info.zsi" },
    { name: "Ganon's Castle Exterior", file: "ganon_tou_info.zsi" },
    { name: "Ganon's Tower", file: "ganon_info.zsi" },
    { name: "Ganon's Tower (Collapsing)", file: "ganon_sonogo_info.zsi" },
    { name: "Ganon's Tower Exterior (Collapsing)", file: "ganon_final_info.zsi" },
    { name: "Ganon Battle Arena", file: "ganon_demo_info.zsi" },
    { name: "Ganondorf's Lair", file: "ganon_boss_info.zsi" },
    { name: "Gerudo Training Ground", file: "men_info.zsi" },
    { name: "Gohma's Lair", file: "ydan_boss_info.zsi" },
    { name: "Goron Shop", file: "shop_golon_info.zsi" },
    { name: "Granny's Potion Shop", file: "mahouya_info.zsi" },
    { name: "Grave (Fairy's Fountain)", file: "hakaana2_info.zsi" },
    { name: "Grave (Redead)", file: "hakaana_info.zsi" },
    { name: "Gravekeeper's Hut", file: "hut_info.zsi" },
    { name: "Great Fairy's Fountain (Spells)", file: "yousei_izumi_yoko_info.zsi" },
    { name: "Great Fairy's Fountain (Upgrades)", file: "daiyousei_izumi_info.zsi" },
    { name: "Grottos", file: "kakusiana_info.zsi" },
    { name: "Guard House", file: "miharigoya_info.zsi" },
    { name: "Happy Mask Shop", file: "shop_face_info.zsi" },
    { name: "House of Skulltula", file: "kinsuta_info.zsi" },
    { name: "Ice Cavern", file: "ice_doukutu_info.zsi" },
    { name: "Impa's House", file: "labo_info.zsi" },
    { name: "Inside Ganon's Castle", file: "ganontika_info.zsi" },
    { name: "Inside Ganon's Castle (Collapsing)", file: "ganontikasonogo_info.zsi" },
    { name: "Inside Jabu-Jabu's Belly", file: "bdan_info.zsi" },
    { name: "Inside the Deku Tree", file: "ydan_info.zsi" },
    { name: "Kakariko Potion Shop", file: "shop_drag_info.zsi" },
    { name: "King Dodongo's Lair", file: "ddan_boss_info.zsi" },
    { name: "Know-It-All Brothers' House", file: "k_home_info.zsi" },
    { name: "Kokiri Shop", file: "kokiri_info.zsi" },
    { name: "Lakeside Laboratory", file: "hylia_labo_info.zsi" },
    { name: "Link's House", file: "link_info.zsi" },
    { name: "Lon Lon Ranch House & Tower", file: "souko_info.zsi" },
    { name: "Market (Child - Day)", file: "market_day_info.zsi" },
    { name: "Market (Child - Night)", file: "market_night_info.zsi" },
    { name: "Market (Ruins)", file: "market_ruins_info.zsi" },
    { name: "Market Entrance (Child - Day)", file: "entra_day_info.zsi" },
    { name: "Market Entrance (Child - Night)", file: "entra_night_info.zsi" },
    { name: "Market Entrance (Ruins)", file: "entra_ruins_info.zsi" },
    { name: "Market Potion Shop", file: "shop_alley_info.zsi" },
    { name: "Mido's House", file: "k_home4_info.zsi" },
    { name: "Morpha's Lair", file: "mizusin_boss_info.zsi" },
    { name: "Phantom Ganon's Lair", file: "moriboss_info.zsi" },
    { name: "Royal Family's Tomb", file: "hakaana_ouke_info.zsi" },
    { name: "Saria's House", file: "k_home5_info.zsi" },
    { name: "Shadow Temple", file: "hakadan_info.zsi" },
    { name: "Shooting Gallery", file: "syatekijyou_info.zsi" },
    { name: "Spirit Temple", file: "jyasinzou_info.zsi" },
    { name: "Stable", file: "stable_info.zsi" },
    { name: "Temple of Time", file: "tokinoma_info.zsi" },
    { name: "Temple of Time Exterior (Day)", file: "shrine_info.zsi" },
    { name: "Temple of Time Exterior (Night)", file: "shrine_n_info.zsi" },
    { name: "Temple of Time Exterior (Ruins)", file: "shrine_r_info.zsi" },
    { name: "Thieves' Hideout", file: "gerudoway_info.zsi" },
    { name: "Treasure Chest Shop", file: "takaraya_info.zsi" },
    { name: "Twinrova's Lair", file: "jyasinzou_boss_info.zsi" },
    { name: "Twins' House", file: "k_home3_info.zsi" },
    { name: "Volvagia's Lair", file: "fire_bs_info.zsi" },
    { name: "Water Temple", file: "mizusin_info.zsi" },
    { name: "Zora Shop", file: "zoora_info.zsi" }
    //{ name: "Bottom of the Well (MQ)", file: "hakadan_ch_dd_info.zsi" },
    //{ name: "Dodongo's Cavern (MQ)", file: "ddan_dd_info.zsi" },
    //{ name: "Fire Temple (MQ)", file: "hidan_dd_info.zsi" },
    //{ name: "Forest Temple (MQ)", file: "bmori1_dd_info.zsi" },
    //{ name: "Gerudo Training Ground (MQ)", file: "men_dd_info.zsi" },
    //{ name: "Ice Cavern (MQ)", file: "ice_doukutu_dd_info.zsi" },
    //{ name: "Inside Ganon's Castle (MQ)", file: "ganontika_dd_info.zsi" },
    //{ name: "Inside Jabu-Jabu's Belly (MQ)", file: "bdan_dd_info.zsi" },
    //{ name: "Inside the Deku Tree (MQ)", file: "ydan_dd_info.zsi" },
    //{ name: "Shadow Temple (MQ)", file: "hakadan_dd_info.zsi" },
    //{ name: "Spirit Temple (MQ)", file: "jyasinzou_dd_info.zsi" },
    //{ name: "Water Temple (MQ)", file: "mizusin_dd_info.zsi" }
];

const MM3D_Maps = [
    { name: "Ancient Castle of Ikana", file: "z2_castle_info.zsi" },
    { name: "Astral Observatory", file: "z2_tenmon_dai_info.zsi" },
    { name: "Before the Portal to Termina", file: "z2_openingdan_info.zsi" },
    { name: "Beneath the Graves", file: "z2_hakashita_info.zsi" },
    { name: "Beneath the Well", file: "z2_redead_info.zsi" },
    { name: "Bomb Shop", file: "z2_bomya_info.zsi" },
    { name: "Clock Tower Interior", file: "z2_insidetower_info.zsi" },
    { name: "Clock Tower Rooftop", file: "z2_okujou_info.zsi" },
    { name: "Cucco Shack", file: "z2_f01c_info.zsi" },
    { name: "Curiosity Shop & Kafei's Hideout", file: "z2_ayashiishop_info.zsi" },
    { name: "Cutscene Map", file: "spot00_info.zsi" },
    { name: "Dampe's House", file: "z2_danpei2test_info.zsi" },
    { name: "Deku King's Chamber", file: "z2_deku_king_info.zsi" },
    { name: "Deku Palace", file: "z2_22dekucity_info.zsi" },
    { name: "Deku Scrub Playground", file: "z2_dekutes_info.zsi" },
    { name: "Deku Shrine", file: "z2_danpei_info.zsi" },
    { name: "Doggy Racetrack", file: "z2_f01_b_info.zsi" },
    { name: "East Clock Town", file: "z2_town_info.zsi" },
    { name: "Fairy's Fountain", file: "z2_yousei_izumi_info.zsi" },
    { name: "Fisherman's Hut", file: "z2_fisherman_info.zsi" },
    { name: "Ghost Hut", file: "z2_tougites_info.zsi" },
    { name: "Giants' Chamber", file: "z2_kyojinnoma_info.zsi" },
    { name: "Goht's Lair", file: "z2_hakugin_bs_info.zsi" },
    { name: "Gorman Track", file: "z2_koeponarace_info.zsi" },
    { name: "Goron Graveyard", file: "z2_goron_haka_info.zsi" },
    { name: "Goron Racetrack", file: "z2_goronrace_info.zsi" },
    { name: "Goron Shop", file: "z2_goronshop_info.zsi" },
    { name: "Goron Shrine", file: "z2_16goron_house_info.zsi" },
    { name: "Goron Village (Spring)", file: "z2_11goronnosato2_info.zsi" },
    { name: "Goron Village (Winter)", file: "z2_11goronnosato_info.zsi" },
    { name: "Great Bay Temple", file: "z2_sea_info.zsi" },
    { name: "Great Bay Coast", file: "z2_30gyoson_info.zsi" },
    { name: "Great Bay Coast (Cutscene)", file: "z2_konpeki_ent_info.zsi" },
    { name: "Grottos", file: "kakusiana_info.zsi" },
    { name: "Gyorg's Lair", file: "z2_sea_bs_info.zsi" },
    { name: "Honey & Darling's Shop", file: "z2_bowling_info.zsi" },
    { name: "Igos du Ikana's Lair", file: "z2_ikninside_info.zsi" },
    { name: "Ikana Canyon", file: "z2_ikana_info.zsi" },
    { name: "Ikana Graveyard", file: "z2_boti_info.zsi" },
    { name: "Laundry Pool", file: "z2_alley_info.zsi" },
    { name: "Lost Woods", file: "z2_lost_woods_info.zsi" },
    { name: "Lottery Shop", file: "z2_takarakuji_info.zsi" },
    { name: "Magic Hags' Potion Shop", file: "z2_witch_shop_info.zsi" },
    { name: "Majora's Lair", file: "z2_last_bs_info.zsi" },
    { name: "Marine Research Lab", file: "z2_labo_info.zsi" },
    { name: "Mayor's Residence", file: "z2_sonchonoie_info.zsi" },
    { name: "Milk Bar", file: "z2_milk_bar_info.zsi" },
    { name: "Milk Road", file: "z2_romanymae_info.zsi" },
    { name: "Mountain Smithy", file: "z2_kajiya_info.zsi" },
    { name: "Mountain Village (Spring)", file: "z2_10yukiyamanomura2_info.zsi" },
    { name: "Mountain Village (Winter)", file: "z2_10yukiyamanomura_info.zsi" },
    { name: "Music Box House", file: "z2_musichouse_info.zsi" },
    { name: "North Clock Town", file: "z2_backtown_info.zsi" },
    { name: "Ocean Fishing Hole", file: "z2_turibori2_info.zsi" },
    { name: "Oceanside Spider House", file: "z2_kindan2_info.zsi" },
    { name: "Odolwa's Lair", file: "z2_miturin_bs_info.zsi" },
    { name: "Path to Goron Village (Spring)", file: "z2_17setugen2_info.zsi" },
    { name: "Path to Goron Village (Winter)", file: "z2_17setugen_info.zsi" },
    { name: "Path to Mountain Village", file: "z2_13hubukinomiti_info.zsi" },
    { name: "Path to Snowhead", file: "z2_14yukidamanomiti_info.zsi" },
    { name: "Pinnacle Rock", file: "z2_sinkai_info.zsi" },
    { name: "Pirates' Fortress", file: "z2_kaizoku_info.zsi" },
    { name: "Pirates' Fortress Exterior", file: "z2_toride_info.zsi" },
    { name: "Pirates' Fortress Interior", file: "z2_pirate_info.zsi" },
    { name: "Post Office", file: "z2_posthouse_info.zsi" },
    { name: "Ranch House & Barn", file: "z2_omoya_info.zsi" },
    { name: "Road to Ikana", file: "z2_ikanamae_info.zsi" },
    { name: "Road to Southern Swamp", file: "z2_24kemonomiti_info.zsi" },
    { name: "Romani Ranch", file: "z2_f01_info.zsi" },
    { name: "Sakon's Hideout", file: "z2_secom_info.zsi" },
    { name: "Secret Shrine", file: "z2_random_info.zsi" },
    { name: "Snowhead", file: "z2_12hakuginmae_info.zsi" },
    { name: "Snowhead Temple", file: "z2_hakugin_info.zsi" },
    { name: "South Clock Town", file: "z2_clocktower_info.zsi" },
    { name: "Southern Swamp (Clear)", file: "z2_20sichitai2_info.zsi" },
    { name: "Southern Swamp (Poisoned)", file: "z2_20sichitai_info.zsi" },
    { name: "Stock Pot Inn", file: "z2_yadoya_info.zsi" },
    { name: "Stone Tower", file: "z2_f40_info.zsi" },
    { name: "Stone Tower (Inverted)", file: "z2_f41_info.zsi" },
    { name: "Stone Tower Temple", file: "z2_inisie_n_info.zsi" },
    { name: "Stone Tower Temple (Inverted)", file: "z2_inisie_r_info.zsi" },
    { name: "Swamp Fishing Hole", file: "z2_turibori_info.zsi" },
    { name: "Swamp Shooting Gallery", file: "z2_syateki_mori_info.zsi" },
    { name: "Swamp Spider House", file: "z2_kinsta1_info.zsi" },
    { name: "Swordsman's School", file: "z2_doujou_info.zsi" },
    { name: "Termina Field", file: "z2_00keikoku_info.zsi" },
    { name: "Termina Field (Credits Cutscene)", file: "z2_01keikoku_info.zsi" },
    { name: "Termina Field (Credits Cutscene 2)", file: "z2_02keikoku_info.zsi" },
    { name: "Test Map 01", file: "test01_info.zsi" },
    { name: "Test Map 02", file: "test02_info.zsi" },
    { name: "The Moon", file: "z2_sougen_info.zsi" },
    { name: "The Moon - Deku Trial", file: "z2_last_deku_info.zsi" },
    { name: "The Moon - Goron Trial", file: "z2_last_goron_info.zsi" },
    { name: "The Moon - Link Trial", file: "z2_last_link_info.zsi" },
    { name: "The Moon - Zora Trial", file: "z2_last_zora_info.zsi" },
    { name: "Tourist Information", file: "z2_map_shop_info.zsi" },
    { name: "Town Shooting Gallery", file: "z2_syateki_mizu_info.zsi" },
    { name: "Trading Post", file: "z2_8itemshop_info.zsi" },
    { name: "Treasure Chest Shop", file: "z2_takaraya_info.zsi" },
    { name: "Twinmold's Lair", file: "z2_inisie_bs_info.zsi" },
    { name: "Waterfall Rapids", file: "z2_35taki_info.zsi" },
    { name: "West Clock Town", file: "z2_ichiba_info.zsi" },
    { name: "Woodfall", file: "z2_21miturinmae_info.zsi" },
    { name: "Woodfall Temple", file: "z2_miturin_info.zsi" },
    { name: "Woods of Mystery", file: "z2_26sarunomori_info.zsi" },
    { name: "Zora Cape", file: "z2_31misaki_info.zsi" },
    { name: "Zora Hall", file: "z2_33zoracity_info.zsi" },
    { name: "Zora Hall Rooms", file: "z2_bandroom_info.zsi" },
    { name: "Zora Shop", file: "z2_zolashop_info.zsi" },
    { name: "32kamejimamae", file: "z2_32kamejimamae_info.zsi" },
    { name: "meganeana", file: "z2_meganeana_info.zsi" }
];

const flat_ground_clip_y_table = new Set([
    515, 519, 523, 527, 531, 535, 539, 543, 547, 551, 555, 559, 563, 567, 571, 575, 579, 583,
    587, 591, 595, 599, 603, 607, 611, 615, 619, 623, 627, 631, 635, 639, 643, 647, 651, 655,
    659, 663, 667, 671, 675, 679, 683, 687, 691, 695, 699, 703, 707, 711, 715, 719, 723, 727,
    731, 735, 739, 743, 747, 751, 755, 759, 763, 767, 771, 775, 779, 783, 787, 791, 795, 799,
    803, 807, 811, 815, 819, 823, 827, 831, 835, 839, 843, 847, 851, 855, 859, 863, 867, 871,
    875, 879, 883, 887, 891, 895, 899, 903, 907, 911, 915, 919, 923, 927, 931, 935, 939, 943,
    947, 951, 955, 959, 963, 967, 971, 975, 979, 983, 987, 991, 995, 999, 1003, 1007, 1011,
    1015, 1019, 1023, 1030, 1038, 1046, 1054, 1062, 1070, 1078, 1086, 1094, 1102, 1110, 1118,
    1126, 1134, 1142, 1150, 1158, 1166, 1174, 1182, 1190, 1198, 1206, 1214, 1222, 1230, 1238,
    1246, 1254, 1262, 1270, 1278, 1286, 1294, 1302, 1310, 1318, 1326, 1334, 1342, 1350, 1358,
    1366, 1374, 1382, 1390, 1398, 1406, 1414, 1422, 1430, 1438, 1446, 1454, 1462, 1470, 1478,
    1486, 1494, 1502, 1510, 1518, 1526, 1534, 1542, 1550, 1558, 1566, 1574, 1582, 1590, 1598,
    1606, 1614, 1622, 1630, 1638, 1646, 1654, 1662, 1670, 1678, 1686, 1694, 1702, 1710, 1718,
    1726, 1734, 1742, 1750, 1758, 1766, 1774, 1782, 1790, 1798, 1806, 1814, 1822, 1830, 1838,
    1846, 1854, 1862, 1870, 1878, 1886, 1894, 1902, 1910, 1918, 1926, 1934, 1942, 1950, 1958,
    1966, 1974, 1982, 1990, 1998, 2006, 2014, 2022, 2030, 2038, 2046, 2060, 2076, 2092, 2108,
    2124, 2140, 2156, 2172, 2188, 2204, 2220, 2236, 2252, 2268, 2284, 2300, 2316, 2332, 2348,
    2364, 2380, 2396, 2412, 2428, 2444, 2460, 2476, 2492, 2508, 2524, 2540, 2556, 2572, 2588,
    2604, 2620, 2636, 2652, 2668, 2684, 2700, 2716, 2732, 2748, 2764, 2780, 2796, 2812, 2828,
    2844, 2860, 2876, 2892, 2908, 2924, 2940, 2956, 2972, 2988, 3004, 3020, 3036, 3052, 3068,
    3084, 3100, 3116, 3132, 3148, 3164, 3180, 3196, 3212, 3228, 3244, 3260, 3276, 3292, 3308,
    3324, 3340, 3356, 3372, 3388, 3404, 3420, 3436, 3452, 3468, 3484, 3500, 3516, 3532, 3548,
    3564, 3580, 3596, 3612, 3628, 3644, 3660, 3676, 3692, 3708, 3724, 3740, 3756, 3772, 3788,
    3804, 3820, 3836, 3852, 3868, 3884, 3900, 3916, 3932, 3948, 3964, 3980, 3996, 4012, 4028,
    4044, 4060, 4076, 4092, 4120, 4152, 4184, 4216, 4248, 4280, 4312, 4344, 4376, 4408, 4440,
    4472, 4504, 4536, 4568, 4600, 4632, 4664, 4696, 4728, 4760, 4792, 4824, 4856, 4888, 4920,
    4952, 4984
]);
