const OOT_Actors = [
    { file_name: "gameplay_dangeon_keep", collision_name: "gPushBlockCol", offset: 0x4E98, type: "object" },
    { file_name: "gameplay_dangeon_keep", collision_name: "gFloorSwitchCol", offset: 0x5FB8, type: "object" },
    { file_name: "gameplay_field_keep", collision_name: "gBgBombwallCol", offset: 0x41B0, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gLargerCubeCol", offset: 0x39CE0, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gWideTallBlockCol", offset: 0x3A278, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gTallBlockCol", offset: 0x3A5F0, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gSmallerFlatBlockCol", offset: 0x3A950, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gLargerFlatBlockCol", offset: 0x3ACB0, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gSmallerCubeCol", offset: 0x3B020, type: "object" },
    //{ file_name: "gameplay_keep_pal", collision_name: "gLargerCubeCol", offset: 0x394B0, type: "object" },
    //{ file_name: "gameplay_keep_pal", collision_name: "gWideTallBlockCol", offset: 0x39A48, type: "object" },
    //{ file_name: "gameplay_keep_pal", collision_name: "gTallBlockCol", offset: 0x39DC0, type: "object" },
    //{ file_name: "gameplay_keep_pal", collision_name: "gSmallerFlatBlockCol", offset: 0x3A120, type: "object" },
    //{ file_name: "gameplay_keep_pal", collision_name: "gLargerFlatBlockCol", offset: 0x3A480, type: "object" },
    //{ file_name: "gameplay_keep_pal", collision_name: "gSmallerCubeCol", offset: 0x3A7F0, type: "object" },
    { file_name: "object_am", collision_name: "gArmosCol", offset: 0x118, type: "object" },
    { file_name: "object_bdan_objects", collision_name: "gJabuElevatorCol", offset: 0x5048, type: "object" },
    { file_name: "object_bdan_objects", collision_name: "gJabuLoweringPlatformCol", offset: 0x5580, type: "object" },
    { file_name: "object_bdan_objects", collision_name: "gJabuFloorSwitchCol", offset: 0x5CF8, type: "object" },
    { file_name: "object_bdan_objects", collision_name: "gJabuBigOctoPlatformCol", offset: 0x8CE0, type: "object" },
    { file_name: "object_blkobj", collision_name: "gIllusionRoomCol", offset: 0x7564, type: "object" },
    { file_name: "object_bowl", collision_name: "gBowlingFirstAndFinalRoundCol", offset: 0xCB8, type: "object" },
    { file_name: "object_bowl", collision_name: "gBowlingSecondRoundCol", offset: 0x1B00, type: "object" },
    { file_name: "object_bowl", collision_name: "gBowlingDefaultCol", offset: 0x1C40, type: "object" },
    { file_name: "object_box", collision_name: "gTreasureChestCol", offset: 0x5FC8, type: "object" },
    { file_name: "object_brob", collision_name: "gBrobCol", offset: 0x1A70, type: "object" },
    { file_name: "object_bwall", collision_name: "object_bwall_Col_000118", offset: 0x118, type: "object" },
    { file_name: "object_d_elevator", collision_name: "object_d_elevator_Col_000360", offset: 0x360, type: "object" },
    { file_name: "object_d_hsblock", collision_name: "gHookshotTargetCol", offset: 0x578, type: "object" },
    { file_name: "object_d_hsblock", collision_name: "gHookshotPostCol", offset: 0x730, type: "object" },
    { file_name: "object_d_lift", collision_name: "gCollapsingPlatformCol", offset: 0x3D0, type: "object" },
    { file_name: "object_ddan_objects", collision_name: "gDodongoLowerJawCol", offset: 0x1DDC, type: "object" },
    { file_name: "object_ddan_objects", collision_name: "gDodongoRisingPlatformCol", offset: 0x3CE0, type: "object" },
    { file_name: "object_ddan_objects", collision_name: "gDodongoFallingStairsCol", offset: 0x4F30, type: "object" },
    { file_name: "object_demo_kekkai", collision_name: "gClearBlockCol", offset: 0xC080, type: "object" },
    { file_name: "object_demo_kekkai", collision_name: "gFireTrialPlatformCol", offset: 0xECD8, type: "object" },
    { file_name: "object_demo_kekkai", collision_name: "gWaterTrialIceBlockCol", offset: 0x4618, type: "object" },
    { file_name: "object_door_gerudo", collision_name: "gGerudoCellDoorCol", offset: 0x170, type: "object" },
    { file_name: "object_fd", collision_name: "gVolvagiaPlatformCol", offset: 0xD68, type: "object" },
    //{ file_name: "object_fd_pal", collision_name: "gVolvagiaPlatformCol", offset: 0xD68, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubbleAroundArenaCol", offset: 0x1B70, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubble4Col", offset: 0x2850, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubble5Col", offset: 0x2D28, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubble6Col", offset: 0x2FE4, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubble7Col", offset: 0x33E0, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubble2Col", offset: 0x1F70, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubble3Col", offset: 0x2448, type: "object" },
    { file_name: "object_gj", collision_name: "gGanonsCastleRubbleTallCol", offset: 0x3AF0, type: "object" },
    { file_name: "object_gjyo_objects", collision_name: "gRainbowBridgeCol", offset: 0xDB8, type: "object" },
    { file_name: "object_gnd", collision_name: "gPhantomGanonBarsCol", offset: 0x12FD0, type: "object" },
    { file_name: "object_goma", collision_name: "gGohmaDoorCol", offset: 0x1D9D0, type: "object" },
    //{ file_name: "object_goma_pal", collision_name: "gGohmaDoorCol", offset: 0x1EDD0, type: "object" },
    { file_name: "object_gt", collision_name: "gTowerCollapseCsCollapsedStructureInnerCol", offset: 0x5CB8, type: "object" },
    { file_name: "object_gt", collision_name: "gTowerCollapseCsCollapsedStructureOuterCol", offset: 0x91E4, type: "object" },
    { file_name: "object_haka", collision_name: "gGravestoneCol", offset: 0x428, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_000118", offset: 0x118, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_004330", offset: 0x4330, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_0044D0", offset: 0x44D0, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_004780", offset: 0x4780, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_004940", offset: 0x4940, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_004B00", offset: 0x4B00, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_004CC0", offset: 0x4CC0, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_005334", offset: 0x5334, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_005E30", offset: 0x5E30, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_006F70", offset: 0x6F70, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_0081D0", offset: 0x81D0, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_008D10", offset: 0x8D10, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_009168", offset: 0x9168, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_009CD0", offset: 0x9CD0, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_00A7F4", offset: 0xA7F4, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_00A938", offset: 0xA938, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_00E408", offset: 0xE408, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_00ED7C", offset: 0xED7C, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_0108B8", offset: 0x108B8, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_010E10", offset: 0x10E10, type: "object" },
    { file_name: "object_haka_objects", collision_name: "object_haka_objects_Col_0131C4", offset: 0x131C4, type: "object" },
    { file_name: "object_hakach_objects", collision_name: "gBotwCoffinLidCol", offset: 0x0870, type: "object" },
    { file_name: "object_hakach_objects", collision_name: "gBotwBombSpotCol", offset: 0x0C2C, type: "object" },
    { file_name: "object_hakach_objects", collision_name: "gBotw1Col", offset: 0x1830, type: "object" },
    { file_name: "object_hakach_objects", collision_name: "gBotw2Col", offset: 0x1AB8, type: "object" },
    { file_name: "object_hata", collision_name: "gFlagpoleCol", offset: 0xC0, type: "object" },
    { file_name: "object_heavy_object", collision_name: "gHeavyBlockCol", offset: 0x169C, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleHammerableTotemCol", offset: 0xDA10, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleHookshotElevatorCol", offset: 0xE1E8, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStoneStep1Col", offset: 0xDE44, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStoneStep2Col", offset: 0xDD1C, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleMetalFenceWithSlantCol", offset: 0xE2CC, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleMetalFenceCol", offset: 0xE380, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleMetalFence2Col", offset: 0xE430, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleCrackedStoneFloorCol", offset: 0xD800, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleBombableWallCol", offset: 0xD878, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleLargeBombableWallCol", offset: 0xD8F8, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStoneBlock1Col", offset: 0xCB80, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStoneBlock2Col", offset: 0xDF78, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleSpinningFlamethrowerCol", offset: 0xD5C0, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStationaryFlamethrowerShortCol", offset: 0xCC90, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStationaryFlamethrowerTallCol", offset: 0xCDA0, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStonePlatform1Col", offset: 0x120E8, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleStonePlatform2Col", offset: 0xFAE8, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleFlareDancerPlatformCol", offset: 0xE568, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTempleTallestPillarAboveRoomBeforeBossCol", offset: 0xD054, type: "object" },
    { file_name: "object_hidan_objects", collision_name: "gFireTemplePillarInsertedInGroundCol", offset: 0xD188, type: "object" },
    { file_name: "object_ice_objects", collision_name: "object_ice_objects_Col_0003F0", offset: 0x3F0, type: "object" },
    { file_name: "object_ice_objects", collision_name: "gRedIcePlatformCol", offset: 0x1C1C, type: "object" },
    { file_name: "object_ice_objects", collision_name: "object_ice_objects_Col_002594", offset: 0x2594, type: "object" },
    { file_name: "object_ice_objects", collision_name: "object_ice_objects_Col_002854", offset: 0x2854, type: "object" },
    { file_name: "object_ice_objects", collision_name: "gRedIceWallCol", offset: 0x2920, type: "object" },
    { file_name: "object_ingate", collision_name: "gIngoGateCol", offset: 0x11B8, type: "object" },
    { file_name: "object_jj", collision_name: "gJabuJabuHeadCol", offset: 0x0A1C, type: "object" },
    { file_name: "object_jj", collision_name: "gJabuJabuBodyCol", offset: 0x1830, type: "object" },
    { file_name: "object_jj", collision_name: "gJabuJabuUnusedCol", offset: 0xBA8C, type: "object" },
    { file_name: "object_js", collision_name: "gCarpetMerchantCol", offset: 0x5EF8, type: "object" },
    { file_name: "object_jya_iron", collision_name: "gPillarCol", offset: 0x0D48, type: "object" },
    { file_name: "object_jya_iron", collision_name: "gThroneCol", offset: 0x1430, type: "object" },
    { file_name: "object_jya_obj", collision_name: "g1fliftCol", offset: 0x4A8, type: "object" },
    { file_name: "object_jya_obj", collision_name: "gAmishutterCol", offset: 0xC4C8, type: "object" },
    { file_name: "object_jya_obj", collision_name: "gBombiwaCol", offset: 0xE710, type: "object" },
    { file_name: "object_jya_obj", collision_name: "gCobraCol", offset: 0x1167C, type: "object" },
    { file_name: "object_jya_obj", collision_name: "gKanaamiCol", offset: 0xF208, type: "object" },
    { file_name: "object_jya_obj", collision_name: "gLiftCol", offset: 0xD7E8, type: "object" },
    { file_name: "object_jya_obj", collision_name: "GMegamiCol", offset: 0x5C4C, type: "object" },
    { file_name: "object_jya_obj", collision_name: "gZurerukabeCol", offset: 0x12508, type: "object" },
    { file_name: "object_kibako2", collision_name: "gLargeCrateCol", offset: 0xB70, type: "object" },
    { file_name: "object_kingdodongo", collision_name: "object_kingdodongo_Col_025B64", offset: 0x24764, type: "object" },
    { file_name: "object_kingdodongo", collision_name: "object_kingdodongo_Col_0264A8", offset: 0x250A8, type: "object" },
    //{ file_name: "object_kingdodongo_pal", collision_name: "object_kingdodongo_Col_025B64", offset: 0x25B64, type: "object" },
    //{ file_name: "object_kingdodongo_pal", collision_name: "object_kingdodongo_Col_0264A8", offset: 0x264A8, type: "object" },
    { file_name: "object_lightbox", collision_name: "object_lightbox_Col_0003A0", offset: 0x3A0, type: "object" },
    { file_name: "object_lightbox", collision_name: "object_lightbox_Col_000770", offset: 0x770, type: "object" },
    { file_name: "object_lightbox", collision_name: "object_lightbox_Col_000B40", offset: 0xB40, type: "object" },
    { file_name: "object_lightbox", collision_name: "object_lightbox_Col_001F10", offset: 0x1F10, type: "object" },
    { file_name: "object_mamenoki", collision_name: "gMagicBeanPlatformCol", offset: 0x5DC, type: "object" },
    { file_name: "object_menkuri_objects", collision_name: "gGTGRotatingRingPlatformCol", offset: 0x42D8, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gWaterTempleFloatingPlatformOutsideCentralPillarCol", offset: 0x03F0, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gWaterTempleFloatingPlatformWestCol", offset: 0x0998, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gWaterTempleFloatingPlatformInsideCentralPillarCol", offset: 0x0ED0, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gWaterTempleHookshotPlatformCol", offset: 0x15F8, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gWaterTempleDragonStatueCol", offset: 0x3590, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gObjectMizuObjectsBwallCol_001C58", offset: 0x1C58, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gObjectMizuObjectsBwallCol_001DE8", offset: 0x1DE8, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gObjectMizuObjectsBwallCol_0025A4", offset: 0x25A4, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gObjectMizuObjectsShutterCol_007250", offset: 0x7250, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gObjectMizuObjectsShutterCol_0073F0", offset: 0x73F0, type: "object" },
    { file_name: "object_mizu_objects", collision_name: "gObjectMizuObjectsUzuCol_0074EC", offset: 0x74EC, type: "object" },
    { file_name: "object_mjin", collision_name: "gWarpPadCol", offset: 0x658, type: "object" },
    { file_name: "object_mjin_oka", collision_name: "gOcarinaWarpPadCol", offset: 0x330, type: "object" },
    { file_name: "object_mori_hineri1", collision_name: "object_mori_hineri1_Col_0054B8", offset: 0x54B8, type: "object" },
    { file_name: "object_mori_hineri1a", collision_name: "object_mori_hineri1a_Col_003490", offset: 0x3490, type: "object" },
    { file_name: "object_mori_hineri2", collision_name: "object_mori_hineri2_Col_0043D0", offset: 0x43D0, type: "object" },
    { file_name: "object_mori_hineri2a", collision_name: "object_mori_hineri2a_Col_006078", offset: 0x6078, type: "object" },
    { file_name: "object_mori_objects", collision_name: "gMoriBigstCol", offset: 0x221C, type: "object" },
    { file_name: "object_mori_objects", collision_name: "gMoriElevatorCol", offset: 0x35F8, type: "object" },
    { file_name: "object_mori_objects", collision_name: "gMoriHashigoCol", offset: 0x37D8, type: "object" },
    { file_name: "object_mori_objects", collision_name: "gMoriHashira1Col", offset: 0x1AF8, type: "object" },
    { file_name: "object_mori_objects", collision_name: "gMoriHashira2Col", offset: 0x89E0, type: "object" },
    { file_name: "object_mori_objects", collision_name: "gMoriKaitenkabeCol", offset: 0x63B8, type: "object" },
    { file_name: "object_mori_objects", collision_name: "gMoriRakkatenjoCol", offset: 0x87AC, type: "object" },
    { file_name: "object_po_sisters", collision_name: "gPoSistersAmyBlockCol", offset: 0x7860, type: "object" },
    { file_name: "object_ps", collision_name: "gPoeSellerCol", offset: 0xC2D0, type: "object" },
    { file_name: "object_pu_box", collision_name: "gBlockSmallCol", offset: 0x350, type: "object" },
    { file_name: "object_pu_box", collision_name: "gBlockMediumCol", offset: 0x6D0, type: "object" },
    { file_name: "object_pu_box", collision_name: "gBlockTallCol", offset: 0xA50, type: "object" },
    { file_name: "object_pu_box", collision_name: "gBlockTallestCol", offset: 0x15D0, type: "object" },
    { file_name: "object_relay_objects", collision_name: "gDampeRaceDoorCol", offset: 0x3C4, type: "object" },
    { file_name: "object_relay_objects", collision_name: "gWindmillRotatingPlatformCol", offset: 0x25FC, type: "object" },
    { file_name: "object_siofuki", collision_name: "object_siofuki_Col_000D78", offset: 0xD78, type: "object" },
    { file_name: "object_spot00_break", collision_name: "gBrokenDrawbridgeCol", offset: 0x908, type: "object" },
    { file_name: "object_spot00_break", collision_name: "gBarbedWireFenceCol", offset: 0xAF0, type: "object" },
    { file_name: "object_spot00_objects", collision_name: "gHyruleFieldCastleDrawbridgeCol", offset: 0x05E0, type: "object" },
    { file_name: "object_spot00_objects", collision_name: "gHyruleFieldCastleDrawbridgeChainsCol", offset: 0x0280, type: "object" },
    { file_name: "object_spot01_matoya", collision_name: "gKakarikoShootingGalleryCol", offset: 0x1A38, type: "object" },
    { file_name: "object_spot01_matoya", collision_name: "gKakarikoBOTWStoneCol", offset: 0x3C64, type: "object" },
    { file_name: "object_spot01_matoyab", collision_name: "object_spot01_matoyab_col", offset: 0x1C58, type: "object" },
    { file_name: "object_spot01_matoyab", collision_name: "gKakarikoGuardGateCol", offset: 0x1DA8, type: "object" },
    { file_name: "object_spot01_objects", collision_name: "gKakarikoWellArchCol", offset: 0x075C, type: "object" },
    { file_name: "object_spot02_objects", collision_name: "object_spot02_objects_Col_0128D8", offset: 0x128D8, type: "object" },
    { file_name: "object_spot02_objects", collision_name: "object_spot02_objects_Col_012BA4", offset: 0x12BA4, type: "object" },
    { file_name: "object_spot02_objects", collision_name: "object_spot02_objects_Col_0133EC", offset: 0x133EC, type: "object" },
    { file_name: "object_spot03_object", collision_name: "object_spot03_object_Col_000C98", offset: 0xC98, type: "object" },
    { file_name: "object_spot04_objects", collision_name: "gDekuTreeMouthCol", offset: 0x0E94, type: "object" },
    { file_name: "object_spot05_objects", collision_name: "object_spot05_objects_Col_000918", offset: 0x918, type: "object" },
    { file_name: "object_spot05_objects", collision_name: "object_spot05_objects_Col_0012C0", offset: 0x12C0, type: "object" },
    { file_name: "object_spot06_objects", collision_name: "gLakeHyliaWaterTempleGateCol", offset: 0x0EE8, type: "object" },
    { file_name: "object_spot06_objects", collision_name: "gLakeHyliaZoraShortcutIceblockCol", offset: 0x1238, type: "object" },
    { file_name: "object_spot07_object", collision_name: "object_spot07_object_Col_002590", offset: 0x2590, type: "object" },
    { file_name: "object_spot07_object", collision_name: "object_spot07_object_Col_0038FC", offset: 0x38FC, type: "object" },
    { file_name: "object_spot08_obj", collision_name: "gZorasFountainIceRampCol", offset: 0x1904, type: "object" },
    { file_name: "object_spot08_obj", collision_name: "gZorasFountainIcebergCol", offset: 0x2FD8, type: "object" },
    { file_name: "object_spot08_obj", collision_name: "gZorasFountainBombableWallCol", offset: 0x39D4, type: "object" },
    { file_name: "object_spot09_obj", collision_name: "gValleyObjects1Col", offset: 0x5520, type: "object" },
    { file_name: "object_spot09_obj", collision_name: "gValleyObjects2Col", offset: 0x283C, type: "object" },
    { file_name: "object_spot09_obj", collision_name: "gValleyObjects3Col", offset: 0x8458, type: "object" },
    { file_name: "object_spot09_obj", collision_name: "gValleyObjects4Col", offset: 0x7580, type: "object" },
    { file_name: "object_spot11_obj", collision_name: "gDesertColossusBombableWallCol", offset: 0x1A58, type: "object" },
    { file_name: "object_spot12_obj", collision_name: "gGerudoFortressWastelandGateCol", offset: 0x11EC, type: "object" },
    { file_name: "object_spot12_obj", collision_name: "gGerudoFortressGTGShutterCol", offset: 0x238C, type: "object" },
    { file_name: "object_spot15_obj", collision_name: "gLonLonMilkCrateCol", offset: 0x348, type: "object" },
    { file_name: "object_spot15_obj", collision_name: "gLonLonCorralFenceCol", offset: 0x4D0, type: "object" },
    { file_name: "object_spot17_obj", collision_name: "gCraterBombableWallCol", offset: 0xA38, type: "object" },
    { file_name: "object_spot18_obj", collision_name: "gGoronCityVaseLidCol", offset: 0x368, type: "object" },
    { file_name: "object_spot18_obj", collision_name: "gGoronCityDoorCol", offset: 0x534, type: "object" },
    { file_name: "object_spot18_obj", collision_name: "gGoronCityVaseCol", offset: 0x2154, type: "object" },
    { file_name: "object_spot18_obj", collision_name: "gGoronCityStatueSpearCol", offset: 0x261C, type: "object" },
    { file_name: "object_spot18_obj", collision_name: "gGoronCityStatueCol", offset: 0x2FE4, type: "object" },
    { file_name: "object_sst", collision_name: "gBongoDrumCol", offset: 0x180F8, type: "object" },
    //{ file_name: "object_sst_pal", collision_name: "gBongoDrumCol", offset: 0x194F8, type: "object" },
    { file_name: "object_timeblock", collision_name: "gSongOfTimeBlockCol", offset: 0xB30, type: "object" },
    { file_name: "object_toki_objects", collision_name: "gDoorTokiCol", offset: 0x7888, type: "object" },
    { file_name: "object_umajump", collision_name: "gJumpableHorseFenceCol", offset: 0x1438, type: "object" },
    { file_name: "object_wood02", collision_name: "object_wood02_Col_007A70", offset: 0x7A70, type: "object" },
    { file_name: "object_ydan_objects", collision_name: "gDTRisingPlatformsCol", offset: 0x5780, type: "object" },
    { file_name: "object_ydan_objects", collision_name: "gDTWebWallCol", offset: 0x6050, type: "object" },
    { file_name: "object_ydan_objects", collision_name: "gDTWebFloorCol", offset: 0x6460, type: "object" },
    { file_name: "object_ydan_objects", collision_name: "gDTFallingLadderCol", offset: 0x66A8, type: "object" },
    { file_name: "object_ydan_objects", collision_name: "gDTSlidingPlatformCol", offset: 0x7798, type: "object" },
    { file_name: "object_zg", collision_name: "gTowerCollapseBarsCol", offset: 0x11D4, type: "object" },
    { file_name: "ovl_Bg_Ganon_Otyuka", collision_name: "sCol", offset: 0x13B0 , type: "overlay" },
    { file_name: "ovl_En_Jsjutan", collision_name: "sCol", offset: 0x3968 , type: "overlay" },
];

const OOT_Actors2 = [
    { actor_name: "Obj_Oshihiki", actor_description: "Push Block", collision_name: "gPushBlockCol", params_mask: null, params_values: null },
    { actor_name: "Bg_Jya_Block", actor_description: "Silver Block (Child Link)", collision_name: "gPushBlockCol", params_mask: null, params_values: null },
    { actor_name: "Obj_Switch", actor_description: "Floor Switch", collision_name: "gFloorSwitchCol", params_mask: 0x0007, params_values: [0, 1] },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null }
];

const MM_Actors = [
    { file_name: "gameplay_dangeon_keep", collision_name: "gameplay_dangeon_keep_Colheader_007498", offset: 0x7498, type: "object" },
    { file_name: "gameplay_dangeon_keep", collision_name: "gFloorSwitchCol", offset: 0x8018, type: "object" },
    { file_name: "gameplay_dangeon_keep", collision_name: "gameplay_dangeon_keep_Colheader_01D488", offset: 0x1D488, type: "object" },
    { file_name: "gameplay_dangeon_keep", collision_name: "gWarpTagGoronTrialBaseCol", offset: 0x2324C, type: "object" },
    { file_name: "gameplay_field_keep", collision_name: "gameplay_field_keep_Colheader_003A60", offset: 0x3A60, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gPinkDekuFlowerCol", offset: 0xE710, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gGoldDekuFlowerCol", offset: 0x118D8, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gFramedDoorCol", offset: 0x23100, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gameplay_keep_Colheader_058F30", offset: 0x58F30, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gameplay_keep_Colheader_0594C8", offset: 0x594C8, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gameplay_keep_Colheader_059840", offset: 0x59840, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gameplay_keep_Colheader_059BA0", offset: 0x59BA0, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gameplay_keep_Colheader_059F00", offset: 0x59F00, type: "object" },
    { file_name: "gameplay_keep", collision_name: "gameplay_keep_Colheader_05A270", offset: 0x5A270, type: "object" },
    { file_name: "object_am", collision_name: "object_am_Colheader_000118", offset: 0x118, type: "object" },
    { file_name: "object_am", collision_name: "object_am_Colheader_005CF8", offset: 0x5CF8, type: "object" },
    { file_name: "object_astr_obj", collision_name: "object_astr_obj_Colheader_002498", offset: 0x2498, type: "object" },
    { file_name: "object_botihasira", collision_name: "object_botihasira_Colheader_001BD8", offset: 0x1BD8, type: "object" },
    { file_name: "object_box", collision_name: "gBoxChestCol", offset: 0x80E8, type: "object" },
    { file_name: "object_crace_object", collision_name: "gDekuShrineSlidingDoorCol", offset: 0xE00, type: "object" },
    { file_name: "object_ctower_rot", collision_name: "gClockTowerCorridorCol", offset: 0x142E8, type: "object" },
    { file_name: "object_ctower_rot", collision_name: "gClockTowerOrganCol", offset: 0x16E70, type: "object" },
    { file_name: "object_ctower_rot", collision_name: "gClockTowerStoneDoorMainCol", offset: 0x17410, type: "object" },
    { file_name: "object_ctower_rot", collision_name: "gClockTowerStoneDoorCol", offset: 0x17650, type: "object" },
    { file_name: "object_ctower_rot", collision_name: "gClockTowerWaterWheelCol", offset: 0x18588, type: "object" },
    { file_name: "object_d_hsblock", collision_name: "gHookshotTargetCol", offset: 0x578, type: "object" },
    { file_name: "object_d_hsblock", collision_name: "gHookshotPostCol", offset: 0x730, type: "object" },
    { file_name: "object_d_lift", collision_name: "object_d_lift_Colheader_000BA0", offset: 0xBA0, type: "object" },
    { file_name: "object_d_lift", collision_name: "gDampeGraveBrownElevatorCol", offset: 0xF00, type: "object" },
    { file_name: "object_danpei_object", collision_name: "object_danpei_object_Colheader_000D60", offset: 0xD60, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectElevatorCol", offset: 0x5C4, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectWaterwheelWithPlatformsCol", offset: 0x2E78, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectIceStalactiteCol", offset: 0x3540, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectGearShaftWithPlatformsCol", offset: 0x5D28, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectTwoWaySwitchCol", offset: 0x6EA8, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectOneWaySwitchCol", offset: 0x714C, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectWaterwheelCol", offset: 0xAED0, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectSeesawShaftCol", offset: 0xBC08, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectLargeSeesawPlatformCol", offset: 0xC180, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectSmallSeesawPlatformCol", offset: 0xC700, type: "object" },
    { file_name: "object_dblue_object", collision_name: "gGreatBayTempleObjectUnusedCol", offset: 0xD3DC, type: "object" },
    { file_name: "object_dekucity_obj", collision_name: "object_dekucity_obj_Colheader_0002AC", offset: 0x2AC, type: "object" },
    { file_name: "object_dhouse", collision_name: "object_dhouse_Colheader_008040", offset: 0x8040, type: "object" },
    { file_name: "object_dkjail_obj", collision_name: "gDkjailCol", offset: 0x11A8, type: "object" },
    { file_name: "object_driftice", collision_name: "object_driftice_Colheader_001AA8", offset: 0x1AA8, type: "object" },
    { file_name: "object_eg", collision_name: "gEyegoreBlockCol", offset: 0x1820, type: "object" },
    { file_name: "object_f40_obj", collision_name: "gStoneTowerVerticallyOscillatingPlatformCol", offset: 0x3E80, type: "object" },
    { file_name: "object_f40_obj", collision_name: "gStoneTowerTempleSquareElevatorCol", offset: 0x4240, type: "object" },
    { file_name: "object_f40_obj", collision_name: "gStoneTowerBlockCol", offset: 0x4640, type: "object" },
    { file_name: "object_f40_switch", collision_name: "gStoneTowerFloorSwitchCol", offset: 0x118, type: "object" },
    { file_name: "object_f52_obj", collision_name: "object_f52_obj_Colheader_001BA8", offset: 0x1BA8, type: "object" },
    { file_name: "object_fu_kaiten", collision_name: "object_fu_kaiten_Colheader_002D30", offset: 0x2D30, type: "object" },
    { file_name: "object_fu_kaiten", collision_name: "object_fu_kaiten_Colheader_0037F8", offset: 0x37F8, type: "object" },
    { file_name: "object_fu_mato", collision_name: "object_fu_mato_Colheader_0015C0", offset: 0x15C0, type: "object" },
    { file_name: "object_fu_mato", collision_name: "object_fu_mato_Colheader_0023D4", offset: 0x23D4, type: "object" },
    { file_name: "object_fusen", collision_name: "object_fusen_Colheader_002420", offset: 0x2420, type: "object" },
    { file_name: "object_ghaka", collision_name: "object_ghaka_Colheader_0000E8", offset: 0xE8, type: "object" },
    { file_name: "object_ghaka", collision_name: "object_ghaka_Colheader_003CD0", offset: 0x3CD0, type: "object" },
    { file_name: "object_goronswitch", collision_name: "object_goronswitch_Colheader_0005C8", offset: 0x5C8, type: "object" },
    { file_name: "object_haka_obj", collision_name: "object_haka_obj_Colheader_000148", offset: 0x148, type: "object" },
    { file_name: "object_haka_obj", collision_name: "object_haka_obj_Colheader_000EE8", offset: 0xEE8, type: "object" },
    { file_name: "object_haka_obj", collision_name: "object_haka_obj_Colheader_001588", offset: 0x1588, type: "object" },
    { file_name: "object_hakaisi", collision_name: "object_hakaisi_Colheader_002FC4", offset: 0x2FC4, type: "object" },
    { file_name: "object_hakugin_obj", collision_name: "object_hakugin_obj_Colheader_009768", offset: 0x9768, type: "object" },
    { file_name: "object_hakugin_obj", collision_name: "object_hakugin_obj_Colheader_009AF0", offset: 0x9AF0, type: "object" },
    { file_name: "object_hakugin_obj", collision_name: "object_hakugin_obj_Colheader_00BF40", offset: 0xBF40, type: "object" },
    { file_name: "object_hakugin_obj", collision_name: "object_hakugin_obj_Colheader_00D3B0", offset: 0xD3B0, type: "object" },
    { file_name: "object_hanareyama_obj", collision_name: "object_hanareyama_obj_Colheader_004D8C", offset: 0x4D8C, type: "object" },
    { file_name: "object_hata", collision_name: "gFlagpoleCol", offset: 0xC0, type: "object" },
    { file_name: "object_hgdoor", collision_name: "object_hgdoor_Colheader_0018C0", offset: 0x18C0, type: "object" },
    { file_name: "object_hgdoor", collision_name: "object_hgdoor_Colheader_001D10", offset: 0x1D10, type: "object" },
    { file_name: "object_horse_game_check", collision_name: "object_horse_game_check_Colheader_002FB8", offset: 0x2FB8, type: "object" },
    { file_name: "object_horse_game_check", collision_name: "object_horse_game_check_Colheader_003918", offset: 0x3918, type: "object" },
    { file_name: "object_hsstump", collision_name: "object_hsstump_Colheader_0011B0", offset: 0x11B0, type: "object" },
    { file_name: "object_hunsui", collision_name: "object_hunsui_Colheader_000C74", offset: 0xC74, type: "object" },
    { file_name: "object_hunsui", collision_name: "object_hunsui_Colheader_00190C", offset: 0x190C, type: "object" },
    { file_name: "object_ice_block", collision_name: "gIceBlockCol", offset: 0x438, type: "object" },
    { file_name: "object_icefloe", collision_name: "gIcefloePlatformCol", offset: 0xC90, type: "object" },
    { file_name: "object_icicle", collision_name: "gIcicleCol", offset: 0x294, type: "object" },
    { file_name: "object_ikana_obj", collision_name: "object_ikana_obj_Colheader_000128", offset: 0x128, type: "object" },
    { file_name: "object_ikana_obj", collision_name: "object_ikana_obj_Colheader_000488", offset: 0x488, type: "object" },
    { file_name: "object_ikana_obj", collision_name: "gStoneTowerTemplePunchablePillarCol", offset: 0xC50, type: "object" },
    { file_name: "object_ikana_obj", collision_name: "object_ikana_obj_Colheader_000F28", offset: 0xF28, type: "object" },
    { file_name: "object_ikana_obj", collision_name: "gStoneTowerTempleMirrorCol", offset: 0x2358, type: "object" },
    { file_name: "object_ikana_obj", collision_name: "object_ikana_obj_Colheader_006368", offset: 0x6368, type: "object" },
    { file_name: "object_ikana_obj", collision_name: "object_ikana_obj_Colheader_0084F8", offset: 0x84F8, type: "object" },
    { file_name: "object_ikninside_obj", collision_name: "object_ikninside_obj_Colheader_00CBAC", offset: 0xCBAC, type: "object" },
    { file_name: "object_ikninside_obj", collision_name: "object_ikninside_obj_Colheader_00DE48", offset: 0xDE48, type: "object" },
    { file_name: "object_iknv_obj", collision_name: "object_iknv_obj_Colheader_0117C8", offset: 0x117C8, type: "object" },
    { file_name: "object_iknv_obj", collision_name: "object_iknv_obj_Colheader_0119D4", offset: 0x119D4, type: "object" },
    { file_name: "object_iknv_obj", collision_name: "object_iknv_obj_Colheader_012788", offset: 0x12788, type: "object" },
    { file_name: "object_iknv_obj", collision_name: "object_iknv_obj_Colheader_012CA4", offset: 0x12CA4, type: "object" },
    { file_name: "object_inibs_object", collision_name: "gTwinmoldArenaGiantModeArenaCol", offset: 0x4BA0, type: "object" },
    { file_name: "object_inibs_object", collision_name: "gTwinmoldArenaNormalModeArenaCol", offset: 0x8EF4, type: "object" },
    { file_name: "object_inibs_object", collision_name: "gTwinmoldArenaUnusedTwistedPillarCol", offset: 0x930C, type: "object" },
    { file_name: "object_inibs_object", collision_name: "gTwinmoldArenaUnusedTrapezoidalPillarCol", offset: 0x9600, type: "object" },
    { file_name: "object_inibs_object", collision_name: "gTwinmoldArenaUnusedClawShapedPillarCol", offset: 0x9EA8, type: "object" },
    { file_name: "object_inibs_object", collision_name: "gTwinmoldArenaUnusedWallCol", offset: 0xA200, type: "object" },
    { file_name: "object_inibs_object", collision_name: "gTwinmoldArenaUnusedWallCornerCol", offset: 0xA6A8, type: "object" },
    { file_name: "object_js", collision_name: "object_js_Colheader_0069E8", offset: 0x69E8, type: "object" },
    { file_name: "object_kaizoku_obj", collision_name: "gPirateLiftPlatformCol", offset: 0x19B0, type: "object" },
    { file_name: "object_kaizoku_obj", collision_name: "gPirateBarredShutterCol", offset: 0x35B0, type: "object" },
    { file_name: "object_kaizoku_obj", collision_name: "gPirateGratedShutterCol", offset: 0x5EC8, type: "object" },
    { file_name: "object_kaizoku_obj", collision_name: "object_kaizoku_obj_Colheader_009A88", offset: 0x9A88, type: "object" },
    { file_name: "object_kaizoku_obj", collision_name: "object_kaizoku_obj_Colheader_00B868", offset: 0xB868, type: "object" },
    { file_name: "object_kamejima", collision_name: "gTurtleZoraCapeAsleepCol", offset: 0x2328, type: "object" },
    { file_name: "object_kamejima", collision_name: "gTurtleZoraCapeAwakeCol", offset: 0x2470, type: "object" },
    { file_name: "object_kamejima", collision_name: "gTurtleUnusedCol", offset: 0x2E04, type: "object" },
    { file_name: "object_keikoku_demo", collision_name: "gKeikokuDemoFloorCol", offset: 0x1C98, type: "object" },
    { file_name: "object_keikoku_obj", collision_name: "object_keikoku_obj_Colheader_002300", offset: 0x2300, type: "object" },
    { file_name: "object_kepn_koya", collision_name: "object_kepn_koya_Colheader_00805C", offset: 0x805C, type: "object" },
    { file_name: "object_kibako2", collision_name: "gLargeCrateCol", offset: 0xB70, type: "object" },
    { file_name: "object_kin2_obj", collision_name: "gOceanSpiderHouseBombableWallCol", offset: 0x490, type: "object" },
    { file_name: "object_kin2_obj", collision_name: "gOceanSpiderHouseSkullkidPaintingCol", offset: 0x798, type: "object" },
    { file_name: "object_kin2_obj", collision_name: "gOceanSpiderHouseFireplaceGrateCol", offset: 0x908, type: "object" },
    { file_name: "object_kin2_obj", collision_name: "gOceanSpiderHouseBookshelfCol", offset: 0xF80, type: "object" },
    { file_name: "object_kin2_obj", collision_name: "gOceanSpiderHouseChestOfDrawersCol", offset: 0x1328, type: "object" },
    { file_name: "object_kzsaku", collision_name: "gUnderwaterGrateCol", offset: 0x1118, type: "object" },
    { file_name: "object_ladder", collision_name: "gWoodenLadder12RungCol", offset: 0x1D8, type: "object" },
    { file_name: "object_ladder", collision_name: "gWoodenLadder16RungCol", offset: 0x408, type: "object" },
    { file_name: "object_ladder", collision_name: "gWoodenLadder20RungCol", offset: 0x638, type: "object" },
    { file_name: "object_ladder", collision_name: "gWoodenLadder24RungCol", offset: 0x868, type: "object" },
    { file_name: "object_last_obj", collision_name: "object_last_obj_Colheader_000288", offset: 0x288, type: "object" },
    { file_name: "object_last_obj", collision_name: "object_last_obj_Colheader_001450", offset: 0x1450, type: "object" },
    { file_name: "object_lbfshot", collision_name: "object_lbfshot_Colheader_0014D8", offset: 0x14D8, type: "object" },
    { file_name: "object_lightblock", collision_name: "gSunBlockCol", offset: 0xB80, type: "object" },
    { file_name: "object_lotus", collision_name: "gLilyPadCol", offset: 0xA20, type: "object" },
    { file_name: "object_mamenoki", collision_name: "object_mamenoki_Colheader_0004BC", offset: 0x4BC, type: "object" },
    { file_name: "object_mbar_obj", collision_name: "object_mbar_obj_Colheader_0019B4", offset: 0x19B4, type: "object" },
    { file_name: "object_milkbar", collision_name: "object_milkbar_Colheader_006688", offset: 0x6688, type: "object" },
    { file_name: "object_mnk", collision_name: "object_mnk_Colheader_0033E8", offset: 0x33E8, type: "object" },
    { file_name: "object_mtoride", collision_name: "gWoodfallSceneryPoisonWaterDamageCol", offset: 0x9E4C, type: "object" },
    { file_name: "object_mtoride", collision_name: "gWoodfallSceneryTempleRampAndPlatformCol", offset: 0xFE5C, type: "object" },
    { file_name: "object_mtoride", collision_name: "gWoodfallSceneryTempleCol", offset: 0x10C3C, type: "object" },
    { file_name: "object_numa_obj", collision_name: "gWoodenFlowerOpenedFlowerCol", offset: 0x9FE0, type: "object" },
    { file_name: "object_numa_obj", collision_name: "gWoodenFlowerClosedFlowerCol", offset: 0xA740, type: "object" },
    { file_name: "object_numa_obj", collision_name: "object_numa_obj_Colheader_012818", offset: 0x12818, type: "object" },
    { file_name: "object_obj_danpeilift", collision_name: "object_obj_danpeilift_Colheader_000BA0", offset: 0xBA0, type: "object" },
    { file_name: "object_obj_usiyane", collision_name: "object_obj_usiyane_Colheader_0022AC", offset: 0x22AC, type: "object" },
    { file_name: "object_obj_yasi", collision_name: "gPalmTreeCol", offset: 0x1428, type: "object" },
    { file_name: "object_open_obj", collision_name: "object_open_obj_Colheader_001640", offset: 0x1640, type: "object" },
    { file_name: "object_oyu", collision_name: "gGoronGraveyardHotSpringWaterCol", offset: 0x988, type: "object" },
    { file_name: "object_posthouse_obj", collision_name: "object_posthouse_obj_Colheader_002948", offset: 0x2948, type: "object" },
    { file_name: "object_ps", collision_name: "object_ps_Colheader_0072E0", offset: 0x72E0, type: "object" },
    { file_name: "object_raf", collision_name: "gCarnivorousLilyPadCol", offset: 0x108, type: "object" },
    { file_name: "object_raillift", collision_name: "object_raillift_Colheader_0048D0", offset: 0x48D0, type: "object" },
    { file_name: "object_raillift", collision_name: "object_raillift_Colheader_004FF8", offset: 0x4FF8, type: "object" },
    { file_name: "object_rotlift", collision_name: "gDekuMoonDungeonRotatingPlatformsCol", offset: 0x2190, type: "object" },
    { file_name: "object_rotlift", collision_name: "gDekuMoonDungeonRotatingSpikesCol", offset: 0x4DF0, type: "object" },
    { file_name: "object_secom_obj", collision_name: "object_secom_obj_Colheader_0001C0", offset: 0x1C0, type: "object" },
    { file_name: "object_secom_obj", collision_name: "object_secom_obj_Colheader_002CB8", offset: 0x2CB8, type: "object" },
    { file_name: "object_sekihig", collision_name: "gSunsSongGraveGoronCol", offset: 0x33D8, type: "object" },
    { file_name: "object_sekihil", collision_name: "gSunsSongGraveTriforceCol", offset: 0x33F8, type: "object" },
    { file_name: "object_sekihin", collision_name: "gSunsSongGraveKokiriCol", offset: 0x33D8, type: "object" },
    { file_name: "object_sekihiz", collision_name: "gSongOfSoaringPedestalCol", offset: 0x1010, type: "object" },
    { file_name: "object_sichitai_obj", collision_name: "gSichitaiBoatCol", offset: 0x16DC, type: "object" },
    { file_name: "object_sinkai_kabe", collision_name: "gPinnacleRockPythonDenCol", offset: 0x48, type: "object" },
    { file_name: "object_spdweb", collision_name: "object_spdweb_Colheader_0011C0", offset: 0x11C0, type: "object" },
    { file_name: "object_spdweb", collision_name: "object_spdweb_Colheader_002678", offset: 0x2678, type: "object" },
    { file_name: "object_spidertent", collision_name: "object_spidertent_Colheader_0011AC", offset: 0x11AC, type: "object" },
    { file_name: "object_spidertent", collision_name: "object_spidertent_Colheader_00238C", offset: 0x238C, type: "object" },
    { file_name: "object_spinyroll", collision_name: "object_spinyroll_Colheader_000E68", offset: 0xE68, type: "object" },
    { file_name: "object_spinyroll", collision_name: "object_spinyroll_Colheader_000F80", offset: 0xF80, type: "object" },
    { file_name: "object_spot11_obj", collision_name: "gGoronDoorCol", offset: 0x11C0, type: "object" },
    { file_name: "object_spot11_obj", collision_name: "gWoodStepCol", offset: 0x1EB8, type: "object" },
    { file_name: "object_taru", collision_name: "object_taru_Colheader_000FC8", offset: 0xFC8, type: "object" },
    { file_name: "object_taru", collision_name: "object_taru_Colheader_001CB0", offset: 0x1CB0, type: "object" },
    { file_name: "object_tokei_step", collision_name: "gClocktowerPanelCol", offset: 0x968, type: "object" },
    { file_name: "object_tokei_tobira", collision_name: "object_tokei_tobira_Colheader_0012B0", offset: 0x12B0, type: "object" },
    { file_name: "object_tokei_tobira", collision_name: "object_tokei_tobira_Colheader_001590", offset: 0x1590, type: "object" },
    { file_name: "object_tokei_turret", collision_name: "gClockTownTurretBaseCol", offset: 0x26A0, type: "object" },
    { file_name: "object_tokei_turret", collision_name: "gClockTownTurretPlatformCol", offset: 0x2D80, type: "object" },
    { file_name: "object_tree", collision_name: "gTreeTopCol", offset: 0x1B2C, type: "object" },
    { file_name: "object_twig", collision_name: "object_twig_Colheader_0016C0", offset: 0x16C0, type: "object" },
    { file_name: "object_twig", collision_name: "object_twig_Colheader_0020A0", offset: 0x20A0, type: "object" },
    { file_name: "object_um", collision_name: "object_um_Colheader_007E20", offset: 0x7E20, type: "object" },
    { file_name: "object_um", collision_name: "object_um_Colheader_007F50", offset: 0x7F50, type: "object" },
    { file_name: "object_umajump", collision_name: "object_umajump_Colheader_001438", offset: 0x1438, type: "object" },
    { file_name: "object_umajump", collision_name: "object_umajump_Colheader_001558", offset: 0x1558, type: "object" },
    { file_name: "object_visiblock", collision_name: "gLensOfTruthPlatformCol", offset: 0xAD0, type: "object" },
    { file_name: "object_warp1", collision_name: "gWarpBossWarpPlatformCol", offset: 0x8BD4, type: "object" },
    { file_name: "object_wiz", collision_name: "gWizrobePlatformCol", offset: 0x1690, type: "object" },
    { file_name: "object_wood02", collision_name: "object_wood02_Colheader_007A70", offset: 0x7A70, type: "object" },
    { file_name: "object_zg", collision_name: "gTowerCollapseBarsCol", offset: 0x11D4, type: "object" },
    { file_name: "object_zog", collision_name: "gMikauGraveCol", offset: 0x8670, type: "object" },
    { file_name: "ovl_Boss_05", collision_name: "sBioBabaLilypadCol ", offset: 0x3620 , type: "overlay" },
    { file_name: "ovl_Dm_Char08", collision_name: "sTurtleGreatBayTempleCol ", offset: 0x2640 , type: "overlay" },
    { file_name: "ovl_En_Horse_Game_Check", collision_name: "ovl_En_Horse_Game_Check_Colheader_0010C8 ", offset: 0x10C8 , type: "overlay" },
];

const MM_Actors2 = [
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
	{ actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null },
    { actor_name: "", actor_description: "", collision_name: "", params_mask: null, params_values: null }
];
