// Generated by tools/oot/import_oot_rooms.py from the oot decomp -- do not edit.
//
// OOT_Scene_Segments: for each scene whose draw config (z_scene_table.c)
// points a display-list segment at a texture, the file and offset of that
// texture (the daytime / first-frame choice). Room display lists load
// such textures with gsDPSetTextureImage(..., 0x0N000000); the viewer's
// js/zelda_textured.js maps the segment to this data.

const OOT_Scene_Segments = {
    "Bmori1_scene": {
        0x08: { file: "Bmori1_scene", offset: 0x14D90 }, // gForestTempleDayEntranceTex
    },
    "MIZUsin_scene": {
        0x06: { file: "MIZUsin_scene", offset: 0x14CF0 }, // gWaterTempleDayEntranceTex
        0x08: { file: "MIZUsin_scene", offset: 0x14CF0 }, // gWaterTempleDayEntranceTex
    },
    "ddan_scene": {
        0x08: { file: "ddan_scene", offset: 0x12378 }, // gDCDayEntranceTex
        0x09: { file: "ddan_scene", offset: 0x11F78 }, // gDCLavaFloor1Tex
    },
    "gerudoway_scene": {
        0x08: { file: "gerudoway_scene", offset: 0xBD20 }, // gThievesHideoutDayEntranceTex
    },
    "ice_doukutu_scene": {
        0x08: { file: "ice_doukutu_scene", offset: 0xFA10 }, // gIceCavernDayEntranceTex
    },
    "jyasinzou_scene": {
        0x08: { file: "jyasinzou_scene", offset: 0x18940 }, // gSpiritTempleDayEntranceTex
    },
    "men_scene": {
        0x08: { file: "men_scene", offset: 0xF930 }, // gGTGDayEntranceTex
    },
    "miharigoya_scene": {
        0x08: { file: "miharigoya_scene", offset: 0x2350 }, // gGuardHouseOutSideView2DayTex
        0x09: { file: "miharigoya_scene", offset: 0x6550 }, // gGuardHouseOutSideView1DayTex
    },
    "souko_scene": {
        0x08: { file: "souko_scene", offset: 0x5210 }, // gLonLonHouseDayEntranceTex
    },
    "spot01_scene": {
        0x08: { file: "spot01_scene", offset: 0x15B50 }, // gKakarikoVillageDayWindowTex
    },
    "spot07_scene": {
        0x08: { file: "spot07_scene", offset: 0x8F98 }, // gZorasDomainDayEntranceTex
    },
    "spot12_scene": {
        0x08: { file: "spot12_scene", offset: 0x9678 }, // gGerudoFortressNightWallTex
    },
    "spot18_scene": {
        0x08: { file: "spot18_scene", offset: 0x9808 }, // gGoronCityDayEntranceTex
    },
    "spot20_scene": {
        0x08: { file: "spot20_scene", offset: 0x8180 }, // gLonLonRanchDayWindowTex
    },
    "ydan_scene": {
        0x08: { file: "ydan_scene", offset: 0xBA08 }, // gDekuTreeDayEntranceTex
    },
};
