const BK_Maps = [
    { name: "SM_SPIRAL_MOUNTAIN", pointer: "", sceneID: "1", modelAPointer: "14CF", modelBPointer: "14D0" },
    { name: "SM_BANJOS_HOUSE", pointer: "", sceneID: "8C", modelAPointer: "14A2", modelBPointer: "14A4" },
    { name: "MM_MUMBOS_MOUNTAIN", pointer: "", sceneID: "2", modelAPointer: "14AA", modelBPointer: "14AB" },
    { name: "MM_TICKERS_TOWER", pointer: "", sceneID: "C", modelAPointer: "14AC", modelBPointer: "14AD" },
    { name: "MM_MUMBOS_SKULL", pointer: "", sceneID: "E", modelAPointer: "14AE", modelBPointer: "" },
    { name: "TTC_TREASURE_TROVE_COVE", pointer: "", sceneID: "7", modelAPointer: "146B", modelBPointer: "146C" },
    { name: "TTC_BLUBBERS_SHIP", pointer: "", sceneID: "5", modelAPointer: "146F", modelBPointer: "1470" },
    { name: "TTC_NIPPERS_SHELL", pointer: "", sceneID: "6", modelAPointer: "146D", modelBPointer: "146E" },
    { name: "TTC_SHARKFOOD_ISLAND", pointer: "", sceneID: "8F", modelAPointer: "1473", modelBPointer: "" },
    { name: "TTC_SANDCASTLE", pointer: "", sceneID: "A", modelAPointer: "1471", modelBPointer: "1472" },
    { name: "CC_CLANKERS_CAVERN", pointer: "", sceneID: "B", modelAPointer: "14ED", modelBPointer: "14EE" },
    { name: "CC_WITCH_SWITCH_ROOM", pointer: "", sceneID: "21", modelAPointer: "14EF", modelBPointer: "" },
    { name: "CC_INSIDE_CLANKER", pointer: "", sceneID: "22", modelAPointer: "14F0", modelBPointer: "14F1" },
    { name: "CC_GOLDFEATHER_ROOM", pointer: "", sceneID: "23", modelAPointer: "14F2", modelBPointer: "" },
    { name: "BGS_BUBBLEGLOOP_SWAMP", pointer: "", sceneID: "D", modelAPointer: "14D1", modelBPointer: "14D2" },
    { name: "BGS_MR_VILE", pointer: "", sceneID: "10", modelAPointer: "14D3", modelBPointer: "" },
    { name: "BGS_TIPTUP", pointer: "", sceneID: "11", modelAPointer: "14D4", modelBPointer: "14D5" },
    { name: "BGS_MUMBOS_SKULL", pointer: "", sceneID: "47", modelAPointer: "14AE", modelBPointer: "" },
    { name: "GV_GOBIS_VALLEY", pointer: "", sceneID: "12", modelAPointer: "1474", modelBPointer: "1475" },
    { name: "GV_SNS_CHAMBER", pointer: "", sceneID: "92", modelAPointer: "147E", modelBPointer: "" },
    { name: "GV_MEMORY_GAME", pointer: "", sceneID: "13", modelAPointer: "1476", modelBPointer: "" },
    { name: "GV_SANDYBUTTS_MAZE", pointer: "", sceneID: "14", modelAPointer: "1478", modelBPointer: "1479" },
    { name: "GV_WATER_PYRAMID", pointer: "", sceneID: "15", modelAPointer: "147A", modelBPointer: "147B" },
    { name: "GV_RUBEES_CHAMBER", pointer: "", sceneID: "16", modelAPointer: "147C", modelBPointer: "" },
    { name: "GV_INSIDE_JINXY", pointer: "", sceneID: "1A", modelAPointer: "147D", modelBPointer: "" },
    { name: "FP_FREEZEEZY_PEAK", pointer: "", sceneID: "27", modelAPointer: "14C8", modelBPointer: "14C9" },
    { name: "FP_BOGGYS_IGLOO", pointer: "", sceneID: "41", modelAPointer: "14CA", modelBPointer: "14CE" },
    { name: "FP_WOZZAS_CAVE", pointer: "", sceneID: "7F", modelAPointer: "14CC", modelBPointer: "14CD" },
    { name: "FP_MUMBOS_SKULL", pointer: "", sceneID: "48", modelAPointer: "14AE", modelBPointer: "" },
    { name: "FP_CHRISTMAS_TREE", pointer: "", sceneID: "53", modelAPointer: "14CB", modelBPointer: "" },
    { name: "MMM_MAD_MONSTER_MANSION", pointer: "", sceneID: "1B", modelAPointer: "147F", modelBPointer: "1480" },
    { name: "MMM_CHURCH", pointer: "", sceneID: "1C", modelAPointer: "1486", modelBPointer: "1487" },
    { name: "MMM_CELLAR", pointer: "", sceneID: "1D", modelAPointer: "1482", modelBPointer: "149B" },
    { name: "MMM_TUMBLARS_SHED", pointer: "", sceneID: "24", modelAPointer: "1488", modelBPointer: "" },
    { name: "MMM_WELL", pointer: "", sceneID: "25", modelAPointer: "1495", modelBPointer: "1496" },
    { name: "MMM_NAPPERS_ROOM", pointer: "", sceneID: "26", modelAPointer: "1485", modelBPointer: "149A" },
    { name: "MMM_EGG_ROOM", pointer: "", sceneID: "28", modelAPointer: "1489", modelBPointer: "148A" },
    { name: "MMM_NOTE_ROOM", pointer: "", sceneID: "29", modelAPointer: "148B", modelBPointer: "148C" },
    { name: "MMM_FEATHER_ROOM", pointer: "", sceneID: "2A", modelAPointer: "148D", modelBPointer: "148E" },
    { name: "MMM_SECRET_CHURCH_ROOM", pointer: "", sceneID: "2B", modelAPointer: "1483", modelBPointer: "1484" },
    { name: "MMM_BATHROOM", pointer: "", sceneID: "2C", modelAPointer: "148F", modelBPointer: "1490" },
    { name: "MMM_BEDROOM", pointer: "", sceneID: "2D", modelAPointer: "1491", modelBPointer: "1492" },
    { name: "MMM_HONEYCOMB_ROOM", pointer: "", sceneID: "2E", modelAPointer: "1493", modelBPointer: "1494" },
    { name: "MMM_WATERDRAIN_BARREL", pointer: "", sceneID: "2F", modelAPointer: "1481", modelBPointer: "1497" },
    { name: "MMM_MUMBOS_SKULL", pointer: "", sceneID: "30", modelAPointer: "14AE", modelBPointer: "" },
    { name: "MMM_INSIDE_LOGGO", pointer: "", sceneID: "8D", modelAPointer: "1498", modelBPointer: "1499" },
    { name: "RBB_RUSTY_BUCKET_BAY", pointer: "", sceneID: "31", modelAPointer: "14B0", modelBPointer: "14B1" },
    { name: "RBB_ANCHOR_ROOM", pointer: "", sceneID: "8B", modelAPointer: "14C5", modelBPointer: "14C6" },
    { name: "RBB_ENGINE_ROOM", pointer: "", sceneID: "34", modelAPointer: "14B2", modelBPointer: "14B3" },
    { name: "RBB_WAREHOUSE", pointer: "", sceneID: "35", modelAPointer: "14B4", modelBPointer: "14B5" },
    { name: "RBB_BOATHOUSE", pointer: "", sceneID: "36", modelAPointer: "14B6", modelBPointer: "14B7" },
    { name: "RBB_CONTAINER_1", pointer: "", sceneID: "37", modelAPointer: "14B8", modelBPointer: "" },
    { name: "RBB_CONTAINER_2", pointer: "", sceneID: "3E", modelAPointer: "14B9", modelBPointer: "" },
    { name: "RBB_CONTAINER_3", pointer: "", sceneID: "38", modelAPointer: "14BA", modelBPointer: "" },
    { name: "RBB_CREW_CABIN", pointer: "", sceneID: "39", modelAPointer: "14BD", modelBPointer: "" },
    { name: "RBB_BOSS_BOOM_BOX", pointer: "", sceneID: "3A", modelAPointer: "14BE", modelBPointer: "14BF" },
    { name: "RBB_STORAGE_ROOM", pointer: "", sceneID: "3B", modelAPointer: "14C1", modelBPointer: "14C2" },
    { name: "RBB_KITCHEN", pointer: "", sceneID: "3C", modelAPointer: "14C3", modelBPointer: "14C4" },
    { name: "RBB_NAVIGATION_ROOM", pointer: "", sceneID: "3D", modelAPointer: "14C0", modelBPointer: "14C7" },
    { name: "RBB_CAPTAINS_CABIN", pointer: "", sceneID: "3F", modelAPointer: "14BB", modelBPointer: "14BC" },
    { name: "CCW_HUB", pointer: "", sceneID: "40", modelAPointer: "14D8", modelBPointer: "14E3" },
    { name: "CCW_SPRING", pointer: "", sceneID: "43", modelAPointer: "14D9", modelBPointer: "14E4" },
    { name: "CCW_SUMMER", pointer: "", sceneID: "44", modelAPointer: "14DA", modelBPointer: "14E5" },
    { name: "CCW_AUTUMN", pointer: "", sceneID: "45", modelAPointer: "14DB", modelBPointer: "14E6" },
    { name: "CCW_WINTER", pointer: "", sceneID: "46", modelAPointer: "14DC", modelBPointer: "14E7" },
    { name: "CCW_SPRING_MUMBOS_SKULL", pointer: "", sceneID: "4A", modelAPointer: "14AE", modelBPointer: "" },
    { name: "CCW_SUMMER_MUMBOS_SKULL", pointer: "", sceneID: "4B", modelAPointer: "14AE", modelBPointer: "" },
    { name: "CCW_AUTUMN_MUMBOS_SKULL", pointer: "", sceneID: "4C", modelAPointer: "14AE", modelBPointer: "" },
    { name: "CCW_WINTER_MUMBOS_SKULL", pointer: "", sceneID: "4D", modelAPointer: "14AE", modelBPointer: "" },
    { name: "CCW_SUMMER_ZUBBA_HIVE", pointer: "", sceneID: "5A", modelAPointer: "14DD", modelBPointer: "" },
    { name: "CCW_SPRING_ZUBBA_HIVE", pointer: "", sceneID: "5B", modelAPointer: "14DD", modelBPointer: "" },
    { name: "CCW_AUTUMN_ZUBBA_HIVE", pointer: "", sceneID: "5C", modelAPointer: "14DD", modelBPointer: "" },
    { name: "CCW_SPRING_NABNUTS_HOUSE", pointer: "", sceneID: "5E", modelAPointer: "14DE", modelBPointer: "" },
    { name: "CCW_SUMMER_NABNUTS_HOUSE", pointer: "", sceneID: "5F", modelAPointer: "14DE", modelBPointer: "" },
    { name: "CCW_AUTUMN_NABNUTS_HOUSE", pointer: "", sceneID: "60", modelAPointer: "14DE", modelBPointer: "" },
    { name: "CCW_WINTER_NABNUTS_HOUSE", pointer: "", sceneID: "61", modelAPointer: "14DE", modelBPointer: "" },
    { name: "CCW_WINTER_HONEYCOMB_ROOM", pointer: "", sceneID: "62", modelAPointer: "14E0", modelBPointer: "" },
    { name: "CCW_AUTUMN_NABNUTS_WATER_SUPPLY", pointer: "", sceneID: "63", modelAPointer: "14E1", modelBPointer: "14E2" },
    { name: "CCW_WINTER_NABNUTS_WATER_SUPPLY", pointer: "", sceneID: "64", modelAPointer: "14E1", modelBPointer: "14E2" },
    { name: "CCW_SPRING_WHIPCRACK_ROOM", pointer: "", sceneID: "65", modelAPointer: "14DF", modelBPointer: "" },
    { name: "CCW_SUMMER_WHIPCRACK_ROOM", pointer: "", sceneID: "66", modelAPointer: "14DF", modelBPointer: "" },
    { name: "CCW_AUTUMN_WHIPCRACK_ROOM", pointer: "", sceneID: "67", modelAPointer: "14DF", modelBPointer: "" },
    { name: "CCW_WINTER_WHIPCRACK_ROOM", pointer: "", sceneID: "68", modelAPointer: "14DF", modelBPointer: "" },
    { name: "GL_MM_LOBBY", pointer: "", sceneID: "69", modelAPointer: "14F3", modelBPointer: "150B" },
    { name: "GL_TTC_AND_CC_PUZZLE", pointer: "", sceneID: "6A", modelAPointer: "14F4", modelBPointer: "150C" },
    { name: "GL_180_NOTE_DOOR", pointer: "", sceneID: "6B", modelAPointer: "14F5", modelBPointer: "1510" },
    { name: "GL_RED_CAULDRON_ROOM", pointer: "", sceneID: "6C", modelAPointer: "14F6", modelBPointer: "150D" },
    { name: "GL_TTC_LOBBY", pointer: "", sceneID: "6D", modelAPointer: "14F7", modelBPointer: "1512" },
    { name: "GL_GV_LOBBY", pointer: "", sceneID: "6E", modelAPointer: "14F8", modelBPointer: "14A8" },
    { name: "GL_FP_LOBBY", pointer: "", sceneID: "6F", modelAPointer: "14F9", modelBPointer: "14FA" },
    { name: "GL_GV_PUZZLE", pointer: "", sceneID: "74", modelAPointer: "14FD", modelBPointer: "" },
    { name: "GL_CC_LOBBY", pointer: "", sceneID: "70", modelAPointer: "14FB", modelBPointer: "1507" },
    { name: "GL_MMM_LOBBY", pointer: "", sceneID: "75", modelAPointer: "14FE", modelBPointer: "" },
    { name: "GL_CRYPT", pointer: "", sceneID: "7A", modelAPointer: "14FF", modelBPointer: "" },
    { name: "GL_STATUE_ROOM", pointer: "", sceneID: "71", modelAPointer: "1500", modelBPointer: "150E" },
    { name: "GL_BGS_LOBBY", pointer: "", sceneID: "72", modelAPointer: "1501", modelBPointer: "1511" },
    { name: "GL_640_NOTE_DOOR", pointer: "", sceneID: "76", modelAPointer: "1502", modelBPointer: "1508" },
    { name: "GL_RBB_LOBBY", pointer: "", sceneID: "77", modelAPointer: "1503", modelBPointer: "1509" },
    { name: "GL_RBB_AND_MMM_PUZZLE", pointer: "", sceneID: "78", modelAPointer: "1504", modelBPointer: "150A" },
    { name: "GL_CCW_LOBBY", pointer: "", sceneID: "79", modelAPointer: "1505", modelBPointer: "" },
    { name: "GL_FF_ENTRANCE", pointer: "", sceneID: "80", modelAPointer: "1506", modelBPointer: "1514" },
    { name: "GL_FURNACE_FUN", pointer: "", sceneID: "8E", modelAPointer: "14E8", modelBPointer: "" },
    { name: "GL_DINGPOT", pointer: "", sceneID: "93", modelAPointer: "150F", modelBPointer: "1513" },
    { name: "GL_BATTLEMENTS", pointer: "", sceneID: "90", modelAPointer: "14FC", modelBPointer: "1515" },
    { name: "CS_START_NINTENDO", pointer: "", sceneID: "1E", modelAPointer: "149D", modelBPointer: "14A1" },
    { name: "CS_START_RAREWARE", pointer: "", sceneID: "1F", modelAPointer: "149E", modelBPointer: "14A0" },
    { name: "CS_INTRO_GL_DINGPOT_1", pointer: "", sceneID: "7B", modelAPointer: "150F", modelBPointer: "" },
    { name: "CS_INTRO_BANJOS_HOUSE_1", pointer: "", sceneID: "7C", modelAPointer: "14A2", modelBPointer: "" },
    { name: "CS_SPIRAL_MOUNTAIN_1", pointer: "", sceneID: "7D", modelAPointer: "14CF", modelBPointer: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_2", pointer: "", sceneID: "7E", modelAPointer: "14CF", modelBPointer: "14D0" },
    { name: "CS_INTRO_GL_DINGPOT_2", pointer: "", sceneID: "81", modelAPointer: "150F", modelBPointer: "" },
    { name: "CS_ENTERING_GL_MACHINE_ROOM", pointer: "", sceneID: "82", modelAPointer: "150F", modelBPointer: "" },
    { name: "CS_GAME_OVER_MACHINE_ROOM", pointer: "", sceneID: "83", modelAPointer: "150F", modelBPointer: "" },
    { name: "CS_UNUSED_MACHINE_ROOM", pointer: "", sceneID: "84", modelAPointer: "150F", modelBPointer: "" },
    { name: "CS_SPIRAL_MOUNTAIN_3", pointer: "", sceneID: "85", modelAPointer: "14CF", modelBPointer: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_4", pointer: "", sceneID: "86", modelAPointer: "14CF", modelBPointer: "14D0" },
    { name: "CS_SPIRAL_MOUNTAIN_5", pointer: "", sceneID: "87", modelAPointer: "14A6", modelBPointer: "" },
    { name: "CS_SPIRAL_MOUNTAIN_6", pointer: "", sceneID: "88", modelAPointer: "14CF", modelBPointer: "14D0" },
    { name: "CS_INTRO_SPIRAL_7", pointer: "", sceneID: "94", modelAPointer: "14CF", modelBPointer: "14D0" },
    { name: "CS_END_SPIRAL_MOUNTAIN_1", pointer: "", sceneID: "98", modelAPointer: "149F", modelBPointer: "14A3" },
    { name: "CS_END_SPIRAL_MOUNTAIN_2", pointer: "", sceneID: "99", modelAPointer: "149F", modelBPointer: "14A3" },
    { name: "CS_END_ALL_100", pointer: "", sceneID: "95", modelAPointer: "14A9", modelBPointer: "14A5" },
    { name: "CS_END_NOT_100", pointer: "", sceneID: "20", modelAPointer: "14A9", modelBPointer: "14A5" },
    { name: "CS_INTRO_BANJOS_HOUSE_2", pointer: "", sceneID: "89", modelAPointer: "14A2", modelBPointer: "14A4" },
    { name: "CS_INTRO_BANJOS_HOUSE_3", pointer: "", sceneID: "8A", modelAPointer: "14A2", modelBPointer: "14A4" },
    { name: "CS_END_BEACH_1", pointer: "", sceneID: "96", modelAPointer: "14A9", modelBPointer: "14A5" },
    { name: "CS_END_BEACH_2", pointer: "", sceneID: "97", modelAPointer: "14A9", modelBPointer: "14A5" },
    { name: "FILE_SELECT", pointer: "", sceneID: "91", modelAPointer: "14A2", modelBPointer: "14A4" },
];

const BT_Maps = [
    { name: "SM - Spiral Mountain", pointer: "7998", sceneID: "AF", modelAPointer: "c56c", modelBPointer: "c570" },
    { name: "SM - behind the waterfall", pointer: "7994", sceneID: "AE", modelAPointer: "c580", modelBPointer: "c584" },
    { name: "SM - Banjo's House", pointer: "7ca8", sceneID: "0173", modelAPointer: "c574", modelBPointer: "c578" },
    { name: "SM - Banjo's House (Destroyed)", pointer: "7ca8", sceneID: "0173", modelAPointer: "c5a8", modelBPointer: "" },
    { name: "SM - Digger Tunnel", pointer: "7be0", sceneID: "0141", modelAPointer: "c598", modelBPointer: "" },
    { name: "GL - Entrance", pointer: "7990", sceneID: "AD", modelAPointer: "c57c", modelBPointer: "" },
    { name: "JV - Jinjo Village", pointer: "7be4", sceneID: "0142", modelAPointer: "c88c", modelBPointer: "" },
    { name: "JV - Bottles house", pointer: "7be8", sceneID: "0143", modelAPointer: "c8c8", modelBPointer: "c8d4" },
    { name: "JV - King Jingalings throne room", pointer: "7bec", sceneID: "0144", modelAPointer: "c8cc", modelBPointer: "" },
    { name: "JV - Zombiefied Throne Room", pointer: "7d48", sceneID: "019B", modelAPointer: "c8d0", modelBPointer: "" },
    { name: "JV - Jinjo's house", pointer: "7bf0", sceneID: "0145", modelAPointer: "c8c4", modelBPointer: "" },
    /*{ name: "JV - Green jinjo's house", pointer: "7bf0", sceneID: "0145", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Black jinjo's house", pointer: "7bf4", sceneID: "0146", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Yellow jinjo's house", pointer: "7bf8", sceneID: "0147", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Blue jinjo's house", pointer: "7bfc", sceneID: "0148", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Unused jinjo's house", pointer: "7c00", sceneID: "0149", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Brown jinjo's house", pointer: "7c04", sceneID: "014A", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Orange jinjo's house", pointer: "7c08", sceneID: "014B", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Purple jinjo's house", pointer: "7c0c", sceneID: "014C", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - Red jinjo's house", pointer: "7c10", sceneID: "014D", modelAPointer: "c8c4", modelBPointer: "" },
    { name: "JV - White jinjo's house", pointer: "7c14", sceneID: "014E", modelAPointer: "c8c4", modelBPointer: "" },*/
    { name: "Mumbo's Skull", pointer: "7c34", sceneID: "0156", modelAPointer: "c58c", modelBPointer: "c590" },
    { name: "Wumba's Wigwam", pointer: "7c38", sceneID: "0157", modelAPointer: "c588", modelBPointer: "c5a0" },
    { name: "IOH - Wooden Hollow", pointer: "7c18", sceneID: "014F", modelAPointer: "c890", modelBPointer: "" },
    { name: "IOH - Heggy's egg shed", pointer: "7c1c", sceneID: "0150", modelAPointer: "c8a4", modelBPointer: "" },
    { name: "IOH - Jiggywiggy's temple", pointer: "7c20", sceneID: "0151", modelAPointer: "c894", modelBPointer: "" },
    { name: "IOH - Plateau", pointer: "7c24", sceneID: "0152", modelAPointer: "c898", modelBPointer: "" },
    { name: "IOH - Honey B's Hive", pointer: "7c28", sceneID: "0153", modelAPointer: "c8c0", modelBPointer: "" },
    { name: "IOH - Pine Grove", pointer: "7c2c", sceneID: "0154", modelAPointer: "c89c", modelBPointer: "c8a0" },
    { name: "IOH - Cliff Top", pointer: "7c30", sceneID: "0155", modelAPointer: "c8a8", modelBPointer: "" },
    { name: "IOH - Wasteland", pointer: "7c44", sceneID: "015A", modelAPointer: "c8ac", modelBPointer: "" },
    { name: "IOH - Digger Tunnel", pointer: "7c48", sceneID: "015B", modelAPointer: "c8b8", modelBPointer: "" },
    { name: "IOH - Quagmire", pointer: "7c4c", sceneID: "015C", modelAPointer: "c8b0", modelBPointer: "" },
    { name: "MT", pointer: "79bc", sceneID: "B8", modelAPointer: "c5b0", modelBPointer: "c5b4" },
    { name: "MT - Prison Compound", pointer: "79c4", sceneID: "B9", modelAPointer: "c5b8", modelBPointer: "c5bc" },
    { name: "MT - Columns Vault", pointer: "79c8", sceneID: "BA", modelAPointer: "c5c0", modelBPointer: "" },
    { name: "MT - Mayan Kickball Stadium", pointer: "79cc", sceneID: "BB", modelAPointer: "c5c4", modelBPointer: "" },
    { name: "MT - Code Chamber", pointer: "79cc", sceneID: "BC", modelAPointer: "c5c8", modelBPointer: "" },
    { name: "MT - Jade Snake Grove", pointer: "79ec", sceneID: "C4", modelAPointer: "c5cc", modelBPointer: "c5d0" },
    { name: "MT - Treasure Chamber", pointer: "79f0", sceneID: "C5", modelAPointer: "c5d4", modelBPointer: "" },
    { name: "MT - Kickball Arena", pointer: "79f4", sceneID: "C6", modelAPointer: "c5d8", modelBPointer: "" },
    { name: "MT - kickball arena", pointer: "7a00", sceneID: "00C9", modelAPointer: "c5d8", modelBPointer: "" },
    { name: "MT - Targitzan's Slighty Sacred Temple", pointer: "7cb8", sceneID: "0177", modelAPointer: "c5dc", modelBPointer: "" },
    { name: "MT - Inside Targitzan's temple", pointer: "7cbc", sceneID: "0178", modelAPointer: "c5e0", modelBPointer: "" },
    { name: "MT - Targitzan temple lobby", pointer: "7cc0", sceneID: "0179", modelAPointer: "c5e4", modelBPointer: "" },
    { name: "MT - Targitzan's Really Sacred Chamber", pointer: "7cc4", sceneID: "017A", modelAPointer: "c5dc", modelBPointer: "" },
    { name: "GGM", pointer: "79f8", sceneID: "C7", modelAPointer: "c61c", modelBPointer: "c660" },
    { name: "GGM - fuel depot", pointer: "7a04", sceneID: "00CA", modelAPointer: "c5ec", modelBPointer: "c650" },
    { name: "GGM - crushing shed", pointer: "7a08", sceneID: "00CB", modelAPointer: "c5f0", modelBPointer: "c628" },
    { name: "GGM - flooded caves", pointer: "7a0c", sceneID: "00CC", modelAPointer: "c5f4", modelBPointer: "c63c" },
    { name: "GGM - water storage", pointer: "7a10", sceneID: "00CD", modelAPointer: "c5f8", modelBPointer: "c648" },
    { name: "GGM - waterfall cavern", pointer: "7a14", sceneID: "00CE", modelAPointer: "c5fc", modelBPointer: "c620" },
    { name: "GGM - power hut basement", pointer: "7a18", sceneID: "00CF", modelAPointer: "c600", modelBPointer: "c634" },
    { name: "GGM - chuffy's cab", pointer: "7a1c", sceneID: "00D0", modelAPointer: "c604", modelBPointer: "" },
    { name: "GGM - inside chuffy's boiler boss", pointer: "7a20", sceneID: "00D1", modelAPointer: "c608", modelBPointer: "" },
    { name: "GGM - gloomy caverns", pointer: "7a24", sceneID: "00D2", modelAPointer: "c60c", modelBPointer: "c630" },
    { name: "GGM - generator caverns", pointer: "7a28", sceneID: "00D3", modelAPointer: "c610", modelBPointer: "c640" },
    { name: "GGM - power hut", pointer: "7a2c", sceneID: "00D4", modelAPointer: "c614", modelBPointer: "c62c" },
    { name: "GGM - train station", pointer: "7a38", sceneID: "00D7", modelAPointer: "c618", modelBPointer: "" },
    { name: "GGM - prospectors hut", pointer: "7a3c", sceneID: "00D8", modelAPointer: "c638", modelBPointer: "c664" },
    { name: "GGM - toxic gas cave", pointer: "7a44", sceneID: "00DA", modelAPointer: "c644", modelBPointer: "" },
    { name: "GGM - canary cave", pointer: "7a48", sceneID: "00DB", modelAPointer: "c624", modelBPointer: "c64c" },
    { name: "GGM - Inside Chuffy's wagon", pointer: "7b60", sceneID: "0121", modelAPointer: "c654", modelBPointer: "" },
    { name: "GGM - water supply pipe", pointer: "7b74", sceneID: "0126", modelAPointer: "c700", modelBPointer: "" },
    { name: "GGM - Ordnance Shooting Entrance", pointer: "7c68", sceneID: "0163", modelAPointer: "c65c", modelBPointer: "" },
    { name: "GGM - ordnance storage", pointer: "7a4c", sceneID: "00DC", modelAPointer: "c658", modelBPointer: "" },
    /*{ name: "GGM - Ordnance Shooting Game", pointer: "7c6c", sceneID: "0164", modelAPointer: "", modelBPointer: "" },
    { name: "GGM - Ordnance Shooting Game Multi", pointer: "7c70", sceneID: "0165", modelAPointer: "", modelBPointer: "" },*/
    { name: "WW - Witchyworld", pointer: "7a34", sceneID: "00D6", modelAPointer: "c668", modelBPointer: "c698" },
    { name: "WW - dodgem dome lobby", pointer: "7a50", sceneID: "00DD", modelAPointer: "c68c", modelBPointer: "" },
    /*{ name: "WW - dodgem challenge 1 vs 1", pointer: "7a54", sceneID: "00DE", modelAPointer: "c690", modelBPointer: "" },
    { name: "WW - dodgem challenge 2 vs 1", pointer: "7a58", sceneID: "00DF", modelAPointer: "c690", modelBPointer: "" },
    { name: "WW - dodgem challenge 3 vs 1", pointer: "7a5c", sceneID: "00E0", modelAPointer: "c690", modelBPointer: "" },*/
    { name: "WW - crazy castle stockade", pointer: "7a60", sceneID: "00E1", modelAPointer: "c66c", modelBPointer: "" },
    { name: "WW - crazy castle lobby", pointer: "7a64", sceneID: "00E2", modelAPointer: "c674", modelBPointer: "" },
    { name: "WW - crazy castle pump room", pointer: "7a68", sceneID: "00E3", modelAPointer: "c670", modelBPointer: "" },
    { name: "WW - balloon burst game", pointer: "7a6c", sceneID: "00E4", modelAPointer: "c6a0", modelBPointer: "" },
    { name: "WW - hoop hurry game", pointer: "7a70", sceneID: "00E5", modelAPointer: "c6a0", modelBPointer: "" },
    { name: "WW - star spinner", pointer: "7a74", sceneID: "00E6", modelAPointer: "c688", modelBPointer: "c69c" },
    { name: "WW - the inferno", pointer: "7a78", sceneID: "00E7", modelAPointer: "c678", modelBPointer: "" },
    { name: "WW - Haunted Caverns", pointer: "7a88", sceneID: "00EB", modelAPointer: "c680", modelBPointer: "" },
    { name: "WW - Cave of Horrors", pointer: "7a84", sceneID: "00EA", modelAPointer: "c67c", modelBPointer: "" },
    { name: "WW - Train Station", pointer: "7a8c", sceneID: "00EC", modelAPointer: "c684", modelBPointer: "c6b0" },
    { name: "WW - Mr. Patch", pointer: "7ac0", sceneID: "00F9", modelAPointer: "c694", modelBPointer: "" },
    /*{ name: "WW - Saucer of Peril", pointer: "7b6c", sceneID: "0124", modelAPointer: "", modelBPointer: "" },
    { name: "WW - crazy castle stockade (sop)", pointer: "7bc8", sceneID: "013B", modelAPointer: "c66c", modelBPointer: "" },
    { name: "WW - star spinner (sop)", pointer: "7bcc", sceneID: "013C", modelAPointer: "", modelBPointer: "" },*/
    { name: "JRL - Town", pointer: "7d78", sceneID: "01A7", modelAPointer: "6e24", modelBPointer: "" }, //c6f8
    { name: "JRL - Town buildings", pointer: "", sceneID: "01A7", modelAPointer: "6e58", modelBPointer: "" },
    { name: "JRL - UFO area", pointer: "", sceneID: "", modelAPointer: "6e28", modelBPointer: "" },
    { name: "JRL - Smugglers Cavern", pointer: "7d74", sceneID: "01A6", modelAPointer: "6e2c", modelBPointer: "6e5c" },
    { name: "JRL - Atlantis", pointer: "7d7c", sceneID: "01A8", modelAPointer: "6e30", modelBPointer: "" },
    { name: "JRL - Sunken Ship area", pointer: "", sceneID: "", modelAPointer: "6e48", modelBPointer: "" },
    { name: "JRL - Wumba area", pointer: "", sceneID: "", modelAPointer: "6e54", modelBPointer: "6e64" },
    { name: "JRL - Sea Bottom locker area", pointer: "7d80", sceneID: "01A9", modelAPointer: "6e4c", modelBPointer: "" },
    { name: "JRL - Sea Bottom big fish area", pointer: "", sceneID: "", modelAPointer: "6e50", modelBPointer: "6e68" },
    { name: "JRL - Passage UFO to Smugglers", pointer: "", sceneID: "", modelAPointer: "6e34", modelBPointer: "" },
    { name: "JRL - Passage UFO to Atlantis", pointer: "", sceneID: "", modelAPointer: "6e38", modelBPointer: "" },
    { name: "JRL - Passage Atlantis to ship", pointer: "", sceneID: "", modelAPointer: "6e3c", modelBPointer: "" },
    { name: "JRL - Passage ship to locker", pointer: "", sceneID: "", modelAPointer: "6e40", modelBPointer: "" },
    { name: "JRL - Passage locker to big fish", pointer: "", sceneID: "", modelAPointer: "6e44", modelBPointer: "" },
    { name: "JRL - Jollys", pointer: "7a90", sceneID: "00ED", modelAPointer: "c6e4", modelBPointer: "c714" },
    //{ name: "JRL - Wumba's Wigwam", pointer: "7b5c", sceneID: "0120", modelAPointer: "c588", modelBPointer: "c5a0" },
    { name: "JRL - Pawno", pointer: "7a94", sceneID: "00EE", modelAPointer: "c6ec", modelBPointer: "c6f0" },
    { name: "JRL - Inside UFO", pointer: "7aa0", sceneID: "00F1", modelAPointer: "c6b8", modelBPointer: "c718" },
    { name: "JRL - Ancient Swimming Baths", pointer: "7aac", sceneID: "00F4", modelAPointer: "c6bc", modelBPointer: "c6c0" },
    { name: "JRL - Water (laggy)", pointer: "", sceneID: "", modelAPointer: "c6f8", modelBPointer: "" },
    //{ name: "JRL - Objects (Beta JRL)", pointer: "7ab0", sceneID: "00F5", modelAPointer: "", modelBPointer: "" },
    { name: "JRL - Electric Eels Lair", pointer: "7ab4", sceneID: "00F6", modelAPointer: "c6c4", modelBPointer: "c6c8" },
    { name: "JRL - Seaweed Santchum", pointer: "7ab8", sceneID: "00F7", modelAPointer: "c6cc", modelBPointer: "c6d0" },
    { name: "JRL - Inside the big fish", pointer: "7abc", sceneID: "00F8", modelAPointer: "c6d4", modelBPointer: "c6d8" },
    { name: "JRL - Temple of the Fishes", pointer: "7ac4", sceneID: "00FA", modelAPointer: "c6dc", modelBPointer: "c6fc" },
    { name: "JRL - Lord Woo Fak Fak", pointer: "7acc", sceneID: "00FC", modelAPointer: "c6e8", modelBPointer: "" },
    { name: "JRL - Blubber's Wave Race Hire", pointer: "7ad8", sceneID: "00FF", modelAPointer: "c6f4", modelBPointer: "" },
    { name: "JRL - sea bottom cavern", pointer: "7ce0", sceneID: "0181", modelAPointer: "c708", modelBPointer: "" },
    /*{ name: "JRL - submarine multi", pointer: "7ce4", sceneID: "0182", modelAPointer: "", modelBPointer: "" },*/
    { name: "TDL", pointer: "7b24", sceneID: "0112", modelAPointer: "c720", modelBPointer: "c750" },
    { name: "TDL - terry's nest", pointer: "7b28", sceneID: "0113", modelAPointer: "c734", modelBPointer: "c75c" },
    { name: "TDL - train station", pointer: "7b2c", sceneID: "0114", modelAPointer: "c740", modelBPointer: "" },
    { name: "TDL - oogle boogles cave", pointer: "7b30", sceneID: "0115", modelAPointer: "c744", modelBPointer: "" },
    { name: "TDL - inside the mountain", pointer: "7b34", sceneID: "0116", modelAPointer: "c72c", modelBPointer: "c730" },
    { name: "TDL - river passage", pointer: "7b38", sceneID: "0117", modelAPointer: "c738", modelBPointer: "c73c" },
    { name: "TDL - styracosaurus family cave", pointer: "7b3c", sceneID: "0118", modelAPointer: "c728", modelBPointer: "" },
    { name: "TDL - unga bunga's cave", pointer: "7b40", sceneID: "0119", modelAPointer: "c748", modelBPointer: "" },
    { name: "TDL - stomping plains", pointer: "7b44", sceneID: "011A", modelAPointer: "c74c", modelBPointer: "" },
    { name: "TDL - bonfire caverns", pointer: "7b48", sceneID: "011B", modelAPointer: "c724", modelBPointer: "" },
    { name: "TDL - Wumba's Wigwam Big (missing)", pointer: "7b64", sceneID: "0122", modelAPointer: "", modelBPointer: "" },
    { name: "TDL - Inside chompa's belly", pointer: "7b68", sceneID: "0123", modelAPointer: "c608", modelBPointer: "" },
    { name: "GI - outside", pointer: "7adc", sceneID: "0100", modelAPointer: "c760", modelBPointer: "c7a8" },
    { name: "GI - floor 1", pointer: "7ae0", sceneID: "0101", modelAPointer: "c764", modelBPointer: "c7a4" },
    { name: "GI - Train Station", pointer: "7ae4", sceneID: "0102", modelAPointer: "c77c", modelBPointer: "c7b8" },
    { name: "GI - workers quarters", pointer: "7ae8", sceneID: "0103", modelAPointer: "c790", modelBPointer: "c7dc" },
    { name: "GI - trash compactor", pointer: "7aec", sceneID: "0104", modelAPointer: "c780", modelBPointer: "" },
    { name: "GI - toxic waste disposal", pointer: "7b20", sceneID: "0111", modelAPointer: "c78c", modelBPointer: "c7a0" },
    { name: "GI - elevator shaft", pointer: "7af0", sceneID: "0105", modelAPointer: "c774", modelBPointer: "" },
    { name: "GI - floor 2", pointer: "7af4", sceneID: "0106", modelAPointer: "c768", modelBPointer: "c7c4" },
    { name: "GI - floor 2 (electromagnet chamber)", pointer: "7af8", sceneID: "0107", modelAPointer: "c788", modelBPointer: "" },
    { name: "GI - floor 3", pointer: "7afc", sceneID: "0108", modelAPointer: "c76C", modelBPointer: "c7c8" },
    { name: "GI - floor 3 (boiler plant)", pointer: "7b00", sceneID: "0109", modelAPointer: "c784", modelBPointer: "c7d8" },
    { name: "GI - floor 3 (packing room)", pointer: "7b04", sceneID: "010A", modelAPointer: "c7b0", modelBPointer: "" },
    { name: "GI - floor 4", pointer: "7b08", sceneID: "010B", modelAPointer: "c770", modelBPointer: "c7cc" },
    { name: "GI - floor 4 (cable room)", pointer: "7b0c", sceneID: "010C", modelAPointer: "c798", modelBPointer: "" },
    { name: "GI - floor 4 (quality control)", pointer: "7b10", sceneID: "010D", modelAPointer: "c79c", modelBPointer: "c7ac" },
    { name: "GI - floor 4 (Clinker's Cavern Lobby)", pointer: "7cf8", sceneID: "0187", modelAPointer: "c7c0", modelBPointer: "c7e0" },
    { name: "GI - floor 4 (Clinker's Cavern)", pointer: "7c64", sceneID: "0162", modelAPointer: "c7bc", modelBPointer: "" },
    { name: "GI - floor 5", pointer: "7b14", sceneID: "010E", modelAPointer: "c794", modelBPointer: "" },
    { name: "GI - basement", pointer: "7b18", sceneID: "010F", modelAPointer: "c778", modelBPointer: "c7d4" },
    { name: "GI - basement (repair depot)", pointer: "7b1c", sceneID: "0110", modelAPointer: "c7b4", modelBPointer: "" },
    { name: "GI - water supply pipe", pointer: "7b70", sceneID: "0125", modelAPointer: "c704", modelBPointer: "" },
    { name: "HFP - lava side", pointer: "7b78", sceneID: "0127", modelAPointer: "c7ec", modelBPointer: "c7f0" },
    { name: "HFP - icy side", pointer: "7b7c", sceneID: "0128", modelAPointer: "c7f4", modelBPointer: "c7f8" },
    { name: "HFP - lava train station", pointer: "7b80", sceneID: "0129", modelAPointer: "c808", modelBPointer: "" },
    { name: "HFP - ice train station", pointer: "7b84", sceneID: "012A", modelAPointer: "c800", modelBPointer: "c804" },
    { name: "HFP - chilli billi", pointer: "7b88", sceneID: "012B", modelAPointer: "c81c", modelBPointer: "c82c" },
    { name: "HFP - chilly willy", pointer: "7b8c", sceneID: "012C", modelAPointer: "c820", modelBPointer: "c830" },
    { name: "HFP - colosseum kickball stadium lobby", pointer: "7b90", sceneID: "012D", modelAPointer: "c814", modelBPointer: "" },
    /*{ name: "HFP - colosseum kickball stadium - Quarterfinal", pointer: "7b94", sceneID: "012E", modelAPointer: "", modelBPointer: "" },
    { name: "HFP - colosseum kickball stadium - Semifinal", pointer: "7b98", sceneID: "012F", modelAPointer: "", modelBPointer: "" },
    { name: "HFP - colosseum kickball stadium - Final", pointer: "7b9c", sceneID: "0130", modelAPointer: "", modelBPointer: "" },*/
    { name: "HFP - boggy's igloo", pointer: "7ba0", sceneID: "0131", modelAPointer: "c7fc", modelBPointer: "c828" },
    { name: "HFP - icicle grotto", pointer: "7ba4", sceneID: "0132", modelAPointer: "c80c", modelBPointer: "" },
    { name: "HFP - inside the volcano", pointer: "7ba8", sceneID: "0133", modelAPointer: "c818", modelBPointer: "" },
    { name: "CCL", pointer: "7c60", sceneID: "0161", modelAPointer: "c834", modelBPointer: "c854" },
    { name: "CCL - Cloud Cuckoo Land", pointer: "7bb4", sceneID: "0136", modelAPointer: "c834", modelBPointer: "c854" },
    { name: "CCL - inside the trashcan", pointer: "7bb8", sceneID: "0137", modelAPointer: "c84c", modelBPointer: "c850" },
    { name: "CCL - inside the cheesewedge", pointer: "7bbc", sceneID: "0138", modelAPointer: "c848", modelBPointer: "c860" },
    { name: "CCL - central cavern", pointer: "7bc4", sceneID: "013A", modelAPointer: "c838", modelBPointer: "c858" },
    { name: "CCL - inside the pot o gold", pointer: "7bd0", sceneID: "013D", modelAPointer: "c83c", modelBPointer: "c840" },
    { name: "CK - Cauldron Keep", pointer: "7c50", sceneID: "015D", modelAPointer: "c86c", modelBPointer: "c870" },
    { name: "CK - Gatehouse", pointer: "7c54", sceneID: "015E", modelAPointer: "c878", modelBPointer: "72e4" },
    { name: "CK - Quiz", pointer: "7c58", sceneID: "015F", modelAPointer: "c87c", modelBPointer: "" },
    { name: "CK - Gun Chamber", pointer: "7c5c", sceneID: "0160", modelAPointer: "c874", modelBPointer: "" },
    //{ name: "CK - Gun Room Still", pointer: "7c84", sceneID: "016A", modelAPointer: "", modelBPointer: "" },
    { name: "CK - Final Boss", pointer: "", sceneID: "", modelAPointer: "c884", modelBPointer: "" },
    { name: "CK - Final Boss Inside", pointer: "", sceneID: "", modelAPointer: "c880", modelBPointer: "" },
    /*{ name: "CK", pointer: "7d44", sceneID: "019A", modelAPointer: "", modelBPointer: "" },
    { name: "MT - Multi", pointer: "7c74", sceneID: "0166", modelAPointer: "", modelBPointer: "" },
    { name: "MT - still", pointer: "7c78", sceneID: "0167", modelAPointer: "", modelBPointer: "" },
    { name: "HFP - Icy side still", pointer: "7c7c", sceneID: "0168", modelAPointer: "", modelBPointer: "" },
    { name: "Bottles house still", pointer: "7c80", sceneID: "0169", modelAPointer: "", modelBPointer: "" },
    { name: "GGM", pointer: "7c98", sceneID: "016F", modelAPointer: "", modelBPointer: "" },
    { name: "GGM", pointer: "7c9c", sceneID: "0170", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Balloons", pointer: "7cc8", sceneID: "017B", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Hoops", pointer: "7ccc", sceneID: "017C", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Packing Game", pointer: "7cd0", sceneID: "017D", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Kickball Arena", pointer: "7cd8", sceneID: "017F", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Kickball Arena 2", pointer: "7cdc", sceneID: "0180", modelAPointer: "", modelBPointer: "" },
    { name: "TDL - chompa's belly multi", pointer: "7ce8", sceneID: "0183", modelAPointer: "", modelBPointer: "" },
    { name: "Beta green pipe", pointer: "7cec", sceneID: "0184", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Trash Can", pointer: "7cf0", sceneID: "0185", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Dodgems", pointer: "7cf4", sceneID: "0186", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Bee Hive", pointer: "7cfc", sceneID: "0188", modelAPointer: "", modelBPointer: "" },
    { name: "MP - Quiz Game", pointer: "7d00", sceneID: "0189", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Game select screen", pointer: "7c3c", sceneID: "0158", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Opening cut scene", pointer: "7c40", sceneID: "0159", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Intro", pointer: "7d08", sceneID: "018B", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Sisters explain BOB", pointer: "7d0c", sceneID: "018C", modelAPointer: "", modelBPointer: "" },
    { name: "CS - About to Blast Jingaling", pointer: "7d18", sceneID: "018F", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Getting Zapped", pointer: "7d1c", sceneID: "0190", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Zombiefied Throne Room", pointer: "7cd4", sceneID: "017E", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Gained energy from Jingaling", pointer: "7d10", sceneID: "018D", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Party Ended", pointer: "7d20", sceneID: "0191", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Bottles gets home", pointer: "7d24", sceneID: "0192", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Bottles is brought back to life!", pointer: "7d28", sceneID: "0193", modelAPointer: "", modelBPointer: "" },
    { name: "CS - B and K About to use BOB", pointer: "7d2c", sceneID: "0194", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Lets fix Bottles Next", pointer: "7d30", sceneID: "0195", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Playing with Gruntys Head", pointer: "7d34", sceneID: "0196", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Giving Jingaliong back life", pointer: "7d38", sceneID: "0197", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Jingalings Temple gets back life", pointer: "7d3c", sceneID: "0198", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Jingaling Celebrates that hes back", pointer: "7d40", sceneID: "0199", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Credits", pointer: "7d4c", sceneID: "019C", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Character Parade", pointer: "7d50", sceneID: "019D", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Two Years have Passed", pointer: "7960", sceneID: "A1", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Drill Starts", pointer: "7964", sceneID: "A2", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Drill goes through Boulders", pointer: "7968", sceneID: "A3", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Use Magic to Lift Boulder", pointer: "796c", sceneID: "A4", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Revenge is Mine!", pointer: "7970", sceneID: "A5", modelAPointer: "10510", modelBPointer: "" },
    { name: "CS - Witches Leave Spiral Mountain", pointer: "7974", sceneID: "A6", modelAPointer: "", modelBPointer: "" },
    { name: "CS - House Destoryed", pointer: "7978", sceneID: "A7", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Playing Poker", pointer: "797c", sceneID: "A8", modelAPointer: "", modelBPointer: "10518" },
    { name: "CS - Earthquake!", pointer: "7980", sceneID: "A9", modelAPointer: "", modelBPointer: "" },
    { name: "CS - It Stopped", pointer: "7984", sceneID: "AA", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Get out of the House!", pointer: "7988", sceneID: "AB", modelAPointer: "", modelBPointer: "" },
    { name: "CS - Come on!", pointer: "798c", sceneID: "AC", modelAPointer: "", modelBPointer: "" },*/
];

const OOT_Maps = [
    { name: "Spot 00 - Hyrule Field", file: "spot00_scene", seams: "spot00_scene_seams.txt" },
    { name: "Spot 01 - Kakariko Village", file: "spot01_scene", seams: "spot01_scene_seams.txt" },
    { name: "Spot 02 - Graveyard", file: "spot02_scene", seams: "spot02_scene_seams.txt" },
    { name: "Spot 03 - Zora's River", file: "spot03_scene", seams: "spot03_scene_seams.txt" },
    { name: "Spot 04 - Kokiri Forest", file: "spot04_scene", seams: "spot04_scene_seams.txt" },
    { name: "Spot 05 - Sacred Forest Meadow", file: "spot05_scene", seams: "spot05_scene_seams.txt" },
    { name: "Spot 06 - Lake Hylia", file: "spot06_scene", seams: "spot06_scene_seams.txt" },
    { name: "Spot 07 - Zora's Domain", file: "spot07_scene", seams: "spot07_scene_seams.txt" },
    { name: "Spot 08 - Zora's Fountain", file: "spot08_scene", seams: "spot08_scene_seams.txt" },
    { name: "Spot 09 - Gerudo Valley", file: "spot09_scene", seams: "spot09_scene_seams.txt" },
    { name: "Spot 10 - Lost Woods", file: "spot10_scene", seams: "spot10_scene_seams.txt" },
    { name: "Spot 11 - Desert Colossus", file: "spot11_scene", seams: "spot11_scene_seams.txt" },
    { name: "Spot 12 - Gerudo's Fortress", file: "spot12_scene", seams: "spot12_scene_seams.txt" },
    { name: "Spot 13 - Haunted Wasteland", file: "spot13_scene", seams: "spot13_scene_seams.txt" },
    { name: "Spot 15 - Hyrule Castle", file: "spot15_scene", seams: "spot15_scene_seams.txt" },
    { name: "Spot 16 - Death Mountain Trail", file: "spot16_scene", seams: "spot16_scene_seams.txt" },
    { name: "Spot 17 - Death Mountain Crater", file: "spot17_scene", seams: "spot17_scene_seams.txt" },
    { name: "Spot 18 - Goron City", file: "spot18_scene", seams: "spot18_scene_seams.txt" },
    { name: "Spot 20 - Lon Lon Ranch", file: "spot20_scene", seams: "spot20_scene_seams.txt" },
    { name: "Back Alley (Day)", file: "market_alley_scene" },
    { name: "Back Alley (Night)", file: "market_alley_n_scene" },
    { name: "Back Alley House (Dog Lady)", file: "impa_scene" },
    { name: "Back Alley House (Man in Green)", file: "kakariko3_scene" },
    { name: "Barinade's Lair", file: "bdan_boss_scene", seams: "bdan_boss_scene_seams.txt" },
    { name: "Bazaar", file: "shop1_scene" },
    { name: "Bombchu Bowling Alley", file: "bowling_scene", seams: "bowling_scene_seams.txt" },
    { name: "Bombchu Shop", file: "night_shop_scene" },
    { name: "Bongo Bongo's Lair", file: "HAKAdan_bs_scene", seams: "HAKAdan_bs_scene_seams.txt" },
    { name: "Bottom of the Well", file: "HAKAdanCH_scene", seams: "HAKAdanCH_scene_seams.txt" },
    { name: "Carpenter Boss's House", file: "kakariko_scene" },
    { name: "Carpenters' Tent", file: "tent_scene" },
    { name: "Castle Courtyard", file: "nakaniwa_scene", seams: "nakaniwa_scene_seams.txt" },
    { name: "Castle Hedge Maze (Day)", file: "hairal_niwa_scene", seams: "hairal_niwa_scene_seams.txt" },
    { name: "Castle Hedge Maze (Night)", file: "hairal_niwa_n_scene" },
    { name: "Chamber of the Sages", file: "kenjyanoma_scene" },
    { name: "Cutscene Map", file: "hiral_demo_scene" },
    { name: "Dampe's Grave & Windmill", file: "hakasitarelay_scene", seams: "hakasitarelay_scene_seams.txt" },
    { name: "Dodongo's Cavern", file: "ddan_scene", seams: "ddan_scene_seams.txt" },
    { name: "Fairy's Fountain (Healing Fairies)", file: "yousei_izumi_tate_scene", seams: "yousei_izumi_tate_scene_seams.txt" },
    { name: "Fire Temple", file: "HIDAN_scene", seams: "HIDAN_scene_seams.txt" },
    { name: "Fishing Pond", file: "turibori_scene", seams: "turibori_scene_seams.txt" },
    { name: "Forest Temple", file: "Bmori1_scene", seams: "Bmori1_scene_seams.txt" },
    { name: "Ganon's Castle Exterior", file: "ganon_tou_scene", seams: "ganon_tou_scene_seams.txt" },
    { name: "Ganon's Tower", file: "ganon_scene", seams: "ganon_scene_seams.txt" },
    { name: "Ganon's Tower (Collapsing)", file: "ganon_sonogo_scene", seams: "ganon_sonogo_scene_seams.txt" },
    { name: "Ganon's Tower Collapse & Battle Arena", file: "ganon_demo_scene", seams: "ganon_demo_scene_seams.txt" },
    { name: "Ganon's Tower Exterior (Collapsing)", file: "ganon_final_scene", seams: "ganon_final_scene_seams.txt" },
    { name: "Ganondorf's Lair", file: "ganon_boss_scene", seams: "ganon_boss_scene_seams.txt" },
    { name: "Gerudo Training Ground", file: "men_scene", seams: "men_scene_seams.txt" },
    { name: "Gohma's Lair", file: "ydan_boss_scene", seams: "ydan_boss_scene_seams.txt" },
    { name: "Goron Shop", file: "golon_scene", seams: "golon_scene_seams.txt" },
    { name: "Granny's Potion Shop", file: "mahouya_scene" },
    { name: "Grave (Fairy's Fountain)", file: "hakaana2_scene", seams: "hakaana2_scene_seams.txt" },
    { name: "Grave (Redead)", file: "hakaana_scene" },
    { name: "Gravekeeper's Hut", file: "hut_scene" },
    { name: "Great Fairy's Fountain (Spells)", file: "yousei_izumi_yoko_scene" },
    { name: "Great Fairy's Fountain (Upgrades)", file: "daiyousei_izumi_scene" },
    { name: "Grottos", file: "kakusiana_scene", seams: "kakusiana_scene_seams.txt" },
    { name: "Guard House", file: "miharigoya_scene", seams: "miharigoya_scene_seams.txt" },
    { name: "Happy Mask Shop", file: "face_shop_scene" },
    { name: "House of Skulltula", file: "kinsuta_scene", seams: "kinsuta_scene_seams.txt" },
    { name: "House of Twins", file: "kokiri_home3_scene", seams: "kokiri_home3_scene_seams.txt" },
    { name: "Ice Cavern", file: "ice_doukutu_scene", seams: "ice_doukutu_scene_seams.txt" },
    { name: "Impa's House", file: "labo_scene" },
    { name: "Inside Ganon's Castle", file: "ganontika_scene", seams: "ganontika_scene_seams.txt" },
    { name: "Inside Ganon's Castle (Collapsing)", file: "ganontikasonogo_scene", seams: "ganontikasonogo_scene_seams.txt" },
    { name: "Inside Jabu-Jabu's Belly", file: "bdan_scene", seams: "bdan_scene_seams.txt" },
    { name: "Inside the Deku Tree", file: "ydan_scene", seams: "ydan_scene_seams.txt" },
    { name: "Kakariko Potion Shop", file: "drag_scene" },
    { name: "King Dodongo's Lair", file: "ddan_boss_scene", seams: "ddan_boss_scene_seams.txt" },
    { name: "Know-It-All Brothers' House", file: "kokiri_home_scene" },
    { name: "Kokiri Shop", file: "kokiri_shop_scene" },
    { name: "Lakeside Laboratory", file: "hylia_labo_scene", seams: "hylia_labo_scene_seams.txt" },
    { name: "Link's House", file: "link_home_scene" },
    { name: "Lon Lon Ranch House & Tower", file: "souko_scene", seams: "souko_scene_seams.txt" },
    { name: "Market (Child - Day)", file: "market_day_scene" },
    { name: "Market (Child - Night)", file: "market_night_scene" },
    { name: "Market (Ruins)", file: "market_ruins_scene" },
    { name: "Market Entrance (Child - Day)", file: "entra_scene" },
    { name: "Market Entrance (Child - Night)", file: "entra_n_scene" },
    { name: "Market Entrance (Ruins)", file: "enrui_scene" },
    { name: "Market Potion Shop", file: "alley_shop_scene" },
    { name: "Mido's House", file: "kokiri_home4_scene", seams: "kokiri_home4_scene_seams.txt" },
    { name: "Morpha's Lair", file: "MIZUsin_bs_scene", seams: "MIZUsin_bs_scene_seams.txt" },
    { name: "Phantom Ganon's Lair", file: "moribossroom_scene", seams: "moribossroom_scene_seams.txt" },
    { name: "Royal Family's Tomb", file: "hakaana_ouke_scene", seams: "hakaana_ouke_scene_seams.txt" },
    { name: "Saria's House", file: "kokiri_home5_scene", seams: "kokiri_home5_scene_seams.txt" },
    { name: "Shadow Temple", file: "HAKAdan_scene", seams: "HAKAdan_scene_seams.txt" },
    { name: "Shooting Gallery", file: "syatekijyou_scene", seams: "syatekijyou_scene_seams.txt" },
    { name: "Spirit Temple", file: "jyasinzou_scene", seams: "jyasinzou_scene_seams.txt" },
    { name: "Stable", file: "malon_stable_scene" },
    { name: "Temple of Time", file: "tokinoma_scene", seams: "tokinoma_scene_seams.txt" },
    { name: "Temple of Time Exterior (Day)", file: "shrine_scene" },
    { name: "Temple of Time Exterior (Night)", file: "shrine_n_scene" },
    { name: "Temple of Time Exterior (Ruins)", file: "shrine_r_scene" },
    { name: "Thieves' Hideout", file: "gerudoway_scene", seams: "gerudoway_scene_seams.txt" },
    { name: "Treasure Chest Shop", file: "takaraya_scene", seams: "takaraya_scene_seams.txt" },
    { name: "Twinrova's Lair & Iron Knuckle's Lair", file: "jyasinboss_scene", seams: "jyasinboss_scene_seams.txt" },
    { name: "Volvagia's Lair", file: "FIRE_bs_scene", seams: "FIRE_bs_scene_seams.txt" },
    { name: "Water Temple", file: "MIZUsin_scene", seams: "MIZUsin_scene_seams.txt" },
    { name: "Zora Shop", file: "zoora_scene", seams: "zoora_scene_seams.txt" }
];

const MM_Maps = [
    { name: "Ancient Castle of Ikana", file: "Z2_CASTLE", seams: "Z2_CASTLE_seams.txt" },
    { name: "Astral Observatory", file: "Z2_TENMON_DAI", seams: "Z2_TENMON_DAI_seams.txt" },
    { name: "Before the Portal to Termina", file: "Z2_OPENINGDAN", seams: "Z2_OPENINGDAN_seams.txt" },
    { name: "Beneath the Graveyard", file: "Z2_HAKASHITA", seams: "Z2_HAKASHITA_seams.txt" },
    { name: "Beneath the Well", file: "Z2_REDEAD", seams: "Z2_REDEAD_seams.txt" },
    { name: "Bomb Shop", file: "Z2_BOMYA", seams: "Z2_BOMYA_seams.txt" },
    { name: "Clock Tower Interior", file: "Z2_INSIDETOWER", seams: "Z2_INSIDETOWER_seams.txt" },
    { name: "Clock Tower Rooftop", file: "Z2_OKUJOU", seams: "Z2_OKUJOU_seams.txt" },
    { name: "Cucco Shack", file: "Z2_F01C", seams: "Z2_F01C_seams.txt" },
    { name: "Curiosity Shop", file: "Z2_AYASHIISHOP", seams: "Z2_AYASHIISHOP_seams.txt" },
    { name: "Cutscene Map", file: "SPOT00" },
    { name: "Dampe's House", file: "Z2_DANPEI2TEST", seams: "Z2_DANPEI2TEST_seams.txt" },
    { name: "Deku King's Chamber", file: "Z2_DEKU_KING", seams: "Z2_DEKU_KING_seams.txt" },
    { name: "Deku Palace", file: "Z2_22DEKUCITY", seams: "Z2_22DEKUCITY_seams.txt" },
    { name: "Deku Scrub Playground", file: "Z2_DEKUTES", seams: "Z2_DEKUTES_seams.txt" },
    { name: "Deku Shrine", file: "Z2_DANPEI", seams: "Z2_DANPEI_seams.txt" },
    { name: "Doggy Racetrack", file: "Z2_F01_B", seams: "Z2_F01_B_seams.txt" },
    { name: "East Clock Town", file: "Z2_TOWN", seams: "Z2_TOWN_seams.txt" },
    { name: "Fairy's Fountain", file: "Z2_YOUSEI_IZUMI", seams: "Z2_YOUSEI_IZUMI_seams.txt" },
    { name: "Fisherman's Hut", file: "Z2_FISHERMAN", seams: "Z2_FISHERMAN_seams.txt" },
    { name: "Ghost Hut", file: "Z2_TOUGITES" },
    { name: "Giants' Chamber", file: "Z2_KYOJINNOMA" },
    { name: "Goht's Lair", file: "Z2_HAKUGIN_BS", seams: "Z2_HAKUGIN_BS_seams.txt" },
    { name: "Gorman Track", file: "Z2_KOEPONARACE", seams: "Z2_KOEPONARACE_seams.txt" },
    { name: "Goron Graveyard", file: "Z2_GORON_HAKA", seams: "Z2_GORON_HAKA_seams.txt" },
    { name: "Goron Racetrack", file: "Z2_GORONRACE", seams: "Z2_GORONRACE_seams.txt" },
    { name: "Goron Shop", file: "Z2_GORONSHOP" },
    { name: "Goron Shrine", file: "Z2_16GORON_HOUSE", seams: "Z2_16GORON_HOUSE_seams.txt" },
    { name: "Goron Village (Spring)", file: "Z2_11GORONNOSATO2", seams: "Z2_11GORONNOSATO2_seams.txt" },
    { name: "Goron Village (Winter)", file: "Z2_11GORONNOSATO", seams: "Z2_11GORONNOSATO_seams.txt" },
    { name: "Great Bay (Cutscene)", file: "Z2_KONPEKI_ENT", seams: "Z2_KONPEKI_ENT_seams.txt" },
    { name: "Great Bay Coast", file: "Z2_30GYOSON", seams: "Z2_30GYOSON_seams.txt" },
    { name: "Great Bay Temple", file: "Z2_SEA", seams: "Z2_SEA_seams.txt" },
    { name: "Grottos", file: "KAKUSIANA", seams: "KAKUSIANA_seams.txt" },
    { name: "Gyorg's Lair", file: "Z2_SEA_BS" },
    { name: "Honey & Darling's Shop", file: "Z2_BOWLING" },
    { name: "Igos du Ikana's Lair", file: "Z2_IKNINSIDE", seams: "Z2_IKNINSIDE_seams.txt" },
    { name: "Ikana Canyon", file: "Z2_IKANA", seams: "Z2_IKANA_seams.txt" },
    { name: "Ikana Graveyard", file: "Z2_BOTI", seams: "Z2_BOTI_seams.txt" },
    { name: "Laundry Pool", file: "Z2_ALLEY", seams: "Z2_ALLEY_seams.txt" },
    { name: "Lost Woods", file: "Z2_LOST_WOODS", seams: "Z2_LOST_WOODS_seams.txt" },
    { name: "Lottery Shop", file: "Z2_TAKARAKUJI", seams: "Z2_TAKARAKUJI_seams.txt" },
    { name: "Magic Hags' Potion Shop", file: "Z2_WITCH_SHOP", seams: "Z2_WITCH_SHOP_seams.txt" },
    { name: "Majora's Lair", file: "Z2_LAST_BS", seams: "Z2_LAST_BS_seams.txt" },
    { name: "Marine Research Lab", file: "Z2_LABO", seams: "Z2_LABO_seams.txt" },
    { name: "Mayor's Residence", file: "Z2_SONCHONOIE", seams: "Z2_SONCHONOIE_seams.txt" },
    { name: "Milk Bar", file: "Z2_MILK_BAR", seams: "Z2_MILK_BAR_seams.txt" },
    { name: "Milk Road", file: "Z2_ROMANYMAE", seams: "Z2_ROMANYMAE_seams.txt" },
    { name: "Mountain Smithy", file: "Z2_KAJIYA" },
    { name: "Mountain Village (Spring)", file: "Z2_10YUKIYAMANOMURA2", seams: "Z2_10YUKIYAMANOMURA2_seams.txt" },
    { name: "Mountain Village (Winter)", file: "Z2_10YUKIYAMANOMURA", seams: "Z2_10YUKIYAMANOMURA_seams.txt" },
    { name: "Music Box House", file: "Z2_MUSICHOUSE", seams: "Z2_MUSICHOUSE_seams.txt" },
    { name: "North Clock Town", file: "Z2_BACKTOWN", seams: "Z2_BACKTOWN_seams.txt" },
    { name: "Oceanside Spider House", file: "Z2_KINDAN2", seams: "Z2_KINDAN2_seams.txt" },
    { name: "Odolwa's Lair", file: "Z2_MITURIN_BS" },
    { name: "Path to Goron Village (Spring)", file: "Z2_17SETUGEN2", seams: "Z2_17SETUGEN2_seams.txt" },
    { name: "Path to Goron Village (Winter)", file: "Z2_17SETUGEN", seams: "Z2_17SETUGEN_seams.txt" },
    { name: "Path to Mountain Village", file: "Z2_13HUBUKINOMITI", seams: "Z2_13HUBUKINOMITI_seams.txt" },
    { name: "Path to Snowhead", file: "Z2_14YUKIDAMANOMITI", seams: "Z2_14YUKIDAMANOMITI_seams.txt" },
    { name: "Pinnacle Rock", file: "Z2_SINKAI", seams: "Z2_SINKAI_seams.txt" },
    { name: "Pirates' Fortress", file: "Z2_KAIZOKU", seams: "Z2_KAIZOKU_seams.txt" },
    { name: "Pirates' Fortress Exterior", file: "Z2_TORIDE", seams: "Z2_TORIDE_seams.txt" },
    { name: "Pirates' Fortress Interior", file: "Z2_PIRATE", seams: "Z2_PIRATE_seams.txt" },
    { name: "Post Office", file: "Z2_POSTHOUSE", seams: "Z2_POSTHOUSE_seams.txt" },
    { name: "Ranch House & Barn", file: "Z2_OMOYA", seams: "Z2_OMOYA_seams.txt" },
    { name: "Road to Ikana", file: "Z2_IKANAMAE", seams: "Z2_IKANAMAE_seams.txt" },
    { name: "Road to Southern Swamp", file: "Z2_24KEMONOMITI", seams: "Z2_24KEMONOMITI_seams.txt" },
    { name: "Romani Ranch", file: "Z2_F01", seams: "Z2_F01_seams.txt" },
    { name: "Sakon's Hideout", file: "Z2_SECOM", seams: "Z2_SECOM_seams.txt" },
    { name: "Secret Shrine", file: "Z2_RANDOM", seams: "Z2_RANDOM_seams.txt" },
    { name: "Snowhead", file: "Z2_12HAKUGINMAE", seams: "Z2_12HAKUGINMAE_seams.txt" },
    { name: "Snowhead Temple", file: "Z2_HAKUGIN", seams: "Z2_HAKUGIN_seams.txt" },
    { name: "South Clock Town", file: "Z2_CLOCKTOWER", seams: "Z2_CLOCKTOWER_seams.txt" },
    { name: "Southern Swamp (Clear)", file: "Z2_20SICHITAI2", seams: "Z2_20SICHITAI2_seams.txt" },
    { name: "Southern Swamp (Poisoned)", file: "Z2_20SICHITAI", seams: "Z2_20SICHITAI_seams.txt" },
    { name: "Stock Pot Inn", file: "Z2_YADOYA", seams: "Z2_YADOYA_seams.txt" },
    { name: "Stone Tower", file: "Z2_F40", seams: "Z2_F40_seams.txt" },
    { name: "Stone Tower (Inverted)", file: "Z2_F41", seams: "Z2_F41_seams.txt" },
    { name: "Stone Tower Temple", file: "Z2_INISIE_N", seams: "Z2_INISIE_N_seams.txt" },
    { name: "Stone Tower Temple (Inverted)", file: "Z2_INISIE_R", seams: "Z2_INISIE_R_seams.txt" },
    { name: "Swamp Shooting Gallery", file: "Z2_SYATEKI_MORI", seams: "Z2_SYATEKI_MORI_seams.txt" },
    { name: "Swamp Spider House", file: "Z2_KINSTA1", seams: "Z2_KINSTA1_seams.txt" },
    { name: "Swordsman's School", file: "Z2_DOUJOU", seams: "Z2_DOUJOU_seams.txt" },
    { name: "Termina Field", file: "Z2_00KEIKOKU", seams: "Z2_00KEIKOKU_seams.txt" },
    { name: "The Moon", file: "Z2_SOUGEN", seams: "Z2_SOUGEN_seams.txt" },
    { name: "The Moon - Deku Trial", file: "Z2_LAST_DEKU", seams: "Z2_LAST_DEKU_seams.txt" },
    { name: "The Moon - Goron Trial", file: "Z2_LAST_GORON", seams: "Z2_LAST_GORON_seams.txt" },
    { name: "The Moon - Link Trial", file: "Z2_LAST_LINK" },
    { name: "The Moon - Zora Trial", file: "Z2_LAST_ZORA", seams: "Z2_LAST_ZORA_seams.txt" },
    { name: "Tourist Information", file: "Z2_MAP_SHOP", seams: "Z2_MAP_SHOP_seams.txt" },
    { name: "Town Shooting Gallery", file: "Z2_SYATEKI_MIZU" },
    { name: "Trading Post", file: "Z2_8ITEMSHOP", seams: "Z2_8ITEMSHOP_seams.txt" },
    { name: "Treasure Chest Shop", file: "Z2_TAKARAYA" },
    { name: "Twinmold's Lair", file: "Z2_INISIE_BS", seams: "Z2_INISIE_BS_seams.txt" },
    { name: "Waterfall Rapids", file: "Z2_35TAKI", seams: "Z2_35TAKI_seams.txt" },
    { name: "West Clock Town", file: "Z2_ICHIBA", seams: "Z2_ICHIBA_seams.txt" },
    { name: "Woodfall", file: "Z2_21MITURINMAE", seams: "Z2_21MITURINMAE_seams.txt" },
    { name: "Woodfall Temple", file: "Z2_MITURIN", seams: "Z2_MITURIN_seams.txt" },
    { name: "Woods of Mystery", file: "Z2_26SARUNOMORI", seams: "Z2_26SARUNOMORI_seams.txt" },
    { name: "Zora Cape", file: "Z2_31MISAKI", seams: "Z2_31MISAKI_seams.txt" },
    { name: "Zora Hall", file: "Z2_33ZORACITY", seams: "Z2_33ZORACITY_seams.txt" },
    { name: "Zora Hall Rooms", file: "Z2_BANDROOM", seams: "Z2_BANDROOM_seams.txt" }
];

const OOT3D_Maps = [
    { name: "Spot 00 - Hyrule Field", file: "spot00_info.zsi", seams: "spot00_info_seams.txt" },
    { name: "Spot 01 - Kakariko Village", file: "spot01_info.zsi", seams: "spot01_info_seams.txt" },
    { name: "Spot 02 - Graveyard", file: "spot02_info.zsi", seams: "spot02_info_seams.txt" },
    { name: "Spot 03 - Zora's River", file: "spot03_info.zsi", seams: "spot03_info_seams.txt" },
    { name: "Spot 04 - Kokiri Forest", file: "spot04_info.zsi", seams: "spot04_info_seams.txt" },
    { name: "Spot 05 - Sacred Forest Meadow", file: "spot05_info.zsi", seams: "spot05_info_seams.txt" },
    { name: "Spot 06 - Lake Hylia", file: "spot06_info.zsi", seams: "spot06_info_seams.txt" },
    { name: "Spot 07 - Zora's Domain", file: "spot07_info.zsi", seams: "spot07_info_seams.txt" },
    { name: "Spot 08 - Zora's Fountain", file: "spot08_info.zsi", seams: "spot08_info_seams.txt" },
    { name: "Spot 09 - Gerudo Valley", file: "spot09_info.zsi", seams: "spot09_info_seams.txt" },
    { name: "Spot 10 - Lost Woods", file: "spot10_info.zsi", seams: "spot10_info_seams.txt" },
    { name: "Spot 11 - Desert Colossus", file: "spot11_info.zsi", seams: "spot11_info_seams.txt" },
    { name: "Spot 12 - Gerudo's Fortress", file: "spot12_info.zsi", seams: "spot12_info_seams.txt" },
    { name: "Spot 13 - Haunted Wasteland", file: "spot13_info.zsi", seams: "spot13_info_seams.txt" },
    { name: "Spot 15 - Hyrule Castle", file: "spot15_info.zsi", seams: "spot15_info_seams.txt" },
    { name: "Spot 16 - Death Mountain Trail", file: "spot16_info.zsi", seams: "spot16_info_seams.txt" },
    { name: "Spot 17 - Death Mountain Crater", file: "spot17_info.zsi", seams: "spot17_info_seams.txt" },
    { name: "Spot 18 - Goron City", file: "spot18_info.zsi", seams: "spot18_info_seams.txt" },
    { name: "Spot 20 - Lon Lon Ranch", file: "spot20_info.zsi", seams: "spot20_info_seams.txt" },
    { name: "Spot 99 - Hyrule Field (Title)", file: "spot99_info.zsi" },
    { name: "Back Alley (Day)", file: "market_alley_info.zsi", seams: "market_alley_info_seams.txt" },
    { name: "Back Alley (Night)", file: "market_alley_n_info.zsi", seams: "market_alley_n_info_seams.txt" },
    { name: "Back Alley House (Dog Lady)", file: "kakariko_impa_info.zsi", seams: "kakariko_impa_info_seams.txt" },
    { name: "Back Alley House (Man in Green)", file: "kakariko_home3_info.zsi", seams: "kakariko_home3_info_seams.txt" },
    { name: "Barinade's Lair", file: "bdan_boss_info.zsi", seams: "bdan_boss_info_seams.txt" },
    { name: "Bazaar", file: "shop_info.zsi" },
    { name: "Bombchu Bowling Alley", file: "bowling_info.zsi", seams: "bowling_info_seams.txt" },
    { name: "Bombchu Shop", file: "shop_night_info.zsi" },
    { name: "Bongo Bongo's Lair", file: "hakadan_boss_info.zsi", seams: "hakadan_boss_info_seams.txt" },
    { name: "Bottom of the Well", file: "hakadan_ch_info.zsi", seams: "hakadan_ch_info_seams.txt" },
    { name: "Carpenter Boss's House", file: "kakariko_info.zsi", seams: "kakariko_info_seams.txt" },
    { name: "Carpenters' Tent", file: "tent_info.zsi" },
    { name: "Castle Courtyard", file: "nakaniwa_info.zsi", seams: "nakaniwa_info_seams.txt" },
    { name: "Castle Hedge Maze (Day)", file: "hairal_niwa_info.zsi", seams: "hairal_niwa_info_seams.txt" },
    { name: "Castle Hedge Maze (Night)", file: "hairal_niwa_n_info.zsi", seams: "hairal_niwa_n_info_seams.txt" },
    { name: "Chamber of the Sages", file: "kenjyanoma_info.zsi" },
    { name: "Cutscene Map", file: "hiral_demo_info.zsi" },
    { name: "Dampe's Grave & Windmill", file: "hakasitarelay_info.zsi", seams: "hakasitarelay_info_seams.txt" },
    { name: "Dodongo's Cavern", file: "ddan_info.zsi", seams: "ddan_info_seams.txt" },
    { name: "Fairy's Fountain (Healing Fairies)", file: "yousei_izumi_tate_info.zsi", seams: "yousei_izumi_tate_info_seams.txt" },
    { name: "Fire Temple", file: "hidan_info.zsi", seams: "hidan_info_seams.txt" },
    { name: "Fishing Pond", file: "turibori_info.zsi", seams: "turibori_info_seams.txt" },
    { name: "Forest Temple", file: "bmori1_info.zsi", seams: "bmori1_info_seams.txt" },
    { name: "Ganon's Castle Exterior", file: "ganon_tou_info.zsi", seams: "ganon_tou_info_seams.txt" },
    { name: "Ganon's Tower", file: "ganon_info.zsi", seams: "ganon_info_seams.txt" },
    { name: "Ganon's Tower (Collapsing)", file: "ganon_sonogo_info.zsi", seams: "ganon_sonogo_info_seams.txt" },
    { name: "Ganon's Tower Collapse & Battle Arena", file: "ganon_demo_info.zsi" },
    { name: "Ganondorf's Death Scene (Tower Escape Exterior)", file: "ganon_final_info.zsi", seams: "ganon_final_info_seams.txt" },
    { name: "Ganondorf's Lair", file: "ganon_boss_info.zsi", seams: "ganon_boss_info_seams.txt" },
    { name: "Gerudo Training Ground", file: "men_info.zsi", seams: "men_info_seams.txt" },
    { name: "Gohma's Lair", file: "ydan_boss_info.zsi", seams: "ydan_boss_info_seams.txt" },
    { name: "Goron Shop", file: "shop_golon_info.zsi", seams: "shop_golon_info_seams.txt" },
    { name: "Granny's Potion Shop", file: "mahouya_info.zsi" },
    { name: "Grave (Fairy's Fountain)", file: "hakaana2_info.zsi", seams: "hakaana2_info_seams.txt" },
    { name: "Grave (Redead)", file: "hakaana_info.zsi", seams: "hakaana_info_seams.txt" },
    { name: "Gravekeeper's Hut", file: "hut_info.zsi" },
    { name: "Great Fairy's Fountain (Spells)", file: "yousei_izumi_yoko_info.zsi", seams: "yousei_izumi_yoko_info_seams.txt" },
    { name: "Great Fairy's Fountain (Upgrades)", file: "daiyousei_izumi_info.zsi", seams: "daiyousei_izumi_info_seams.txt" },
    { name: "Grottos", file: "kakusiana_info.zsi", seams: "kakusiana_info_seams.txt" },
    { name: "Guard House", file: "miharigoya_info.zsi", seams: "miharigoya_info_seams.txt" },
    { name: "Happy Mask Shop", file: "shop_face_info.zsi", seams: "shop_face_info_seams.txt" },
    { name: "House of Skulltula", file: "kinsuta_info.zsi", seams: "kinsuta_info_seams.txt" },
    { name: "Ice Cavern", file: "ice_doukutu_info.zsi", seams: "ice_doukutu_info_seams.txt" },
    { name: "Impa's House", file: "labo_info.zsi" },
    { name: "Inside Ganon's Castle", file: "ganontika_info.zsi", seams: "ganontika_info_seams.txt" },
    { name: "Inside Ganon's Castle (Collapsing)", file: "ganontikasonogo_info.zsi", seams: "ganontikasonogo_info_seams.txt" },
    { name: "Inside Jabu-Jabu's Belly", file: "bdan_info.zsi", seams: "bdan_info_seams.txt" },
    { name: "Inside the Deku Tree", file: "ydan_info.zsi", seams: "ydan_info_seams.txt" },
    { name: "Kakariko Potion Shop", file: "shop_drag_info.zsi" },
    { name: "King Dodongo's Lair", file: "ddan_boss_info.zsi", seams: "ddan_boss_info_seams.txt" },
    { name: "Know-It-All Brothers' House", file: "k_home_info.zsi", seams: "k_home_info_seams.txt" },
    { name: "Kokiri Shop", file: "kokiri_info.zsi" },
    { name: "Lakeside Laboratory", file: "hylia_labo_info.zsi", seams: "hylia_labo_info_seams.txt" },
    { name: "Link's House", file: "link_info.zsi", seams: "link_info_seams.txt" },
    { name: "Lon Lon Ranch House & Tower", file: "souko_info.zsi", seams: "souko_info_seams.txt" },
    { name: "Market (Child - Day)", file: "market_day_info.zsi" },
    { name: "Market (Child - Night)", file: "market_night_info.zsi" },
    { name: "Market (Ruins)", file: "market_ruins_info.zsi" },
    { name: "Market Entrance (Child - Day)", file: "entra_day_info.zsi" },
    { name: "Market Entrance (Child - Night)", file: "entra_night_info.zsi" },
    { name: "Market Entrance (Ruins)", file: "entra_ruins_info.zsi" },
    { name: "Market Potion Shop", file: "shop_alley_info.zsi" },
    { name: "Mido's House", file: "k_home4_info.zsi", seams: "k_home4_info_seams.txt" },
    { name: "Morpha's Lair", file: "mizusin_boss_info.zsi", seams: "mizusin_boss_info_seams.txt" },
    { name: "Phantom Ganon's Lair", file: "moriboss_info.zsi", seams: "moriboss_info_seams.txt" },
    { name: "Royal Family's Tomb", file: "hakaana_ouke_info.zsi", seams: "hakaana_ouke_info_seams.txt" },
    { name: "Saria's House", file: "k_home5_info.zsi", seams: "k_home5_info_seams.txt" },
    { name: "Shadow Temple", file: "hakadan_info.zsi", seams: "hakadan_info_seams.txt" },
    { name: "Shooting Gallery", file: "syatekijyou_info.zsi", seams: "syatekijyou_info_seams.txt" },
    { name: "Spirit Temple", file: "jyasinzou_info.zsi", seams: "jyasinzou_info_seams.txt" },
    { name: "Stable", file: "stable_info.zsi", seams: "stable_info_seams.txt" },
    { name: "Temple of Time", file: "tokinoma_info.zsi", seams: "tokinoma_info_seams.txt" },
    { name: "Temple of Time Exterior (Day)", file: "shrine_info.zsi" },
    { name: "Temple of Time Exterior (Night)", file: "shrine_n_info.zsi" },
    { name: "Temple of Time Exterior (Ruins)", file: "shrine_r_info.zsi" },
    { name: "Thieves' Hideout", file: "gerudoway_info.zsi", seams: "gerudoway_info_seams.txt" },
    { name: "Treasure Chest Shop", file: "takaraya_info.zsi", seams: "takaraya_info_seams.txt" },
    { name: "Twinrova's Lair & Iron Knuckle Mini-Boss Room", file: "jyasinzou_boss_info.zsi", seams: "jyasinzou_boss_info_seams.txt" },
    { name: "Twins' House", file: "k_home3_info.zsi", seams: "k_home3_info_seams.txt" },
    { name: "Volvagia's Lair", file: "fire_bs_info.zsi", seams: "fire_bs_info_seams.txt" },
    { name: "Water Temple", file: "mizusin_info.zsi", seams: "mizusin_info_seams.txt" },
    { name: "Zora Shop", file: "zoora_info.zsi", seams: "zoora_info_seams.txt" }
    //{ name: "Bottom of the Well (MQ)", file: "hakadan_ch_dd_info.zsi" },
    //{ name: "Dodongo's Cavern (MQ)", file: "ddan_dd_info.zsi" },
    //{ name: "Fire Temple (MQ)", file: "hidan_dd_info.zsi" },
    //{ name: "Forest Temple (MQ)", file: "bmori1_dd_info.zsi" },
    //{ name: "Gerudo Training Ground (MQ)", file: "men_dd_info.zsi" },
    //{ name: "Ice Cavern (MQ)", file: "ice_doukutu_dd_info.zsi" },
    //{ name: "Inside Ganon's Castle (MQ)", file: "ganontika_dd_info.zsi" },
    //{ name: "Inside Jabu-Jabu's Belly (MQ)", file: "bdan_dd_info.zsi" },
    //{ name: "Inside the Deku Tree (MQ)", file: "ydan_dd_info.zsi" },
    //{ name: "Shadow Temple (MQ)", file: "hakadan_dd_info.zsi" },
    //{ name: "Spirit Temple (MQ)", file: "jyasinzou_dd_info.zsi" },
    //{ name: "Water Temple (MQ)", file: "mizusin_dd_info.zsi" }
];

const MM3D_Maps = [
    { name: "Ancient Castle of Ikana", file: "z2_castle_info.zsi", seams: "z2_castle_info_seams.txt" },
    { name: "Astral Observatory", file: "z2_tenmon_dai_info.zsi", seams: "z2_tenmon_dai_info_seams.txt" },
    { name: "Before the Portal to Termina", file: "z2_openingdan_info.zsi", seams: "z2_openingdan_info_seams.txt" },
    { name: "Beneath the Graves", file: "z2_hakashita_info.zsi", seams: "z2_hakashita_info_seams.txt" },
    { name: "Beneath the Well", file: "z2_redead_info.zsi", seams: "z2_redead_info_seams.txt" },
    { name: "Bomb Shop", file: "z2_bomya_info.zsi", seams: "z2_bomya_info_seams.txt" },
    { name: "Clock Tower Interior", file: "z2_insidetower_info.zsi", seams: "z2_insidetower_info_seams.txt" },
    { name: "Clock Tower Rooftop", file: "z2_okujou_info.zsi", seams: "z2_okujou_info_seams.txt" },
    { name: "Cucco Shack", file: "z2_f01c_info.zsi", seams: "z2_f01c_info_seams.txt" },
    { name: "Curiosity Shop & Kafei's Hideout", file: "z2_ayashiishop_info.zsi", seams: "z2_ayashiishop_info_seams.txt" },
    { name: "Cutscene Map", file: "spot00_info.zsi" },
    { name: "Dampe's House", file: "z2_danpei2test_info.zsi", seams: "z2_danpei2test_info_seams.txt" },
    { name: "Deku King's Chamber", file: "z2_deku_king_info.zsi", seams: "z2_deku_king_info_seams.txt" },
    { name: "Deku Palace", file: "z2_22dekucity_info.zsi", seams: "z2_22dekucity_info_seams.txt" },
    { name: "Deku Scrub Playground", file: "z2_dekutes_info.zsi", seams: "z2_dekutes_info_seams.txt" },
    { name: "Deku Shrine", file: "z2_danpei_info.zsi", seams: "z2_danpei_info_seams.txt" },
    { name: "Doggy Racetrack", file: "z2_f01_b_info.zsi", seams: "z2_f01_b_info_seams.txt" },
    { name: "East Clock Town", file: "z2_town_info.zsi", seams: "z2_town_info_seams.txt" },
    { name: "Fairy's Fountain", file: "z2_yousei_izumi_info.zsi", seams: "z2_yousei_izumi_info_seams.txt" },
    { name: "Fisherman's Hut", file: "z2_fisherman_info.zsi", seams: "z2_fisherman_info_seams.txt" },
    { name: "Ghost Hut", file: "z2_tougites_info.zsi", seams: "z2_tougites_info_seams.txt" },
    { name: "Giants' Chamber", file: "z2_kyojinnoma_info.zsi" },
    { name: "Goht's Lair", file: "z2_hakugin_bs_info.zsi", seams: "z2_hakugin_bs_info_seams.txt" },
    { name: "Gorman Track", file: "z2_koeponarace_info.zsi", seams: "z2_koeponarace_info_seams.txt" },
    { name: "Goron Graveyard", file: "z2_goron_haka_info.zsi", seams: "z2_goron_haka_info_seams.txt" },
    { name: "Goron Racetrack", file: "z2_goronrace_info.zsi", seams: "z2_goronrace_info_seams.txt" },
    { name: "Goron Shop", file: "z2_goronshop_info.zsi", seams: "z2_goronshop_info_seams.txt" },
    { name: "Goron Shrine", file: "z2_16goron_house_info.zsi", seams: "z2_16goron_house_info_seams.txt" },
    { name: "Goron Village (Spring)", file: "z2_11goronnosato2_info.zsi", seams: "z2_11goronnosato2_info_seams.txt" },
    { name: "Goron Village (Winter)", file: "z2_11goronnosato_info.zsi", seams: "z2_11goronnosato_info_seams.txt" },
    { name: "Great Bay Temple", file: "z2_sea_info.zsi", seams: "z2_sea_info_seams.txt" },
    { name: "Great Bay Coast", file: "z2_30gyoson_info.zsi", seams: "z2_30gyoson_info_seams.txt" },
    { name: "Great Bay Coast (Cutscene)", file: "z2_konpeki_ent_info.zsi", seams: "z2_konpeki_ent_info_seams.txt" },
    { name: "Grottos", file: "kakusiana_info.zsi", seams: "kakusiana_info_seams.txt" },
    { name: "Gyorg's Lair", file: "z2_sea_bs_info.zsi" },
    { name: "Honey & Darling's Shop", file: "z2_bowling_info.zsi" },
    { name: "Igos du Ikana's Lair", file: "z2_ikninside_info.zsi", seams: "z2_ikninside_info_seams.txt" },
    { name: "Ikana Canyon", file: "z2_ikana_info.zsi", seams: "z2_ikana_info_seams.txt" },
    { name: "Ikana Graveyard", file: "z2_boti_info.zsi", seams: "z2_boti_info_seams.txt" },
    { name: "Laundry Pool", file: "z2_alley_info.zsi", seams: "z2_alley_info_seams.txt" },
    { name: "Lost Woods", file: "z2_lost_woods_info.zsi", seams: "z2_lost_woods_info_seams.txt" },
    { name: "Lottery Shop", file: "z2_takarakuji_info.zsi", seams: "z2_takarakuji_info_seams.txt" },
    { name: "Magic Hags' Potion Shop", file: "z2_witch_shop_info.zsi", seams: "z2_witch_shop_info_seams.txt" },
    { name: "Majora's Lair", file: "z2_last_bs_info.zsi", seams: "z2_last_bs_info_seams.txt" },
    { name: "Marine Research Lab", file: "z2_labo_info.zsi", seams: "z2_labo_info_seams.txt" },
    { name: "Mayor's Residence", file: "z2_sonchonoie_info.zsi", seams: "z2_sonchonoie_info_seams.txt" },
    { name: "Milk Bar", file: "z2_milk_bar_info.zsi", seams: "z2_milk_bar_info_seams.txt" },
    { name: "Milk Road", file: "z2_romanymae_info.zsi", seams: "z2_romanymae_info_seams.txt" },
    { name: "Mountain Smithy", file: "z2_kajiya_info.zsi" },
    { name: "Mountain Village (Spring)", file: "z2_10yukiyamanomura2_info.zsi", seams: "z2_10yukiyamanomura2_info_seams.txt" },
    { name: "Mountain Village (Winter)", file: "z2_10yukiyamanomura_info.zsi", seams: "z2_10yukiyamanomura_info_seams.txt" },
    { name: "Music Box House", file: "z2_musichouse_info.zsi", seams: "z2_musichouse_info_seams.txt" },
    { name: "North Clock Town", file: "z2_backtown_info.zsi", seams: "z2_backtown_info_seams.txt" },
    { name: "Ocean Fishing Hole", file: "z2_turibori2_info.zsi" },
    { name: "Oceanside Spider House", file: "z2_kindan2_info.zsi", seams: "z2_kindan2_info_seams.txt" },
    { name: "Odolwa's Lair", file: "z2_miturin_bs_info.zsi", seams: "z2_miturin_bs_info_seams.txt" },
    { name: "Path to Goron Village (Spring)", file: "z2_17setugen2_info.zsi", seams: "z2_17setugen2_info_seams.txt" },
    { name: "Path to Goron Village (Winter)", file: "z2_17setugen_info.zsi", seams: "z2_17setugen_info_seams.txt" },
    { name: "Path to Mountain Village", file: "z2_13hubukinomiti_info.zsi", seams: "z2_13hubukinomiti_info_seams.txt" },
    { name: "Path to Snowhead", file: "z2_14yukidamanomiti_info.zsi", seams: "z2_14yukidamanomiti_info_seams.txt" },
    { name: "Pinnacle Rock", file: "z2_sinkai_info.zsi", seams: "z2_sinkai_info_seams.txt" },
    { name: "Pirates' Fortress", file: "z2_kaizoku_info.zsi", seams: "z2_kaizoku_info_seams.txt" },
    { name: "Pirates' Fortress Exterior", file: "z2_toride_info.zsi", seams: "z2_toride_info_seams.txt" },
    { name: "Pirates' Fortress Interior", file: "z2_pirate_info.zsi", seams: "z2_pirate_info_seams.txt" },
    { name: "Post Office", file: "z2_posthouse_info.zsi", seams: "z2_posthouse_info_seams.txt" },
    { name: "Ranch House & Barn", file: "z2_omoya_info.zsi", seams: "z2_omoya_info_seams.txt" },
    { name: "Road to Ikana", file: "z2_ikanamae_info.zsi", seams: "z2_ikanamae_info_seams.txt" },
    { name: "Road to Southern Swamp", file: "z2_24kemonomiti_info.zsi", seams: "z2_24kemonomiti_info_seams.txt" },
    { name: "Romani Ranch", file: "z2_f01_info.zsi", seams: "z2_f01_info_seams.txt" },
    { name: "Sakon's Hideout", file: "z2_secom_info.zsi", seams: "z2_secom_info_seams.txt" },
    { name: "Secret Shrine", file: "z2_random_info.zsi", seams: "z2_random_info_seams.txt" },
    { name: "Snowhead", file: "z2_12hakuginmae_info.zsi", seams: "z2_12hakuginmae_info_seams.txt" },
    { name: "Snowhead Temple", file: "z2_hakugin_info.zsi", seams: "z2_hakugin_info_seams.txt" },
    { name: "South Clock Town", file: "z2_clocktower_info.zsi", seams: "z2_clocktower_info_seams.txt" },
    { name: "Southern Swamp (Clear)", file: "z2_20sichitai2_info.zsi", seams: "z2_20sichitai2_info_seams.txt" },
    { name: "Southern Swamp (Poisoned)", file: "z2_20sichitai_info.zsi", seams: "z2_20sichitai_info_seams.txt" },
    { name: "Stock Pot Inn", file: "z2_yadoya_info.zsi", seams: "z2_yadoya_info_seams.txt" },
    { name: "Stone Tower", file: "z2_f40_info.zsi", seams: "z2_f40_info_seams.txt" },
    { name: "Stone Tower (Inverted)", file: "z2_f41_info.zsi", seams: "z2_f41_info_seams.txt" },
    { name: "Stone Tower Temple", file: "z2_inisie_n_info.zsi", seams: "z2_inisie_n_info_seams.txt" },
    { name: "Stone Tower Temple (Inverted)", file: "z2_inisie_r_info.zsi", seams: "z2_inisie_r_info_seams.txt" },
    { name: "Swamp Fishing Hole", file: "z2_turibori_info.zsi" },
    { name: "Swamp Shooting Gallery", file: "z2_syateki_mori_info.zsi", seams: "z2_syateki_mori_info_seams.txt" },
    { name: "Swamp Spider House", file: "z2_kinsta1_info.zsi", seams: "z2_kinsta1_info_seams.txt" },
    { name: "Swordsman's School", file: "z2_doujou_info.zsi", seams: "z2_doujou_info_seams.txt" },
    { name: "Termina Field", file: "z2_00keikoku_info.zsi", seams: "z2_00keikoku_info_seams.txt" },
    { name: "Termina Field (Credits Cutscene)", file: "z2_01keikoku_info.zsi" },
    { name: "Termina Field (Credits Cutscene)", file: "z2_02keikoku_info.zsi" },
    { name: "Test Map 01", file: "test01_info.zsi", seams: "test01_info_seams.txt" },
    { name: "Test Map 02", file: "test02_info.zsi" },
    { name: "The Moon", file: "z2_sougen_info.zsi", seams: "z2_sougen_info_seams.txt" },
    { name: "The Moon - Deku Trial", file: "z2_last_deku_info.zsi", seams: "z2_last_deku_info_seams.txt" },
    { name: "The Moon - Goron Trial", file: "z2_last_goron_info.zsi", seams: "z2_last_goron_info_seams.txt" },
    { name: "The Moon - Link Trial", file: "z2_last_link_info.zsi", seams: "z2_last_link_info_seams.txt" },
    { name: "The Moon - Zora Trial", file: "z2_last_zora_info.zsi", seams: "z2_last_zora_info_seams.txt" },
    { name: "Tourist Information", file: "z2_map_shop_info.zsi", seams: "z2_map_shop_info_seams.txt" },
    { name: "Town Shooting Gallery", file: "z2_syateki_mizu_info.zsi", seams: "z2_syateki_mizu_info_seams.txt" },
    { name: "Trading Post", file: "z2_8itemshop_info.zsi", seams: "z2_8itemshop_info_seams.txt" },
    { name: "Treasure Chest Shop", file: "z2_takaraya_info.zsi" },
    { name: "Twinmold's Lair", file: "z2_inisie_bs_info.zsi", seams: "z2_inisie_bs_info_seams.txt" },
    { name: "Waterfall Rapids", file: "z2_35taki_info.zsi", seams: "z2_35taki_info_seams.txt" },
    { name: "West Clock Town", file: "z2_ichiba_info.zsi", seams: "z2_ichiba_info_seams.txt" },
    { name: "Woodfall", file: "z2_21miturinmae_info.zsi", seams: "z2_21miturinmae_info_seams.txt" },
    { name: "Woodfall Temple", file: "z2_miturin_info.zsi", seams: "z2_miturin_info_seams.txt" },
    { name: "Woods of Mystery", file: "z2_26sarunomori_info.zsi", seams: "z2_26sarunomori_info_seams.txt" },
    { name: "Zora Cape", file: "z2_31misaki_info.zsi", seams: "z2_31misaki_info_seams.txt" },
    { name: "Zora Hall", file: "z2_33zoracity_info.zsi", seams: "z2_33zoracity_info_seams.txt" },
    { name: "Zora Hall Rooms", file: "z2_bandroom_info.zsi", seams: "z2_bandroom_info_seams.txt" },
    { name: "32kamejimamae", file: "z2_32kamejimamae_info.zsi" },
    { name: "meganeana", file: "z2_meganeana_info.zsi" },
    { name: "zolashop", file: "z2_zolashop_info.zsi" }
];
