#!/usr/bin/env python3
"""
Generate js/bk_object_list.js (BK actor / model / sprite name tables) from the
banjo-kazooie decomp's include/enums.h.

usage: generate_bk_object_list.py <path/to/banjo-kazooie> [out.js]

Names come from two places inside each enum block:
  - the enumerator itself, whose name embeds its hex id (ACTOR_2A_GOLD_BULLION,
    ASSET_14CF_MODEL_SM_SPIRAL_MOUNTAIN_OPA)
  - "// 2ff MM Tree" style comment lines the decomp uses for ids that have no
    enumerator yet
"""

import os
import re
import sys


def enum_block(src, name):
    m = re.search(r"enum %s\s*\{(.*?)\};" % name, src, re.S)
    if not m:
        sys.exit("enum %s not found" % name)
    return m.group(1)


def parse_names(block, prefix):
    names = {}
    for m in re.finditer(r"\b%s_([0-9A-Fa-f]+)_(\w+)" % prefix, block):
        names.setdefault(int(m.group(1), 16), m.group(2))
    return names


def parse_comment_names(block):
    """'// 2ff MM Tree' -> {0x2ff: 'MM Tree'}; 'Unused' lines are skipped."""
    names = {}
    for m in re.finditer(r"^\s*//\s*([0-9A-Fa-f]{2,4})\s+(.+?)\s*$", block, re.M):
        text = m.group(2).strip()
        if text.lower().startswith("unused"):
            continue
        names.setdefault(int(m.group(1), 16), text)
    return names


def parse_actor_models(repo):
    """actorId -> model asset id from every `ActorInfo x = { marker, actor, model, ...}` in src/.

    Ids are written either as enum names (which embed the hex id) or as plain
    numbers. ActorInfo.modelId is a raw asset id (assetcache_get(marker->modelId)),
    NOT offset by 0x2D1 like ModelProp.modelId. A model of 0 / NULL means the
    actor is invisible (a trigger); those are left out.
    """
    src = []
    for root, _dirs, files in os.walk(os.path.join(repo, "src")):
        for name in files:
            if name.endswith(".c"):
                with open(os.path.join(root, name), encoding="utf-8", errors="replace") as f:
                    src.append(f.read())
    src = "\n".join(src)

    def value(text, prefix):
        text = text.strip()
        m = re.match(r"%s_([0-9A-Fa-f]+)_" % prefix, text)
        if m:
            return int(m.group(1), 16)
        if re.fullmatch(r"0x[0-9A-Fa-f]+|\d+", text):
            return int(text, 0)
        return None

    models = {}
    for _marker, actor, model in re.findall(
            r"\bActorInfo\s+\w+\s*=\s*\{\s*([^,]+),\s*([^,]+),\s*([^,]+),", src, re.S):
        actor_id = value(actor, "ACTOR")
        model_id = value(model, "ASSET")
        if actor_id and model_id:
            models.setdefault(actor_id, model_id)
    return models


def js_table(var, values, comment, fmt='"%s"'):
    lines = ["// %s" % comment, "const %s = {" % var]
    for uid in sorted(values):
        lines.append(("    0x%X: " + fmt + ",") % (uid, values[uid]))
    lines.append("};")
    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    repo = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..", "js", "bk_object_list.js")

    with open(os.path.join(repo, "include", "enums.h"), encoding="utf-8") as f:
        src = f.read()

    actors = parse_names(enum_block(src, "actor_e"), "ACTOR")

    asset_block = enum_block(src, "asset_e")
    asset_names = parse_names(asset_block, "ASSET")
    asset_comments = parse_comment_names(asset_block)

    # Enumerator names win over comments; strip the MODEL_/SPRITE_ prefix so
    # the table reads the same whichever source a name came from.
    models = {}
    sprites = {}
    for uid, name in asset_names.items():
        if name.startswith("MODEL_"):
            models[uid] = name[len("MODEL_"):]
        elif name.startswith("SPRITE_"):
            sprites[uid] = name[len("SPRITE_"):]
    for uid, text in asset_comments.items():
        if 0x2D1 <= uid < 0x572:
            models.setdefault(uid, text)
        elif 0x572 <= uid < 0x71C:
            sprites.setdefault(uid, text)

    actor_models = parse_actor_models(repo)

    header = (
        "// Generated by tools/bk/generate_bk_object_list.py from the banjo-kazooie\n"
        "// decomp's include/enums.h and the ActorInfo tables in src/. Do not edit by hand.\n"
        "//\n"
        "// Keys are the ids as they appear in a map's setup.bin:\n"
        "//   BK_Actor_Names  - NodeProp.actorId (enum actor_e)\n"
        "//   BK_Model_Names  - asset id; ModelProp.modelId + 0x2D1 (MODEL_ASSET_OFFSET)\n"
        "//   BK_Sprite_Names - asset id; SpriteProp.spriteId + 0x572 (SPRITE_ASSET_OFFSET)\n"
        "//   BK_Actor_Models - NodeProp.actorId -> model asset id (ActorInfo.modelId); invisible actors omitted\n\n"
    )
    body = "\n\n".join([
        js_table("BK_Actor_Names", actors, "enum actor_e"),
        js_table("BK_Model_Names", models, "model assets 0x2D1..0x571"),
        js_table("BK_Sprite_Names", sprites, "sprite assets 0x572..0x71B"),
        js_table("BK_Actor_Models", {k: "0x%X" % v for k, v in actor_models.items()},
                 "ActorInfo.modelId per actor", fmt="%s"),
    ])
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + body + "\n")
    print("%s: %d actors, %d models, %d sprites, %d actor->model links" % (
        out, len(actors), len(models), len(sprites), len(actor_models)))


if __name__ == "__main__":
    main()
