#!/usr/bin/env python3
"""
Generate js/bt_object_list.js (BT setup-file lookup tables and the sky table)
from models/BT/tables.json, the tables banjo-tooie/tools/extract_maps.py pulls
out of the gsproplookup, gemarkersDll and gcskyDll overlays.

usage: generate_bt_object_list.py [models/BT/tables.json] [js/bt_object_list.js] [--names bt_assets.py]

--names: an optional community asset-name table (the banjo-memory-viewer's
bt_assets.py, "0x5DC: {... "name": "Model: Wood Plank"}" lines) used to label
prop models. Defaults to ../banjo-memory-viewer/bt_assets.py next to this
repo when present.
"""

import argparse
import json
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")


def load_names(path):
    names = {}
    if not path or not os.path.exists(path):
        return names
    with open(path, encoding="utf-8") as f:
        for m in re.finditer(r'0x([0-9A-Fa-f]+):\s*\{[^}]*"name":\s*"([^"]*)"', f.read()):
            name = m.group(2).strip()
            if name and name not in ("?", "X"):
                names[int(m.group(1), 16)] = name
    return names


def js_map(name, entries, comment):
    lines = ["// %s" % comment, "const %s = {" % name]
    for k, v in entries:
        lines.append("    %s: %s," % (k, json.dumps(v)))
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("tables", nargs="?", default=os.path.join(ROOT, "models", "BT", "tables.json"))
    ap.add_argument("out", nargs="?", default=os.path.join(ROOT, "js", "bt_object_list.js"))
    ap.add_argument("--names", default=os.path.join(ROOT, "..", "banjo-memory-viewer", "bt_assets.py"))
    args = ap.parse_args()

    with open(args.tables, encoding="utf-8") as f:
        tables = json.load(f)
    names = load_names(args.names)

    prop_models = [("0x%X" % i, a) for i, a in enumerate(tables["prop_models"]) if a]
    prop_sprites = [("0x%X" % i, a) for i, a in enumerate(tables["prop_sprites"]) if a]
    actor_overlays = [("0x%X" % int(k), "%s#%d" % (v[0], v[1])) for k, v in tables["actor_overlays"].items()]
    actor_models = [("0x%X" % int(k), v) for k, v in tables["actor_models"].items() if v]
    actor_sprites = [("0x%X" % int(k), v) for k, v in tables.get("actor_sprites", {}).items() if v]
    extra_models = [int(k) for k in tables.get("extra_models", {})]
    extra_sprites = [int(k) for k in tables.get("extra_sprites", {})]
    skies = [("0x%X" % sky["map_id"], [{"model": l["model"], "scale": l["scale"], "speed": l["speed"]} for l in sky["layers"]])
             for sky in tables.get("skies", [])]
    sky_models = {l["model"] for _, layers in skies for l in layers}
    asset_names = sorted({a for _, a in prop_models} | {a for _, a in prop_sprites} | {a for _, a in actor_models}
                         | {a for _, a in actor_sprites} | set(extra_models) | set(extra_sprites) | sky_models)
    asset_names = [("0x%X" % a, names[a]) for a in asset_names if a in names]

    blocks = [
        "// Generated by tools/bt/generate_bt_object_list.py from models/BT/tables.json\n"
        "// (banjo-tooie/tools/extract_maps.py). Do not edit by hand.",
        js_map("BT_Prop_Models", prop_models,
               "gsproplookup: model prop id (Prop.modelId, the prop's u16 >> 4) -> model asset id"),
        js_map("BT_Prop_Sprites", prop_sprites,
               "gsproplookup: sprite prop id -> sprite asset id"),
        js_map("BT_Actor_Overlays", actor_overlays,
               "gemarkersDll: actor id -> the ch*/gl* overlay (and entrypoint) that spawns it; "
               "ids missing here are handled by core code"),
        js_map("BT_Actor_Models", actor_models,
               "actor id -> model asset id, from the actor-info struct in its overlay's data "
               "(missing: model-less actor, or its struct was not found)"),
        js_map("BT_Actor_Sprites", actor_sprites,
               "actor id -> sprite asset id, for the actors whose info struct names a sprite "
               "(eggs, feathers, the light halo): drawn as billboards, see bt_setup.js"),
        js_map("BT_Skies", skies,
               "gcskyDll: map id -> sky layers [{model asset, uniform scale, rotation deg/s}], "
               "drawn centred on the camera before the map (see sky.js)"),
        js_map("BT_Asset_Names", asset_names,
               "Community names for the model and sprite assets above, the ones actor code loads itself "
               "(tables.json extra_models / extra_sprites) and the sky models; optional"),
    ]
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n\n".join(blocks) + "\n")
    print("wrote %s: %d prop models, %d sprites, %d actor overlays, %d actor models, %d actor sprites, %d skies, %d names" % (
        args.out, len(prop_models), len(prop_sprites), len(actor_overlays), len(actor_models), len(actor_sprites), len(skies), len(asset_names)))


if __name__ == "__main__":
    main()
