import os
import json
import re

# Original OOT3D_Maps array as Python list of dicts
MM3D_Maps = [
	{ "name": "Ancient Castle of Ikana", "file": "z2_castle_info.zsi" },
	{ "name": "Astral Observatory", "file": "z2_tenmon_dai_info.zsi" },
	{ "name": "Before the Portal to Termina", "file": "z2_openingdan_info.zsi" },
	{ "name": "Beneath the Graves", "file": "z2_hakashita_info.zsi" },
	{ "name": "Beneath the Well", "file": "z2_redead_info.zsi" },
	{ "name": "Bomb Shop", "file": "z2_bomya_info.zsi" },
	{ "name": "Clock Tower Interior", "file": "z2_insidetower_info.zsi" },
	{ "name": "Clock Tower Rooftop", "file": "z2_okujou_info.zsi" },
	{ "name": "Cucco Shack", "file": "z2_f01c_info.zsi" },
	{ "name": "Curiosity Shop & Kafei's Hideout", "file": "z2_ayashiishop_info.zsi" },
	{ "name": "Cutscene Map", "file": "spot00_info.zsi" },
	{ "name": "Dampe's House", "file": "z2_danpei2test_info.zsi" },
	{ "name": "Deku King's Chamber", "file": "z2_deku_king_info.zsi" },
	{ "name": "Deku Palace", "file": "z2_22dekucity_info.zsi" },
	{ "name": "Deku Scrub Playground", "file": "z2_dekutes_info.zsi" },
	{ "name": "Deku Shrine", "file": "z2_danpei_info.zsi" },
	{ "name": "Doggy Racetrack", "file": "z2_f01_b_info.zsi" },
	{ "name": "East Clock Town", "file": "z2_town_info.zsi" },
	{ "name": "Fairy's Fountain", "file": "z2_yousei_izumi_info.zsi" },
	{ "name": "Fisherman's Hut", "file": "z2_fisherman_info.zsi" },
	{ "name": "Ghost Hut", "file": "z2_tougites_info.zsi" },
	{ "name": "Giants' Chamber", "file": "z2_kyojinnoma_info.zsi" },
	{ "name": "Goht's Lair", "file": "z2_hakugin_bs_info.zsi" },
	{ "name": "Gorman Track", "file": "z2_koeponarace_info.zsi" },
	{ "name": "Goron Graveyard", "file": "z2_goron_haka_info.zsi" },
	{ "name": "Goron Racetrack", "file": "z2_goronrace_info.zsi" },
	{ "name": "Goron Shop", "file": "z2_goronshop_info.zsi" },
	{ "name": "Goron Shrine", "file": "z2_16goron_house_info.zsi" },
	{ "name": "Goron Village (Spring)", "file": "z2_11goronnosato2_info.zsi" },
	{ "name": "Goron Village (Winter)", "file": "z2_11goronnosato_info.zsi" },
	{ "name": "Great Bay Temple", "file": "z2_sea_info.zsi" },
	{ "name": "Great Bay Coast", "file": "z2_30gyoson_info.zsi" },
	{ "name": "Great Bay Coast (Cutscene)", "file": "z2_konpeki_ent_info.zsi" },
	{ "name": "Grottos", "file": "kakusiana_info.zsi" },
	{ "name": "Gyorg's Lair", "file": "z2_sea_bs_info.zsi" },
	{ "name": "Honey & Darling's Shop", "file": "z2_bowling_info.zsi" },
	{ "name": "Igos du Ikana's Lair", "file": "z2_ikninside_info.zsi" },
	{ "name": "Ikana Canyon", "file": "z2_ikana_info.zsi" },
	{ "name": "Ikana Graveyard", "file": "z2_boti_info.zsi" },
	{ "name": "Laundry Pool", "file": "z2_alley_info.zsi" },
	{ "name": "Lost Woods", "file": "z2_lost_woods_info.zsi" },
	{ "name": "Lottery Shop", "file": "z2_takarakuji_info.zsi" },
	{ "name": "Magic Hags' Potion Shop", "file": "z2_witch_shop_info.zsi" },
	{ "name": "Majora's Lair", "file": "z2_last_bs_info.zsi" },
	{ "name": "Marine Research Lab", "file": "z2_labo_info.zsi" },
	{ "name": "Mayor's Residence", "file": "z2_sonchonoie_info.zsi" },
	{ "name": "Milk Bar", "file": "z2_milk_bar_info.zsi" },
	{ "name": "Milk Road", "file": "z2_romanymae_info.zsi" },
	{ "name": "Mountain Smithy", "file": "z2_kajiya_info.zsi" },
	{ "name": "Mountain Village (Spring)", "file": "z2_10yukiyamanomura2_info.zsi" },
	{ "name": "Mountain Village (Winter)", "file": "z2_10yukiyamanomura_info.zsi" },
	{ "name": "Music Box House", "file": "z2_musichouse_info.zsi" },
	{ "name": "North Clock Town", "file": "z2_backtown_info.zsi" },
	{ "name": "Ocean Fishing Hole", "file": "z2_turibori2_info.zsi" },
	{ "name": "Oceanside Spider House", "file": "z2_kindan2_info.zsi" },
	{ "name": "Odolwa's Lair", "file": "z2_miturin_bs_info.zsi" },
	{ "name": "Path to Goron Village (Spring)", "file": "z2_17setugen2_info.zsi" },
	{ "name": "Path to Goron Village (Winter)", "file": "z2_17setugen_info.zsi" },
	{ "name": "Path to Mountain Village", "file": "z2_13hubukinomiti_info.zsi" },
	{ "name": "Path to Snowhead", "file": "z2_14yukidamanomiti_info.zsi" },
	{ "name": "Pinnacle Rock", "file": "z2_sinkai_info.zsi" },
	{ "name": "Pirates' Fortress", "file": "z2_kaizoku_info.zsi" },
	{ "name": "Pirates' Fortress Exterior", "file": "z2_toride_info.zsi" },
	{ "name": "Pirates' Fortress Interior", "file": "z2_pirate_info.zsi" },
	{ "name": "Post Office", "file": "z2_posthouse_info.zsi" },
	{ "name": "Ranch House & Barn", "file": "z2_omoya_info.zsi" },
	{ "name": "Road to Ikana", "file": "z2_ikanamae_info.zsi" },
	{ "name": "Road to Southern Swamp", "file": "z2_24kemonomiti_info.zsi" },
	{ "name": "Romani Ranch", "file": "z2_f01_info.zsi" },
	{ "name": "Sakon's Hideout", "file": "z2_secom_info.zsi" },
	{ "name": "Secret Shrine", "file": "z2_random_info.zsi" },
	{ "name": "Snowhead", "file": "z2_12hakuginmae_info.zsi" },
	{ "name": "Snowhead Temple", "file": "z2_hakugin_info.zsi" },
	{ "name": "South Clock Town", "file": "z2_clocktower_info.zsi" },
	{ "name": "Southern Swamp (Clear)", "file": "z2_20sichitai2_info.zsi" },
	{ "name": "Southern Swamp (Poisoned)", "file": "z2_20sichitai_info.zsi" },
	{ "name": "Stock Pot Inn", "file": "z2_yadoya_info.zsi" },
	{ "name": "Stone Tower", "file": "z2_f40_info.zsi" },
	{ "name": "Stone Tower (Inverted)", "file": "z2_f41_info.zsi" },
	{ "name": "Stone Tower Temple", "file": "z2_inisie_n_info.zsi" },
	{ "name": "Stone Tower Temple (Inverted)", "file": "z2_inisie_r_info.zsi" },
	{ "name": "Swamp Fishing Hole", "file": "z2_turibori_info.zsi" },
	{ "name": "Swamp Shooting Gallery", "file": "z2_syateki_mori_info.zsi" },
	{ "name": "Swamp Spider House", "file": "z2_kinsta1_info.zsi" },
	{ "name": "Swordsman's School", "file": "z2_doujou_info.zsi" },
	{ "name": "Termina Field", "file": "z2_00keikoku_info.zsi" },
	{ "name": "Termina Field (Credits Cutscene)", "file": "z2_01keikoku_info.zsi" },
	{ "name": "Termina Field (Credits Cutscene)", "file": "z2_02keikoku_info.zsi" },
	{ "name": "Test Map 01", "file": "test01_info.zsi" },
	{ "name": "Test Map 02", "file": "test02_info.zsi" },
	{ "name": "The Moon", "file": "z2_sougen_info.zsi" },
	{ "name": "The Moon - Deku Trial", "file": "z2_last_deku_info.zsi" },
	{ "name": "The Moon - Goron Trial", "file": "z2_last_goron_info.zsi" },
	{ "name": "The Moon - Link Trial", "file": "z2_last_link_info.zsi" },
	{ "name": "The Moon - Zora Trial", "file": "z2_last_zora_info.zsi" },
	{ "name": "Tourist Information", "file": "z2_map_shop_info.zsi" },
	{ "name": "Town Shooting Gallery", "file": "z2_syateki_mizu_info.zsi" },
	{ "name": "Trading Post", "file": "z2_8itemshop_info.zsi" },
	{ "name": "Treasure Chest Shop", "file": "z2_takaraya_info.zsi" },
	{ "name": "Twinmold's Lair", "file": "z2_inisie_bs_info.zsi" },
	{ "name": "Waterfall Rapids", "file": "z2_35taki_info.zsi" },
	{ "name": "West Clock Town", "file": "z2_ichiba_info.zsi" },
	{ "name": "Woodfall", "file": "z2_21miturinmae_info.zsi" },
	{ "name": "Woodfall Temple", "file": "z2_miturin_info.zsi" },
	{ "name": "Woods of Mystery", "file": "z2_26sarunomori_info.zsi" },
	{ "name": "Zora Cape", "file": "z2_31misaki_info.zsi" },
	{ "name": "Zora Hall", "file": "z2_33zoracity_info.zsi" },
	{ "name": "Zora Hall Rooms", "file": "z2_bandroom_info.zsi" },
	{ "name": "32kamejimamae", "file": "z2_32kamejimamae_info.zsi" },
	{ "name": "meganeana", "file": "z2_meganeana_info.zsi" },
	{ "name": "zolashop", "file": "z2_zolashop_info.zsi" }
]

OOT3D_Maps = [
	{ "name": "Back Alley (Day)", "file": "market_alley_info.zsi" },
	{ "name": "Back Alley (Night)", "file": "market_alley_n_info.zsi" },
	{ "name": "Back Alley House (Dog Lady)", "file": "kakariko_impa_info.zsi" },
	{ "name": "Back Alley House (Man in Green)", "file": "kakariko_home3_info.zsi" },
	{ "name": "Barinade's Lair", "file": "bdan_boss_info.zsi" },
	{ "name": "Bazaar", "file": "shop_info.zsi" },
	{ "name": "Bombchu Bowling Alley", "file": "bowling_info.zsi" },
	{ "name": "Bombchu Shop", "file": "shop_night_info.zsi" },
	{ "name": "Bongo Bongo's Lair", "file": "hakadan_boss_info.zsi" },
	{ "name": "Bottom of the Well", "file": "hakadan_ch_info.zsi" },
	#{ "name": "Bottom of the Well (MQ)", "file": "hakadan_ch_dd_info.zsi" },
	{ "name": "Carpenter Boss's House", "file": "kakariko_info.zsi" },
	{ "name": "Carpenters' Tent", "file": "tent_info.zsi" },
	{ "name": "Castle Courtyard", "file": "nakaniwa_info.zsi" },
	{ "name": "Castle Hedge Maze (Day)", "file": "hairal_niwa_info.zsi" },
	{ "name": "Castle Hedge Maze (Night)", "file": "hairal_niwa_n_info.zsi" },
	{ "name": "Chamber of the Sages", "file": "kenjyanoma_info.zsi" },
	{ "name": "Cutscene Map", "file": "hiral_demo_info.zsi" },
	{ "name": "Dampe's Grave & Windmill", "file": "hakasitarelay_info.zsi" },
	{ "name": "Dodongo's Cavern", "file": "ddan_info.zsi" },
	#{ "name": "Dodongo's Cavern (MQ)", "file": "ddan_dd_info.zsi" },
	{ "name": "Fairy's Fountain (Healing Fairies)", "file": "yousei_izumi_tate_info.zsi" },
	{ "name": "Fire Temple", "file": "hidan_info.zsi" },
	#{ "name": "Fire Temple (MQ)", "file": "hidan_dd_info.zsi" },
	{ "name": "Fishing Pond", "file": "turibori_info.zsi" },
	{ "name": "Forest Temple", "file": "bmori1_info.zsi" },
	#{ "name": "Forest Temple (MQ)", "file": "bmori1_dd_info.zsi" },
	{ "name": "Ganon's Castle Exterior", "file": "ganon_tou_info.zsi" },
	{ "name": "Ganon's Tower", "file": "ganon_info.zsi" },
	{ "name": "Ganon's Tower (Collapsing)", "file": "ganon_sonogo_info.zsi" },
	{ "name": "Ganon's Tower Collapse & Battle Arena", "file": "ganon_demo_info.zsi" },
	{ "name": "Ganondorf's Death Scene (Tower Escape Exterior)", "file": "ganon_final_info.zsi" },
	{ "name": "Ganondorf's Lair", "file": "ganon_boss_info.zsi" },
	{ "name": "Gerudo Training Ground", "file": "men_info.zsi" },
	#{ "name": "Gerudo Training Ground (MQ)", "file": "men_dd_info.zsi" },
	{ "name": "Gohma's Lair", "file": "ydan_boss_info.zsi" },
	{ "name": "Goron Shop", "file": "shop_golon_info.zsi" },
	{ "name": "Granny's Potion Shop", "file": "mahouya_info.zsi" },
	{ "name": "Grave (Fairy's Fountain)", "file": "hakaana2_info.zsi" },
	{ "name": "Grave (Redead)", "file": "hakaana_info.zsi" },
	{ "name": "Gravekeeper's Hut", "file": "hut_info.zsi" },
	{ "name": "Great Fairy's Fountain (Upgrades)", "file": "daiyousei_izumi_info.zsi" },
	{ "name": "Grottos", "file": "kakusiana_info.zsi" },
	{ "name": "Guard House", "file": "miharigoya_info.zsi" },
	{ "name": "Happy Mask Shop", "file": "shop_face_info.zsi" },
	{ "name": "House of Skulltula", "file": "kinsuta_info.zsi" },
	{ "name": "Ice Cavern", "file": "ice_doukutu_info.zsi" },
	#{ "name": "Ice Cavern (MQ)", "file": "ice_doukutu_dd_info.zsi" },
	{ "name": "Impa's House", "file": "labo_info.zsi" },
	{ "name": "Inside Ganon's Castle", "file": "ganontika_info.zsi" },
	{ "name": "Inside Ganon's Castle (Collapsing)", "file": "ganontikasonogo_info.zsi" },
	#{ "name": "Inside Ganon's Castle (MQ)", "file": "ganontika_dd_info.zsi" },
	{ "name": "Inside Jabu-Jabu's Belly", "file": "bdan_info.zsi" },
	#{ "name": "Inside Jabu-Jabu's Belly (MQ)", "file": "bdan_dd_info.zsi" },
	{ "name": "Inside the Deku Tree", "file": "ydan_info.zsi" },
	#{ "name": "Inside the Deku Tree (MQ)", "file": "ydan_dd_info.zsi" },
	{ "name": "Kakariko Potion Shop", "file": "shop_drag_info.zsi" },
	{ "name": "King Dodongo's Lair", "file": "ddan_boss_info.zsi" },
	{ "name": "Know-It-All Brothers' House", "file": "k_home_info.zsi" },
	{ "name": "Kokiri Shop", "file": "kokiri_info.zsi" },
	{ "name": "Lakeside Laboratory", "file": "hylia_labo_info.zsi" },
	{ "name": "Link's House", "file": "link_info.zsi" },
	{ "name": "Lon Lon Ranch House & Tower", "file": "souko_info.zsi" },
	{ "name": "Market (Child - Day)", "file": "market_day_info.zsi" },
	{ "name": "Market (Child - Night)", "file": "market_night_info.zsi" },
	{ "name": "Market (Ruins)", "file": "market_ruins_info.zsi" },
	{ "name": "Market Entrance (Child - Day)", "file": "entra_day_info.zsi" },
	{ "name": "Market Entrance (Child - Night)", "file": "entra_night_info.zsi" },
	{ "name": "Market Entrance (Ruins)", "file": "entra_ruins_info.zsi" },
	{ "name": "Market Potion Shop", "file": "shop_alley_info.zsi" },
	{ "name": "Mido's House", "file": "k_home4_info.zsi" },
	{ "name": "Morpha's Lair", "file": "mizusin_boss_info.zsi" },
	{ "name": "Phantom Ganon's Lair", "file": "moriboss_info.zsi" },
	{ "name": "Royal Family's Tomb", "file": "hakaana_ouke_info.zsi" },
	{ "name": "Saria's House", "file": "k_home5_info.zsi" },
	{ "name": "Shadow Temple", "file": "hakadan_info.zsi" },
	#{ "name": "Shadow Temple (MQ)", "file": "hakadan_dd_info.zsi" },
	{ "name": "Shooting Gallery", "file": "syatekijyou_info.zsi" },
	{ "name": "Spirit Temple", "file": "jyasinzou_info.zsi" },
	#{ "name": "Spirit Temple (MQ)", "file": "jyasinzou_dd_info.zsi" },
	{ "name": "Spot 00 - Hyrule Field", "file": "spot00_info.zsi" },
	{ "name": "Spot 01 - Kakariko Village", "file": "spot01_info.zsi" },
	{ "name": "Spot 02 - Graveyard", "file": "spot02_info.zsi" },
	{ "name": "Spot 03 - Zora's River", "file": "spot03_info.zsi" },
	{ "name": "Spot 04 - Kokiri Forest", "file": "spot04_info.zsi" },
	{ "name": "Spot 05 - Sacred Forest Meadow", "file": "spot05_info.zsi" },
	{ "name": "Spot 06 - Lake Hylia", "file": "spot06_info.zsi" },
	{ "name": "Spot 07 - Zora's Domain", "file": "spot07_info.zsi" },
	{ "name": "Spot 08 - Zora's Fountain", "file": "spot08_info.zsi" },
	{ "name": "Spot 09 - Gerudo Valley", "file": "spot09_info.zsi" },
	{ "name": "Spot 10 - Lost Woods", "file": "spot10_info.zsi" },
	{ "name": "Spot 11 - Desert Colossus", "file": "spot11_info.zsi" },
	{ "name": "Spot 12 - Gerudo's Fortress", "file": "spot12_info.zsi" },
	{ "name": "Spot 13 - Haunted Wasteland", "file": "spot13_info.zsi" },
	{ "name": "Spot 15 - Hyrule Castle", "file": "spot15_info.zsi" },
	{ "name": "Spot 16 - Death Mountain Trail", "file": "spot16_info.zsi" },
	{ "name": "Spot 17 - Death Mountain Crater", "file": "spot17_info.zsi" },
	{ "name": "Spot 18 - Goron City", "file": "spot18_info.zsi" },
	{ "name": "Spot 20 - Lon Lon Ranch", "file": "spot20_info.zsi" },
	{ "name": "Spot 99 - Hyrule Field (Title)", "file": "spot99_info.zsi" },
	{ "name": "Stable", "file": "stable_info.zsi" },
	{ "name": "Temple of Time", "file": "tokinoma_info.zsi" },
	{ "name": "Temple of Time Exterior (Day)", "file": "shrine_info.zsi" },
	{ "name": "Temple of Time Exterior (Night)", "file": "shrine_n_info.zsi" },
	{ "name": "Temple of Time Exterior (Ruins)", "file": "shrine_r_info.zsi" },
	{ "name": "Thieves' Hideout", "file": "gerudoway_info.zsi" },
	{ "name": "Treasure Chest Shop", "file": "takaraya_info.zsi" },
	{ "name": "Twinrova's Lair & Iron Knuckle Mini-Boss Room", "file": "jyasinzou_boss_info.zsi" },
	{ "name": "Twins' House", "file": "k_home3_info.zsi" },
	{ "name": "Volvagia's Lair", "file": "fire_bs_info.zsi" },
	{ "name": "Water Temple", "file": "mizusin_info.zsi" },
	#{ "name": "Water Temple (MQ)", "file": "mizusin_dd_info.zsi" }
];

OOT_Maps = [
    { "name": "Spot 00 - Hyrule Field", "file": "spot00_scene" },
    { "name": "Spot 01 - Kakariko Village", "file": "spot01_scene" },
    { "name": "Spot 02 - Graveyard", "file": "spot02_scene" },
    { "name": "Spot 03 - Zora's River", "file": "spot03_scene" },
    { "name": "Spot 04 - Kokiri Forest", "file": "spot04_scene" },
    { "name": "Spot 05 - Sacred Forest Meadow", "file": "spot05_scene" },
    { "name": "Spot 06 - Lake Hylia", "file": "spot06_scene" },
    { "name": "Spot 07 - Zora's Domain", "file": "spot07_scene" },
    { "name": "Spot 08 - Zora's Fountain", "file": "spot08_scene" },
    { "name": "Spot 09 - Gerudo Valley", "file": "spot09_scene" },
    { "name": "Spot 10 - Lost Woods", "file": "spot10_scene" },
    { "name": "Spot 11 - Desert Colossus", "file": "spot11_scene" },
    { "name": "Spot 12 - Gerudo's Fortress", "file": "spot12_scene" },
    { "name": "Spot 13 - Haunted Wasteland", "file": "spot13_scene" },
    { "name": "Spot 15 - Hyrule Castle", "file": "spot15_scene" },
    { "name": "Spot 16 - Death Mountain Trail", "file": "spot16_scene" },
    { "name": "Spot 17 - Death Mountain Crater", "file": "spot17_scene" },
    { "name": "Spot 18 - Goron City", "file": "spot18_scene" },
    { "name": "Spot 20 - Lon Lon Ranch", "file": "spot20_scene" },
    { "name": "Back Alley (Day)", "file": "market_alley_scene" },
    { "name": "Back Alley (Night)", "file": "market_alley_n_scene" },
    { "name": "Back Alley House (Dog Lady)", "file": "impa_scene" },
    { "name": "Back Alley House (Man in Green)", "file": "kakariko3_scene" },
    { "name": "Barinade's Lair", "file": "bdan_boss_scene" },
    { "name": "Bazaar", "file": "shop1_scene" },
    { "name": "Bombchu Bowling Alley", "file": "bowling_scene" },
    { "name": "Bombchu Shop", "file": "night_shop_scene" },
    { "name": "Bongo Bongo's Lair", "file": "HAKAdan_bs_scene" },
    { "name": "Bottom of the Well", "file": "HAKAdanCH_scene" },
    { "name": "Carpenter Boss's House", "file": "kakariko_scene" },
    { "name": "Carpenters' Tent", "file": "tent_scene" },
    { "name": "Castle Courtyard", "file": "nakaniwa_scene" },
    { "name": "Castle Hedge Maze (Day)", "file": "hairal_niwa_scene" },
    { "name": "Castle Hedge Maze (Night)", "file": "hairal_niwa_n_scene" },
    { "name": "Chamber of the Sages", "file": "kenjyanoma_scene" },
    { "name": "Cutscene Map", "file": "hiral_demo_scene" },
    { "name": "Dampe's Grave & Windmill", "file": "hakasitarelay_scene" },
    { "name": "Dodongo's Cavern", "file": "ddan_scene" },
    { "name": "Fairy's Fountain (Healing Fairies)", "file": "yousei_izumi_tate_scene" },
    { "name": "Fire Temple", "file": "HIDAN_scene" },
    { "name": "Fishing Pond", "file": "turibori_scene" },
    { "name": "Forest Temple", "file": "Bmori1_scene" },
    { "name": "Ganon's Castle Exterior", "file": "ganon_tou_scene" },
    { "name": "Ganon's Tower", "file": "ganon_scene" },
    { "name": "Ganon's Tower (Collapsing)", "file": "ganon_sonogo_scene" },
    { "name": "Ganon's Tower Collapse & Battle Arena", "file": "ganon_demo_scene" },
    { "name": "Ganon's Tower Exterior (Collapsing)", "file": "ganon_final_scene" },
    { "name": "Ganondorf's Lair", "file": "ganon_boss_scene" },
    { "name": "Gerudo Training Ground", "file": "men_scene" },
    { "name": "Gohma's Lair", "file": "ydan_boss_scene" },
    { "name": "Goron Shop", "file": "golon_scene" },
    { "name": "Granny's Potion Shop", "file": "mahouya_scene" },
    { "name": "Grave (Fairy's Fountain)", "file": "hakaana2_scene" },
    { "name": "Grave (Redead)", "file": "hakaana_scene" },
    { "name": "Gravekeeper's Hut", "file": "hut_scene" },
    { "name": "Great Fairy's Fountain (Spells)", "file": "yousei_izumi_yoko_scene" },
    { "name": "Great Fairy's Fountain (Upgrades)", "file": "daiyousei_izumi_scene" },
    { "name": "Grottos", "file": "kakusiana_scene" },
    { "name": "Guard House", "file": "miharigoya_scene" },
    { "name": "Happy Mask Shop", "file": "face_shop_scene" },
    { "name": "House of Skulltula", "file": "kinsuta_scene" },
    { "name": "House of Twins", "file": "kokiri_home3_scene" },
    { "name": "Ice Cavern", "file": "ice_doukutu_scene" },
    { "name": "Impa's House", "file": "labo_scene" },
    { "name": "Inside Ganon's Castle", "file": "ganontika_scene" },
    { "name": "Inside Ganon's Castle (Collapsing)", "file": "ganontikasonogo_scene" },
    { "name": "Inside Jabu-Jabu's Belly", "file": "bdan_scene" },
    { "name": "Inside the Deku Tree", "file": "ydan_scene" },
    { "name": "Kakariko Potion Shop", "file": "drag_scene" },
    { "name": "King Dodongo's Lair", "file": "ddan_boss_scene" },
    { "name": "Know-It-All Brothers' House", "file": "kokiri_home_scene" },
    { "name": "Kokiri Shop", "file": "kokiri_shop_scene" },
    { "name": "Lakeside Laboratory", "file": "hylia_labo_scene" },
    { "name": "Link's House", "file": "link_home_scene" },
    { "name": "Lon Lon Ranch House & Tower", "file": "souko_scene" },
    { "name": "Market (Child - Day)", "file": "market_day_scene" },
    { "name": "Market (Child - Night)", "file": "market_night_scene" },
    { "name": "Market (Ruins)", "file": "market_ruins_scene" },
    { "name": "Market Entrance (Child - Day)", "file": "entra_scene" },
    { "name": "Market Entrance (Child - Night)", "file": "entra_n_scene" },
    { "name": "Market Entrance (Ruins)", "file": "enrui_scene" },
    { "name": "Market Potion Shop", "file": "alley_shop_scene" },
    { "name": "Mido's House", "file": "kokiri_home4_scene" },
    { "name": "Morpha's Lair", "file": "MIZUsin_bs_scene" },
    { "name": "Phantom Ganon's Lair", "file": "moribossroom_scene" },
    { "name": "Royal Family's Tomb", "file": "hakaana_ouke_scene" },
    { "name": "Saria's House", "file": "kokiri_home5_scene" },
    { "name": "Shadow Temple", "file": "HAKAdan_scene" },
    { "name": "Shooting Gallery", "file": "syatekijyou_scene" },
    { "name": "Spirit Temple", "file": "jyasinzou_scene" },
    { "name": "Stable", "file": "malon_stable_scene" },
    { "name": "Temple of Time", "file": "tokinoma_scene" },
    { "name": "Temple of Time Exterior (Day)", "file": "shrine_scene" },
    { "name": "Temple of Time Exterior (Night)", "file": "shrine_n_scene" },
    { "name": "Temple of Time Exterior (Ruins)", "file": "shrine_r_scene" },
    { "name": "Thieves' Hideout", "file": "gerudoway_scene" },
    { "name": "Treasure Chest Shop", "file": "takaraya_scene" },
    { "name": "Twinrova's Lair & Iron Knuckle's Lair", "file": "jyasinboss_scene" },
    { "name": "Volvagia's Lair", "file": "FIRE_bs_scene" },
    { "name": "Water Temple", "file": "MIZUsin_scene" },
    { "name": "Zora Shop", "file": "zoora_scene" }
];

MM_Maps = [
    { "name": "Ancient Castle of Ikana", "file": "Z2_CASTLE" },
    { "name": "Astral Observatory", "file": "Z2_TENMON_DAI" },
    { "name": "Before the Portal to Termina", "file": "Z2_OPENINGDAN" },
    { "name": "Beneath the Graveyard", "file": "Z2_HAKASHITA" },
    { "name": "Beneath the Well", "file": "Z2_REDEAD" },
    { "name": "Bomb Shop", "file": "Z2_BOMYA" },
    { "name": "Clock Tower Interior", "file": "Z2_INSIDETOWER" },
    { "name": "Clock Tower Rooftop", "file": "Z2_OKUJOU" },
    { "name": "Cucco Shack", "file": "Z2_F01C" },
    { "name": "Curiosity Shop", "file": "Z2_AYASHIISHOP" },
    { "name": "Cutscene Map", "file": "SPOT00" },
    { "name": "Dampe's House", "file": "Z2_DANPEI2TEST" },
    { "name": "Deku King's Chamber", "file": "Z2_DEKU_KING" },
    { "name": "Deku Palace", "file": "Z2_22DEKUCITY" },
    { "name": "Deku Scrub Playground", "file": "Z2_DEKUTES" },
    { "name": "Deku Shrine", "file": "Z2_DANPEI" },
    { "name": "Doggy Racetrack", "file": "Z2_F01_B" },
    { "name": "East Clock Town", "file": "Z2_TOWN" },
    { "name": "Fairy's Fountain", "file": "Z2_YOUSEI_IZUMI" },
    { "name": "Fisherman's Hut", "file": "Z2_FISHERMAN" },
    { "name": "Ghost Hut", "file": "Z2_TOUGITES" },
    { "name": "Giants' Chamber", "file": "Z2_KYOJINNOMA" },
    { "name": "Goht's Lair", "file": "Z2_HAKUGIN_BS" },
    { "name": "Gorman Track", "file": "Z2_KOEPONARACE" },
    { "name": "Goron Graveyard", "file": "Z2_GORON_HAKA" },
    { "name": "Goron Racetrack", "file": "Z2_GORONRACE" },
    { "name": "Goron Shop", "file": "Z2_GORONSHOP" },
    { "name": "Goron Shrine", "file": "Z2_16GORON_HOUSE" },
    { "name": "Goron Village (Spring)", "file": "Z2_11GORONNOSATO2" },
    { "name": "Goron Village (Winter)", "file": "Z2_11GORONNOSATO" },
    { "name": "Great Bay (Cutscene)", "file": "Z2_KONPEKI_ENT" },
    { "name": "Great Bay Coast", "file": "Z2_30GYOSON" },
    { "name": "Great Bay Temple", "file": "Z2_SEA" },
    { "name": "Grottos", "file": "KAKUSIANA" },
    { "name": "Gyorg's Lair", "file": "Z2_SEA_BS" },
    { "name": "Honey & Darling's Shop", "file": "Z2_BOWLING" },
    { "name": "Igos du Ikana's Lair", "file": "Z2_IKNINSIDE" },
    { "name": "Ikana Canyon", "file": "Z2_IKANA" },
    { "name": "Ikana Graveyard", "file": "Z2_BOTI" },
    { "name": "Laundry Pool", "file": "Z2_ALLEY" },
    { "name": "Lost Woods", "file": "Z2_LOST_WOODS" },
    { "name": "Lottery Shop", "file": "Z2_TAKARAKUJI" },
    { "name": "Magic Hags' Potion Shop", "file": "Z2_WITCH_SHOP" },
    { "name": "Majora's Lair", "file": "Z2_LAST_BS" },
    { "name": "Marine Research Lab", "file": "Z2_LABO" },
    { "name": "Mayor's Residence", "file": "Z2_SONCHONOIE" },
    { "name": "Milk Bar", "file": "Z2_MILK_BAR" },
    { "name": "Milk Road", "file": "Z2_ROMANYMAE" },
    { "name": "Mountain Smithy", "file": "Z2_KAJIYA" },
    { "name": "Mountain Village (Spring)", "file": "Z2_10YUKIYAMANOMURA2" },
    { "name": "Mountain Village (Winter)", "file": "Z2_10YUKIYAMANOMURA" },
    { "name": "Music Box House", "file": "Z2_MUSICHOUSE" },
    { "name": "North Clock Town", "file": "Z2_BACKTOWN" },
    { "name": "Oceanside Spider House", "file": "Z2_KINDAN2" },
    { "name": "Odolwa's Lair", "file": "Z2_MITURIN_BS" },
    { "name": "Path to Goron Village (Spring)", "file": "Z2_17SETUGEN2" },
    { "name": "Path to Goron Village (Winter)", "file": "Z2_17SETUGEN" },
    { "name": "Path to Mountain Village", "file": "Z2_13HUBUKINOMITI" },
    { "name": "Path to Snowhead", "file": "Z2_14YUKIDAMANOMITI" },
    { "name": "Pinnacle Rock", "file": "Z2_SINKAI" },
    { "name": "Pirates' Fortress", "file": "Z2_KAIZOKU" },
    { "name": "Pirates' Fortress Exterior", "file": "Z2_TORIDE" },
    { "name": "Pirates' Fortress Interior", "file": "Z2_PIRATE" },
    { "name": "Post Office", "file": "Z2_POSTHOUSE" },
    { "name": "Ranch House & Barn", "file": "Z2_OMOYA" },
    { "name": "Road to Ikana", "file": "Z2_IKANAMAE" },
    { "name": "Road to Southern Swamp", "file": "Z2_24KEMONOMITI" },
    { "name": "Romani Ranch", "file": "Z2_F01" },
    { "name": "Sakon's Hideout", "file": "Z2_SECOM" },
    { "name": "Secret Shrine", "file": "Z2_RANDOM" },
    { "name": "Snowhead", "file": "Z2_12HAKUGINMAE" },
    { "name": "Snowhead Temple", "file": "Z2_HAKUGIN" },
    { "name": "South Clock Town", "file": "Z2_CLOCKTOWER" },
    { "name": "Southern Swamp (Clear)", "file": "Z2_20SICHITAI2" },
    { "name": "Southern Swamp (Poisoned)", "file": "Z2_20SICHITAI" },
    { "name": "Stock Pot Inn", "file": "Z2_YADOYA" },
    { "name": "Stone Tower", "file": "Z2_F40" },
    { "name": "Stone Tower (Inverted)", "file": "Z2_F41" },
    { "name": "Stone Tower Temple", "file": "Z2_INISIE_N" },
    { "name": "Stone Tower Temple (Inverted)", "file": "Z2_INISIE_R" },
    { "name": "Swamp Shooting Gallery", "file": "Z2_SYATEKI_MORI" },
    { "name": "Swamp Spider House", "file": "Z2_KINSTA1" },
    { "name": "Swordsman's School", "file": "Z2_DOUJOU" },
    { "name": "Termina Field", "file": "Z2_00KEIKOKU" },
    { "name": "The Moon", "file": "Z2_SOUGEN" },
    { "name": "The Moon - Deku Trial", "file": "Z2_LAST_DEKU" },
    { "name": "The Moon - Goron Trial", "file": "Z2_LAST_GORON" },
    { "name": "The Moon - Link Trial", "file": "Z2_LAST_LINK" },
    { "name": "The Moon - Zora Trial", "file": "Z2_LAST_ZORA" },
    { "name": "Tourist Information", "file": "Z2_MAP_SHOP" },
    { "name": "Town Shooting Gallery", "file": "Z2_SYATEKI_MIZU" },
    { "name": "Trading Post", "file": "Z2_8ITEMSHOP" },
    { "name": "Treasure Chest Shop", "file": "Z2_TAKARAYA" },
    { "name": "Twinmold's Lair", "file": "Z2_INISIE_BS" },
    { "name": "Waterfall Rapids", "file": "Z2_35TAKI" },
    { "name": "West Clock Town", "file": "Z2_ICHIBA" },
    { "name": "Woodfall", "file": "Z2_21MITURINMAE" },
    { "name": "Woodfall Temple", "file": "Z2_MITURIN" },
    { "name": "Woods of Mystery", "file": "Z2_26SARUNOMORI" },
    { "name": "Zora Cape", "file": "Z2_31MISAKI" },
    { "name": "Zora Hall", "file": "Z2_33ZORACITY" },
    { "name": "Zora Hall Rooms", "file": "Z2_BANDROOM" }
];

# Build a lookup from file prefix -> map object
prefix_to_map = {entry["file"].replace(".zsi", ""): entry for entry in OOT_Maps}

# Scan current directory for *_seams.txt files
for fname in os.listdir("."):
    if fname.endswith("_seams.txt"):
        # extract prefix
        prefix = re.sub(r"_seams\.txt$", "", fname)
        if prefix in prefix_to_map:
            prefix_to_map[prefix]["seams"] = fname
        else:
            print(f"Warning: {fname} does not match any map in OOT_Maps")

# Output updated JS array
js_array = "const OOT_Maps = " + json.dumps(OOT_Maps, indent=4) + ";"

with open("OOT_Maps_updated.js", "w", encoding="utf-8") as f:
    f.write(js_array)

print("Done. Updated OOT with seams files.")